const COMMANDS=Object.freeze([
  ['explore','EXPLORE'],['flight','FLIGHT'],['intelligence','INTELLIGENCE'],['replay','REPLAY'],['compare','COMPARE'],['what-if','WHAT IF'],['sequences','SEQUENCES'],['trickster','CREATE'],['evidence','EVIDENCE']
]);
const MODE_HINTS=Object.freeze({opening:'',explore:'SELECT ACTIVITY · FLY THE FIELD · SEARCH THE CHAIN · TURN EVIDENCE INTO PLAYABLE STORIES',flight:'FLY · BOOST · SCAN · REVEAL · NAVIGATE EVIDENCE · SWITCH BETWEEN NAVIGATION AND MISSIONS',intelligence:'INSPECT VERIFIED ACTIVITY · FOLLOW EVIDENCE · OPEN REPLAY',replay:'PLAY · PAUSE · REWIND · STEP THROUGH CHAIN TIME',compare:'COMPARE EVIDENCE SIDE BY SIDE · KEEP TIMELINES SYNCHRONIZED','what-if':'SIMULATE FROM OBSERVED EVIDENCE · ESTIMATES STAY LABELED',sequences:'DISCOVER BOUNDED MARKET SEQUENCES · PLAY THE EVIDENCE',trickster:'COMPOSE A DATA STORY · EVERY PUBLISHED CLAIM KEEPS ITS RECEIPT',evidence:'VERIFY SOURCES · COVERAGE · RECEIPTS · ORIGINAL CHAIN TIME'});
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!=null)n.textContent=text;return n;}
export function fieldInvestigationHopRequest(item={}){const entityId=String(item.id||'').trim(),entityKind=String(item.kind||'').trim(),evidenceIds=Object.freeze((Array.isArray(item.evidenceIds)?item.evidenceIds:[]).map(value=>String(value||'').trim()).filter(Boolean));if(!entityId||!entityKind||!evidenceIds.length)return null;return Object.freeze({source:'field-investigation-hop',query:entityId,entityId,entityKind,evidenceIds});}
export function createFieldShell({host,serviceState='ready',onCommand,onSearch}){
  if(!(host instanceof Element))throw new TypeError('host element is required');
  const root=el('div','field-shell');root.dataset.mode='opening';const fieldHost=el('div','field-shell__field');fieldHost.setAttribute('aria-label','Playable Solana particle universe');const chrome=el('div','field-shell__chrome'),top=el('header','field-shell__top');const brand=el('button','field-shell__brand','A BULLS APP');brand.type='button';brand.addEventListener('click',()=>closeWorkspace());const search=el('form','field-shell__search');search.setAttribute('role','search');const input=document.createElement('input');input.type='search';input.autocomplete='off';input.spellcheck=false;input.placeholder='Search wallet · transaction · token · NFT · program';input.setAttribute('aria-label',input.placeholder);search.append(input,el('span','','READ ONLY'));search.addEventListener('submit',event=>{event.preventDefault();const value=input.value.trim();if(value)onSearch?.(value);});const status=el('div','field-shell__status',serviceState==='ready'?'● SYSTEMS READY':'● PARTIAL SERVICE');top.append(brand,search,status);
  const commandDock=el('nav','field-shell__commands');commandDock.setAttribute('aria-label','Particle Universe modes');for(const [id,label] of COMMANDS){const b=el('button','field-shell__command',label);b.type='button';b.dataset.fieldCommand=id;b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>onCommand?.(id));commandDock.append(b);}const investigationDock=el('aside','field-shell__investigation');investigationDock.hidden=true;investigationDock.setAttribute('aria-live','polite');const workspace=el('section','field-shell__workspace');workspace.hidden=true;workspace.setAttribute('aria-live','polite');const workspaceHead=el('div','field-shell__workspace-head'),workspaceTitle=el('strong','','INTELLIGENCE'),close=el('button','field-shell__close','RETURN TO FIELD ×');close.type='button';close.addEventListener('click',()=>closeWorkspace());workspaceHead.append(workspaceTitle,close);const workspaceBody=el('div','field-shell__workspace-body');workspace.append(workspaceHead,workspaceBody);const hint=el('div','field-shell__hint','');const enter=el('button','field-shell__enter','ENTER UNIVERSE');enter.type='button';enter.setAttribute('aria-label','Enter A Bulls App Particle Universe');enter.addEventListener('click',()=>setActive('explore'));chrome.append(top,investigationDock,commandDock,hint,enter);root.append(fieldHost,chrome,workspace);host.replaceChildren(root);
  function setActive(command='explore'){const mode=MODE_HINTS[command]!==undefined?command:'explore';root.dataset.mode=mode;hint.textContent=MODE_HINTS[mode];root.querySelectorAll('[data-field-command]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.fieldCommand===mode)));globalThis.dispatchEvent(new CustomEvent('abulls:field-mode',{detail:{mode}}));}
  function renderInvestigation(hub){investigationDock.replaceChildren();if(!hub?.focusId){investigationDock.hidden=true;return;}investigationDock.hidden=false;const heading=el('div','field-shell__investigation-title',`${String(hub.focusKind||'entity').toUpperCase()} FOCUS`),count=el('div','field-shell__investigation-count',hub.evidenceCount?`${hub.evidenceCount} EVIDENCE-BACKED CONNECTION${hub.evidenceCount===1?'':'S'}`:'NO INDEXED CONNECTION EVIDENCE'),trail=el('div','field-shell__investigation-actions'),connected=el('div','field-shell__investigation-connected'),actions=el('div','field-shell__investigation-actions');if(hub.navigation?.canBack){const back=el('button','field-shell__investigation-action','← BACK');back.type='button';back.addEventListener('click',()=>globalThis.dispatchEvent(new CustomEvent('abulls:field-investigation-back')));trail.append(back);}if(hub.navigation?.canForward){const forward=el('button','field-shell__investigation-action','FORWARD →');forward.type='button';forward.addEventListener('click',()=>globalThis.dispatchEvent(new CustomEvent('abulls:field-investigation-forward')));trail.append(forward);}for(const item of (Array.isArray(hub.nodes)?hub.nodes:[])){const request=fieldInvestigationHopRequest(item);if(item.focused||!request)continue;const button=el('button','field-shell__investigation-action field-shell__investigation-node',`${String(item.kind||'entity').toUpperCase()} · ${String(item.id).slice(0,8)}`);button.type='button';button.title=`Open exact loaded entity · ${request.evidenceIds.length} receipt${request.evidenceIds.length===1?'':'s'}`;button.addEventListener('click',()=>globalThis.dispatchEvent(new CustomEvent('abulls:universal-search',{detail:request})));connected.append(button);}for(const action of (Array.isArray(hub.actions)?hub.actions:[])){const button=el('button','field-shell__investigation-action',action.label);button.type='button';button.dataset.simulation=String(Boolean(action.simulation));button.addEventListener('click',()=>onCommand?.(action.id,{investigationHub:hub,focusId:hub.focusId,focusKind:hub.focusKind,simulation:Boolean(action.simulation)}));actions.append(button);}investigationDock.append(heading,count);if(trail.childElementCount)investigationDock.append(trail);if(connected.childElementCount)investigationDock.append(connected);investigationDock.append(actions);investigationDock.title=hub.disclosure||'';}
  const onInvestigation=event=>renderInvestigation(event?.detail);globalThis.addEventListener('abulls:field-investigation-hub',onInvestigation);
  function mountWorkspace(content,{title='INTELLIGENCE',mode='intelligence'}={}){workspaceTitle.textContent=title;workspaceBody.replaceChildren();if(content instanceof Element)workspaceBody.append(content);workspace.hidden=false;root.classList.add('field-shell--workspace-open');root.classList.toggle('field-shell--flight-open',mode==='flight');setActive(mode);return workspaceBody;}
  function closeWorkspace(){workspaceBody.replaceChildren();workspace.hidden=true;root.classList.remove('field-shell--workspace-open','field-shell--flight-open');setActive('explore');globalThis.dispatchEvent(new CustomEvent('abulls:field-return'));}
  return Object.freeze({root,fieldHost,workspaceBody,focusSearch:()=>input.focus(),mountWorkspace,closeWorkspace,setActive,showOpening:()=>setActive('opening'),renderInvestigation,destroy:()=>{globalThis.removeEventListener('abulls:field-investigation-hub',onInvestigation);root.remove();}});
}
export const FieldCommands=COMMANDS;
