const COMMANDS=Object.freeze([
  ['explore','FIELD'],['game','GAME'],['intelligence','INTELLIGENCE'],['replay','REPLAY'],['compare','COMPARE'],['what-if','WHAT IF'],['sequences','SEQUENCES'],['trickster','CREATE'],['evidence','EVIDENCE']
]);
const MODE_HINTS=Object.freeze({explore:'PARTICLE FIELD · SEARCH · SELECT · INVESTIGATE',game:'GAME ATTACHED TO PARTICLE FIELD · NAVIGATION OR MISSION FLIGHT',intelligence:'INSPECT VERIFIED ACTIVITY · FOLLOW EVIDENCE · OPEN REPLAY',replay:'PLAY · PAUSE · REWIND · STEP THROUGH CHAIN TIME',compare:'COMPARE EVIDENCE SIDE BY SIDE','what-if':'SIMULATE FROM OBSERVED EVIDENCE · ESTIMATES STAY LABELED',sequences:'DISCOVER BOUNDED MARKET SEQUENCES',trickster:'CREATE DATA STORIES WITH RECEIPTS',evidence:'VERIFY SOURCES · COVERAGE · RECEIPTS'});
function el(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!=null)n.textContent=text;return n;}
export function fieldInvestigationHopRequest(item={}){const entityId=String(item.id||'').trim(),entityKind=String(item.kind||'').trim(),evidenceIds=Object.freeze((Array.isArray(item.evidenceIds)?item.evidenceIds:[]).map(value=>String(value||'').trim()).filter(Boolean));if(!entityId||!entityKind||!evidenceIds.length)return null;return Object.freeze({source:'field-investigation-hop',query:entityId,entityId,entityKind,evidenceIds});}
export function createFieldShell({host,serviceState='ready',onCommand,onSearch}){
  if(!(host instanceof Element))throw new TypeError('host element is required');
  const root=el('div','field-shell');root.dataset.mode='explore';
  const fieldHost=el('div','field-shell__field');fieldHost.setAttribute('aria-label','A Bulls App Particle Field');
  const chrome=el('div','field-shell__chrome'),top=el('header','field-shell__top');
  const brand=el('button','field-shell__brand','A BULLS APP');brand.type='button';brand.addEventListener('click',()=>closeWorkspace());
  const search=el('form','field-shell__search');search.setAttribute('role','search');const input=document.createElement('input');input.type='search';input.autocomplete='off';input.spellcheck=false;input.placeholder='Search wallet · transaction · token · NFT · program';input.setAttribute('aria-label',input.placeholder);search.append(input,el('span','','READ ONLY'));search.addEventListener('submit',event=>{event.preventDefault();const value=input.value.trim();if(value)onSearch?.(value);});
  const status=el('div','field-shell__status',serviceState==='ready'?'● FIELD READY':'● PARTIAL SERVICE');top.append(brand,search,status);
  const commandDock=el('nav','field-shell__commands');commandDock.setAttribute('aria-label','Particle Field functions');for(const [id,label] of COMMANDS){const b=el('button','field-shell__command',label);b.type='button';b.dataset.fieldCommand=id;b.setAttribute('aria-pressed',String(id==='explore'));b.addEventListener('click',()=>onCommand?.(id));commandDock.append(b);}
  const investigationDock=el('aside','field-shell__investigation');investigationDock.hidden=true;investigationDock.setAttribute('aria-live','polite');
  const workspace=el('section','field-shell__workspace');workspace.hidden=true;workspace.setAttribute('aria-live','polite');const workspaceHead=el('div','field-shell__workspace-head'),workspaceTitle=el('strong','','INTELLIGENCE'),close=el('button','field-shell__close','RETURN TO FIELD ×');close.type='button';close.addEventListener('click',()=>closeWorkspace());workspaceHead.append(workspaceTitle,close);const workspaceBody=el('div','field-shell__workspace-body');workspace.append(workspaceHead,workspaceBody);
  const hint=el('div','field-shell__hint',MODE_HINTS.explore);chrome.append(top,investigationDock,commandDock,hint);root.append(fieldHost,chrome,workspace);host.replaceChildren(root);
  function setActive(command='explore'){const mode=MODE_HINTS[command]!==undefined?command:'explore';root.dataset.mode=mode;hint.textContent=MODE_HINTS[mode];root.querySelectorAll('[data-field-command]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.fieldCommand===mode)));globalThis.dispatchEvent(new CustomEvent('abulls:field-mode',{detail:{mode}}));}
  function renderInvestigation(hub){investigationDock.replaceChildren();if(!hub?.focusId){investigationDock.hidden=true;return;}investigationDock.hidden=false;const heading=el('div','field-shell__investigation-title',`${String(hub.focusKind||'entity').toUpperCase()} FOCUS`),count=el('div','field-shell__investigation-count',hub.evidenceCount?`${hub.evidenceCount} EVIDENCE CONNECTION${hub.evidenceCount===1?'':'S'}`:'FOCUS ONLY'),actions=el('div','field-shell__investigation-actions');for(const action of (Array.isArray(hub.actions)?hub.actions:[])){const button=el('button','field-shell__investigation-action',action.label);button.type='button';button.addEventListener('click',()=>onCommand?.(action.id,{investigationHub:hub,focusId:hub.focusId,focusKind:hub.focusKind,simulation:Boolean(action.simulation)}));actions.append(button);}investigationDock.append(heading,count,actions);}
  const onInvestigation=event=>renderInvestigation(event?.detail);globalThis.addEventListener('abulls:field-investigation-hub',onInvestigation);
  function mountWorkspace(content,{title='INTELLIGENCE',mode='intelligence'}={}){workspaceTitle.textContent=title;workspaceBody.replaceChildren();if(content instanceof Element)workspaceBody.append(content);workspace.hidden=false;root.classList.add('field-shell--workspace-open');root.classList.toggle('field-shell--game-open',mode==='game');setActive(mode);return workspaceBody;}
  function closeWorkspace(){workspaceBody.replaceChildren();workspace.hidden=true;root.classList.remove('field-shell--workspace-open','field-shell--game-open');setActive('explore');globalThis.dispatchEvent(new CustomEvent('abulls:field-return'));}
  return Object.freeze({root,fieldHost,workspaceBody,focusSearch:()=>input.focus(),mountWorkspace,closeWorkspace,setActive,renderInvestigation,destroy:()=>{globalThis.removeEventListener('abulls:field-investigation-hub',onInvestigation);root.remove();}});
}
export const FieldCommands=COMMANDS;
