import { composeGuidedStory } from './trickster-composer.mjs';
import { buildStoryTimeline } from './trickster-timeline.mjs';
import { chooseExportPlan,detectExportCapabilities } from './trickster-export-capabilities.mjs';
import { TradeReplayPlayer } from './trade-replay-player.mjs';
import { eventStoryScenePlan, summarizeEventStoryDirection } from './event-story-director.mjs';
import { resolveEventStoryFocus } from './event-story-focus.mjs';
import { buildEventStorySceneRuntime } from './event-story-scene-runtime.mjs';
import { buildEventStorySceneSlice } from './event-story-scene-slice.mjs';
import { buildEventStoryRenderPlan } from './event-story-render-plan.mjs';

function node(tag,className,text){const item=document.createElement(tag);if(className)item.className=className;if(text!=null)item.textContent=text;return item;}
function replayEvents(bundle){return Array.isArray(bundle?.replayEvents)?bundle.replayEvents:Array.isArray(bundle?.replay?.events)?bundle.replay.events:[];}
function replayCandles(bundle){return Array.isArray(bundle?.candles)?bundle.candles:Array.isArray(bundle?.replay?.candles)?bundle.replay.candles:[];}
function short(value){const text=String(value||'');return text.length>18?`${text.slice(0,8)}…${text.slice(-7)}`:text;}
function priceModeLabel(bundle){const selection=bundle?.priceSelection;if(selection?.mode==='indexed-quote-pair'&&selection.quoteMint)return `PRICE OVERLAY · ${short(selection.quoteMint)} · ${selection.bucketSeconds}s`;return bundle?.storyType==='transaction-replay'&&bundle?.marketContext?'TIME-ONLY · NO PRICE MARKET SELECTED':null;}

export class TricksterStudio {
  #host;#root;#bundle=null;#manifest=null;#timeline=null;#direction=null;#sceneRuntime=[];#renderPlan=[];#player=null;#previewBody=null;#onExport;#onOpenEvidence;#status;
  constructor({host,onExport,onOpenEvidence}){if(!(host instanceof Element))throw new TypeError('host element is required');this.#host=host;this.#onExport=onExport;this.#onOpenEvidence=onOpenEvidence;this.#root=node('section','trickster-studio');this.#root.setAttribute('aria-labelledby','tricksterTitle');this.#renderEmpty();this.#host.replaceChildren(this.#root);}
  #header(){const header=node('header','trickster-studio__header'),copy=node('div');copy.append(node('small','','DATA STORY STUDIO'));const title=node('h1','','Trickster');title.id='tricksterTitle';copy.append(title,node('p','','Turn verified public-chain evidence into a cinematic, shareable story—without editing a timeline.'));this.#status=node('span','status-pill','WAITING FOR EVIDENCE');header.append(copy,this.#status);return header;}
  #renderEmpty(){this.#player?.destroy();this.#player=null;this.#direction=null;this.#sceneRuntime=[];this.#renderPlan=[];this.#previewBody=null;this.#root.replaceChildren(this.#header());const empty=node('div','trickster-empty');empty.append(node('strong','','Start from evidence, not a blank canvas.'),node('p','','Open a wallet, transaction, token, NFT, or network event in Intelligence, then choose Create Story.'),node('button','primary','OPEN INTELLIGENCE'));empty.querySelector('button').addEventListener('click',()=>this.#onOpenEvidence?.());this.#root.append(empty);}
  loadEvidence(bundle){if(!bundle?.storyType||!bundle?.subject||!bundle?.coverage||!bundle?.evidence?.length)throw new TypeError('complete evidence bundle is required');this.#bundle=structuredClone(bundle);const isDirected=bundle.storyType==='transaction-replay'&&bundle.marketContext;this.#direction=isDirected?summarizeEventStoryDirection(bundle):null;this.#manifest=composeGuidedStory({id:bundle.id||`story-${Date.now()}`,storyType:bundle.storyType,subject:bundle.subject,coverage:bundle.coverage,evidence:bundle.evidence,claims:bundle.claims||[],scenePlan:isDirected?eventStoryScenePlan(bundle):undefined,output:bundle.output||{}});this.#sceneRuntime=isDirected?buildEventStorySceneRuntime(this.#bundle,this.#manifest):[];this.#timeline=buildStoryTimeline(this.#manifest,{fps:30,maxSeconds:90});this.#renderPlan=isDirected?buildEventStoryRenderPlan(this.#timeline,this.#sceneRuntime):[];this.#renderReady();return this.#manifest;}
  #mountFullReplay(){if(!this.#previewBody)return;this.#player?.destroy();this.#player=null;this.#previewBody.replaceChildren();const events=replayEvents(this.#bundle),candles=replayCandles(this.#bundle),focus=resolveEventStoryFocus(this.#bundle);if(!events.length){this.#previewBody.append(node('div','trickster-preview__frame',this.#manifest.storyType.replaceAll('-',' ').toUpperCase()));return;}const replayHost=node('div','trickster-preview__replay');this.#previewBody.append(replayHost);this.#player=new TradeReplayPlayer({host:replayHost,events,candles,startTime:this.#bundle?.replay?.startTime,endTime:this.#bundle?.replay?.endTime,rate:this.#bundle?.replay?.rate||1,label:`${this.#manifest.storyType.replaceAll('-',' ')} playable evidence replay`,focusSignature:focus.signature,focusTimestamp:focus.timestamp});if(focus.id)this.#player.focusReplayEvent(focus.id);}
  #mountScenePreview(runtime){if(!this.#previewBody||!runtime)return;this.#player?.destroy();this.#player=null;this.#previewBody.replaceChildren();const slice=buildEventStorySceneSlice(this.#bundle,runtime);if(slice.mode==='route-context'){const card=node('div','trickster-scene-evidence');card.append(node('small','','ROUTE CONTEXT'),node('strong','',`${slice.routeRows} indexed route rows`));const venues=this.#bundle?.marketContext?.routes?.venues||[],pools=this.#bundle?.marketContext?.routes?.pools||[];card.append(node('p','',venues.length?`Observed venues: ${venues.slice(0,4).map(item=>`${item.id} (${item.count})`).join(' · ')}`:'No indexed venue labels in this scene window.'),node('p','',pools.length?`Observed pools: ${pools.slice(0,3).map(item=>short(item.id)).join(' · ')}`:'No indexed pool labels in this scene window.'),node('p','notice','Route context is evidence summary only; no hop path is animated unless indexed hop-level evidence exists.'));this.#previewBody.append(card);return;}
    if(slice.mode==='evidence-close'){const card=node('div','trickster-scene-evidence');card.append(node('small','','EVIDENCE CLOSE'),node('strong','',`${slice.evidenceCount} frozen evidence receipts`),node('p','',this.#manifest.coverage.statement),node('p','notice','This closing scene summarizes coverage and receipts. It does not add market motion or new claims.'));this.#previewBody.append(card);return;}
    const replayHost=node('div','trickster-preview__replay');this.#previewBody.append(replayHost);const label=slice.mode==='focus-event'?'Selected event scene':slice.mode==='market-window'?'Bounded market window scene':'Explicit price aftermath scene';this.#player=new TradeReplayPlayer({host:replayHost,events:slice.events,candles:slice.candles,startTime:slice.startTime??this.#bundle?.replay?.startTime,endTime:slice.endTime??this.#bundle?.replay?.endTime,rate:1,label,focusTimestamp:slice.mode==='price-aftermath'?slice.startTime:null});if(slice.focusId&&slice.events.length)this.#player.focusReplayEvent(slice.focusId);}
  #renderReady(){this.#player?.destroy();this.#player=null;this.#root.replaceChildren(this.#header());this.#status.textContent=this.#manifest.coverage.verifiedPercent===100?'VERIFIED EVIDENCE':'PARTIAL COVERAGE';const layout=node('div','trickster-layout'),preview=node('section','trickster-preview');preview.setAttribute('aria-label','Story preview');const events=replayEvents(this.#bundle),pricing=priceModeLabel(this.#bundle);if(pricing)preview.append(node('div','trickster-price-mode',pricing));this.#previewBody=node('div','trickster-preview__body');preview.append(this.#previewBody);this.#mountFullReplay();preview.append(node('p','',`${this.#timeline.durationSeconds.toFixed(1)} seconds · ${this.#manifest.output.aspectRatio} · ${this.#timeline.scenes.length} scenes${events.length?` · ${events.length} replay events`:''}`));
    const storyColumn=node('div','trickster-story-column');
    if(this.#direction){const directed=node('section','trickster-directed-beats');directed.append(node('strong','','EVIDENCE-DIRECTED STORY FLOW'));const list=node('ol','trickster-directed-beats__list');for(const beat of this.#direction.beats){const item=node('li','trickster-directed-beat'),copy=node('div');copy.append(node('strong','',beat.title),node('small','',`${beat.purpose}${beat.claimIds.length?` · ${beat.claimIds.length} evidence-backed claim${beat.claimIds.length===1?'':'s'}`:''}`));item.append(copy);list.append(item);}directed.append(list,node('p','notice',this.#direction.disclosure));storyColumn.append(directed);}
    const scenes=node('ol','trickster-scenes');for(const scene of this.#timeline.scenes){const runtime=this.#sceneRuntime.find(item=>item.sceneId===scene.id)||null,render=this.#renderPlan.find(item=>item.sceneId===scene.id)||null,wrapper=node('li','trickster-scene-item'),button=node('button','trickster-scene'),number=node('span','',String(scenes.children.length+1).padStart(2,'0')),copy=node('div');button.type='button';const runtimeText=runtime?` · ${runtime.mode.replaceAll('-',' ')}`:'';const frameText=render?` · frames ${render.startFrame}-${render.endFrame}`:'';copy.append(node('strong','',scene.type.replaceAll('-',' ')),node('small','',`${(scene.durationFrames/this.#timeline.fps).toFixed(1)}s · ${scene.claims.length} evidence-backed claims${runtimeText}${frameText}`));button.append(number,copy);if(runtime){button.addEventListener('click',()=>{for(const current of scenes.querySelectorAll('.trickster-scene[aria-current="true"]'))current.removeAttribute('aria-current');button.setAttribute('aria-current','true');this.#mountScenePreview(runtime);});}else button.disabled=true;wrapper.append(button);scenes.append(wrapper);}storyColumn.append(scenes);
    const disclosure=node('p','notice',this.#manifest.coverage.statement),exportButton=node('button','primary','CREATE VIDEO');exportButton.type='button';exportButton.addEventListener('click',()=>this.export());const evidenceButton=node('button','secondary','REVIEW EVIDENCE');evidenceButton.type='button';evidenceButton.addEventListener('click',()=>this.#onOpenEvidence?.(this.#manifest));const actions=node('div','trickster-actions');actions.append(evidenceButton,exportButton);const plan=chooseExportPlan(detectExportCapabilities(),{aspectRatio:this.#manifest.output.aspectRatio}),planText=node('small','trickster-export-plan',plan.mode==='on-device-webcodecs'?`Phone-ready ${plan.width}×${plan.height} ${plan.fps}fps MP4/WebM export`:'This device will use the safe rendering fallback.');layout.append(preview,storyColumn);this.#root.append(layout,disclosure,planText,actions);}
  async export(){if(!this.#manifest||!this.#timeline)throw new Error('story_not_ready');this.#status.textContent='PREPARING VIDEO';try{const events=replayEvents(this.#bundle),candles=replayCandles(this.#bundle);const result=await this.#onExport?.({manifest:this.#manifest,timeline:this.#timeline,storyDirection:this.#direction?structuredClone(this.#direction):null,sceneRuntime:structuredClone(this.#sceneRuntime||[]),renderPlan:structuredClone(this.#renderPlan||[]),replayEvents:structuredClone(events),candles:structuredClone(candles),marketContext:this.#bundle?.marketContext?structuredClone(this.#bundle.marketContext):null,priceSelection:this.#bundle?.priceSelection?structuredClone(this.#bundle.priceSelection):null,focus:resolveEventStoryFocus(this.#bundle),plan:chooseExportPlan(detectExportCapabilities(),{aspectRatio:this.#manifest.output.aspectRatio})});this.#status.textContent=result?.videoReady===true?'VIDEO READY':result?.validated===true?'EVIDENCE VALIDATED':'EXPORT AVAILABLE';return result;}catch(error){this.#status.textContent='RETRY AVAILABLE';throw error;}}
  destroy(){this.#player?.destroy();this.#player=null;this.#sceneRuntime=[];this.#renderPlan=[];this.#previewBody=null;this.#root.remove();}
}
