import test from 'node:test';
import assert from 'node:assert/strict';
import { renderWalletComparisonVideo } from './wallet-comparison-video-export.mjs';

const detail={manifest:{storyType:'wallet-comparison',output:{aspectRatio:'9:16'}},timeline:{scenes:[{id:'s1'}],totalFrames:10,fps:30},renderPlan:[{sceneId:'s1',mode:'comparison-replay',startFrame:0,endFrame:9,durationFrames:10,chainTimeFrom:1000,chainTimeTo:2000}],replayEvents:[{id:'a',wallet:'A',timestamp:1000,side:'buy'}],candles:[],comparison:{walletA:{wallet:'A'},walletB:{wallet:'B'}},plan:{mode:'on-device-webcodecs'}};

test('renders wallet comparison with synthesized audio through the same clip encoder',async()=>{let encoded=null;const fakeAudio={sampleRate:48000,numberOfChannels:2};const result=await renderWalletComparisonVideo(detail,{mediaLoader:async()=>({}),negotiate:async()=>({extension:'mp4',videoCodec:'avc1',audioCodec:'aac'}),drawerFactory:()=>async()=>{},audioRenderer:async()=>fakeAudio,encode:async args=>{encoded=args;return{blob:{size:1},extension:'mp4',mimeType:'video/mp4',width:1080,height:1920,fps:30};}});assert.equal(result.videoReady,true);assert.equal(result.extension,'mp4');assert.equal(typeof encoded.drawFrame,'function');assert.equal(encoded.audioBuffer,fakeAudio);assert.equal(result.audio.embedded,true);assert.ok(result.audio.cueCount>=2);});
test('comparison exporter stays silent when audio codec is unavailable',async()=>{let encoded=null;const result=await renderWalletComparisonVideo(detail,{mediaLoader:async()=>({}),negotiate:async()=>({extension:'mp4',videoCodec:'avc1',audioCodec:null}),drawerFactory:()=>async()=>{},audioRenderer:async()=>{throw new Error('should not render audio');},encode:async args=>{encoded=args;return{blob:{size:1},extension:'mp4',mimeType:'video/mp4',width:1080,height:1920,fps:30};}});assert.equal(result.videoReady,true);assert.equal(encoded.audioBuffer,null);assert.equal(result.audio.embedded,false);});
test('comparison exporter fails closed when local rendering is unsupported',async()=>{const result=await renderWalletComparisonVideo({...detail,plan:{mode:'server-render-required'}});assert.equal(result.videoReady,false);assert.equal(result.renderRequired,'server');});
test('non comparison story never enters comparison renderer',async()=>{const result=await renderWalletComparisonVideo({...detail,manifest:{storyType:'transaction-replay',output:{aspectRatio:'9:16'}}});assert.equal(result.videoReady,false);assert.equal(result.reason,'wallet_comparison_render_plan_unavailable');});
