import test from 'node:test';
import assert from 'node:assert/strict';
import { createWalletComparisonFrameDrawer } from './wallet-comparison-frame-renderer.mjs';

function fakeContext(){const texts=[];return{canvas:{width:1080,height:1920},texts,save(){},restore(){},fillRect(){},beginPath(){},arc(){},stroke(){},fill(){},moveTo(){},lineTo(){},closePath(){},rect(){},roundRect(){},measureText(value){return{width:String(value).length*11};},fillText(value){texts.push(String(value));},set fillStyle(v){this._fillStyle=v;},set strokeStyle(v){this._strokeStyle=v;},set lineWidth(v){this._lineWidth=v;},set globalAlpha(v){this._globalAlpha=v;},set font(v){this._font=v;},set textAlign(v){this._textAlign=v;},set textBaseline(v){this._textBaseline=v;}};}
const manifest={coverage:{verifiedPercent:100,statement:'Verified comparison.'},evidence:[{id:'e1'}],claims:[{id:'c1',statement:'Wallet A had more observed trades.',kind:'calculated'}],scenes:[{id:'summary',type:'comparison-hook',claimIds:[]},{id:'replay',type:'synchronized-trade-replay',claimIds:[]},{id:'metrics',type:'calculated-differences',claimIds:['c1']}]};
const renderPlan=[{sceneId:'summary',type:'comparison-hook',mode:'comparison-summary',startFrame:0,endFrame:9,durationFrames:10,walletA:'A',walletB:'B',chainTimeFrom:null,chainTimeTo:null},{sceneId:'replay',type:'synchronized-trade-replay',mode:'comparison-replay',startFrame:10,endFrame:19,durationFrames:10,walletA:'A',walletB:'B',chainTimeFrom:1000,chainTimeTo:3000},{sceneId:'metrics',type:'calculated-differences',mode:'comparison-metrics',startFrame:20,endFrame:29,durationFrames:10,walletA:'A',walletB:'B',chainTimeFrom:null,chainTimeTo:null}];
const bundle={replay:{events:[{id:'a',wallet:'A',timestamp:1000,side:'buy'},{id:'b',wallet:'B',timestamp:2500,side:'sell'}],candles:[{timestamp:1000,close:1},{timestamp:2000,close:2},{timestamp:3000,close:1.5}]},comparison:{walletA:{wallet:'A',tradeCount:2,buys:2,sells:0,directionChanges:0},walletB:{wallet:'B',tradeCount:1,buys:0,sells:1,directionChanges:0},disclosure:'Observed replay window only.'}};

test('draws wallet identities and synchronized shared-market replay',async()=>{const ctx=fakeContext(),draw=createWalletComparisonFrameDrawer({bundle,manifest,renderPlan});await draw(ctx,19);assert.ok(ctx.texts.some(value=>value.includes('WALLET A')));assert.ok(ctx.texts.some(value=>value.includes('WALLET B')));assert.ok(ctx.texts.some(value=>value.includes('SHARED INDEXED PRICE SERIES')));});
test('draws evidence-backed calculated differences',async()=>{const ctx=fakeContext(),draw=createWalletComparisonFrameDrawer({bundle,manifest,renderPlan});await draw(ctx,25);assert.ok(ctx.texts.some(value=>value.includes('EVIDENCE-BACKED DIFFERENCES')));assert.ok(ctx.texts.some(value=>value.includes('Wallet A had more observed trades')));});
