const BUILD='particle-universe-z500-integrated-1';
const CACHE=`abullsapp-${BUILD}`;
const CORE=[
  './','./index.html','./flight.html','./share.html','./privacy.html','./terms.html','./favicon.svg','./manifest.webmanifest',
  './css/styles.css','./css/dusk-atelier.css','./css/product-shell-vnext.css','./css/universe.css','./css/field-shell.css','./css/trickster-studio.css','./css/trickster-simulation.css','./css/intelligence-workspace-vnext.css','./css/intelligence-event-inspector.css','./css/token-market-workspace.css','./css/market-sequence-discovery.css',
  './js/opening-sequence.js','./js/config.js','./js/main.js','./js/experience-entry.mjs','./js/market-context-player-bridge.mjs',
  './universe-flight.js','./universe-flight-data.js','./universe-what-if.js','./universe-warp.js','./universe-cinematics.js','./universe-movie.js','./universe-app.js','./universe-experience.js',
  './assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/icons/icon-maskable-192.png','./assets/icons/icon-maskable-512.png'
];
async function cacheOne(cache,path){try{const request=new Request(path,{cache:'reload'});const response=await fetch(request);if(response.ok&&response.type==='basic')await cache.put(request,response);}catch(_){}}
self.addEventListener('install',event=>event.waitUntil((async()=>{const cache=await caches.open(CACHE);await Promise.all(CORE.map(path=>cacheOne(cache,path)));await self.skipWaiting();})()));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
function isStaticAsset(url){return/\.(?:js|css|mjs|json|png|jpe?g|webp|svg|gif|avif|woff2?|ttf|mp3|m4a|wav|ogg|mp4|webm)$/i.test(url.pathname);}
async function staleWhileRevalidate(request){const cache=await caches.open(CACHE),cached=await cache.match(request,{ignoreSearch:false}),refresh=fetch(request).then(async response=>{if(response.ok&&response.type==='basic')await cache.put(request,response.clone());return response;}).catch(()=>null);return cached||await refresh||new Response('Offline and this resource has not been cached.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});}
async function networkFirst(request){const cache=await caches.open(CACHE);try{const response=await fetch(request,{cache:'no-store'});if(response.ok&&response.type==='basic')await cache.put(request,response.clone());return response;}catch(_){return await cache.match(request)||(request.mode==='navigate'?await cache.match('./index.html'):null)||new Response('Offline and this resource has not been cached.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});}}
self.addEventListener('fetch',event=>{const url=new URL(event.request.url);if(event.request.method!=='GET'||url.origin!==location.origin||url.pathname.includes('/api/')||event.request.headers.has('Authorization'))return;if(event.request.mode==='navigate'){event.respondWith(networkFirst(event.request));return;}event.respondWith(isStaticAsset(url)?staleWhileRevalidate(event.request):networkFirst(event.request));});