/* A Bulls App — Universe Flight v0.1
 * Client-only playable particle-field foundation. No Worker/API polling.
 * The blockchain/evidence graph can later feed setSector() without changing flight physics.
 */
(()=>{
  'use strict';
  const TAU=Math.PI*2, clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
  const state={running:false,canvas:null,ctx:null,w:0,h:0,dpr:1,last:0,ship:{x:0,y:0,vx:0,vy:0,a:-Math.PI/2,hp:100,boost:100},keys:new Set(),pointer:null,shots:[],particles:[],obstacles:[],destination:null,market:{volatility:.35,buyPressure:.5,volume:.4},sector:null,raf:0};
  const hash=s=>{let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0};
  const rng=seed=>()=>((seed=Math.imul(seed^seed>>>15,1|seed)+0x6D2B79F5|0)^seed>>>7)>>>0)/4294967296;
  function resize(){if(!state.canvas)return;const r=state.canvas.getBoundingClientRect();state.dpr=Math.min(2,devicePixelRatio||1);state.w=Math.max(1,r.width);state.h=Math.max(1,r.height);state.canvas.width=state.w*state.dpr;state.canvas.height=state.h*state.dpr;state.ctx.setTransform(state.dpr,0,0,state.dpr,0,0);}
  function makeSector(seed='solana'){const R=rng(hash(seed));state.particles=Array.from({length:180},(_,i)=>({x:(R()-.5)*2600,y:(R()-.5)*2600,r:1+R()*3,k:R(),id:`p-${i}`}));state.obstacles=Array.from({length:26},(_,i)=>({x:(R()-.5)*2200,y:(R()-.5)*2200,r:18+R()*45,hp:1+Math.floor(R()*3),id:`o-${i}`}));state.sector=seed;}
  function setDestination(input,type='auto'){const id=String(input||'').trim();if(!id)return null;const R=rng(hash(id));state.destination={id,type,x:(R()-.5)*1800,y:(R()-.5)*1800,label:id.length>18?`${id.slice(0,8)}…${id.slice(-6)}`:id};return state.destination;}
  function market(m={}){state.market.volatility=clamp(Number(m.volatility??state.market.volatility),0,1);state.market.buyPressure=clamp(Number(m.buyPressure??state.market.buyPressure),0,1);state.market.volume=clamp(Number(m.volume??state.market.volume),0,1);}
  function shoot(){if(!state.running)return;const s=state.ship,sp=720;state.shots.push({x:s.x+Math.cos(s.a)*24,y:s.y+Math.sin(s.a)*24,vx:Math.cos(s.a)*sp+s.vx,vy:Math.sin(s.a)*sp+s.vy,life:1.1});}
  function controls(dt){const s=state.ship,k=state.keys;let turn=(k.has('ArrowRight')||k.has('KeyD')?1:0)-(k.has('ArrowLeft')||k.has('KeyA')?1:0);s.a+=turn*2.8*dt;let thrust=(k.has('ArrowUp')||k.has('KeyW'))?1:0;if(state.pointer){const dx=state.pointer.x-state.w/2,dy=state.pointer.y-state.h/2;s.a=Math.atan2(dy,dx);thrust=state.pointer.thrust?1:thrust;}const boosting=(k.has('ShiftLeft')||k.has('ShiftRight'))&&s.boost>0;if(boosting)s.boost=Math.max(0,s.boost-30*dt);else s.boost=Math.min(100,s.boost+13*dt);const accel=330*(boosting?1.85:1);s.vx+=Math.cos(s.a)*accel*thrust*dt;s.vy+=Math.sin(s.a)*accel*thrust*dt;const drag=Math.pow(.18,dt);s.vx*=drag;s.vy*=drag;const max=boosting?650:390,mag=Math.hypot(s.vx,s.vy);if(mag>max){s.vx=s.vx/mag*max;s.vy=s.vy/mag*max}s.x+=s.vx*dt;s.y+=s.vy*dt;}
  function update(dt){controls(dt);for(const q of state.shots){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;}state.shots=state.shots.filter(q=>q.life>0);for(const q of state.shots)for(const o of state.obstacles){if(o.hp>0&&Math.hypot(q.x-o.x,q.y-o.y)<o.r+5){o.hp--;q.life=0;}}state.obstacles=state.obstacles.filter(o=>o.hp>0);}
  function world(x,y){return[x-state.ship.x+state.w/2,y-state.ship.y+state.h/2]}
  function draw(){const c=state.ctx,w=state.w,h=state.h,m=state.market;c.clearRect(0,0,w,h);c.fillStyle='#020608';c.fillRect(0,0,w,h);const density=.35+m.volume*.65;for(const p of state.particles){const [x,y]=world(p.x,p.y);if(x<-10||y<-10||x>w+10||y>h+10)continue;const buy=p.k<m.buyPressure;c.globalAlpha=(.2+p.k*.65)*density;c.fillStyle=buy?'#63ffc5':'#ff5f79';c.beginPath();c.arc(x,y,p.r*(1+m.volatility*.7),0,TAU);c.fill();}c.globalAlpha=1;for(const o of state.obstacles){const [x,y]=world(o.x,o.y);if(x<-80||y<-80||x>w+80||y>h+80)continue;c.strokeStyle='rgba(255,190,100,.65)';c.lineWidth=2;c.beginPath();c.arc(x,y,o.r,0,TAU);c.stroke();}if(state.destination){const [x,y]=world(state.destination.x,state.destination.y);c.strokeStyle='#fff';c.lineWidth=2;c.beginPath();c.arc(x,y,18+Math.sin(performance.now()/180)*5,0,TAU);c.stroke();c.fillStyle='#fff';c.font='12px system-ui';c.fillText(state.destination.label,x+25,y+4);}for(const q of state.shots){const [x,y]=world(q.x,q.y);c.fillStyle='#fff';c.beginPath();c.arc(x,y,3,0,TAU);c.fill();}c.save();c.translate(w/2,h/2);c.rotate(state.ship.a+Math.PI/2);c.fillStyle='#d8fff1';c.beginPath();c.moveTo(0,-22);c.lineTo(14,17);c.lineTo(0,10);c.lineTo(-14,17);c.closePath();c.fill();c.restore();drawRadar(c,w,h);}
  function drawRadar(c,w,h){const r=55,x=w-r-14,y=r+14;c.fillStyle='rgba(0,0,0,.58)';c.strokeStyle='rgba(130,255,220,.55)';c.beginPath();c.arc(x,y,r,0,TAU);c.fill();c.stroke();if(state.destination){const dx=state.destination.x-state.ship.x,dy=state.destination.y-state.ship.y,d=Math.max(1,Math.hypot(dx,dy)),rr=Math.min(r-7,d/12);c.fillStyle='#fff';c.beginPath();c.arc(x+dx/d*rr,y+dy/d*rr,4,0,TAU);c.fill();}c.fillStyle='rgba(130,255,220,.9)';c.beginPath();c.arc(x,y,3,0,TAU);c.fill();}
  function frame(t){if(!state.running)return;const dt=Math.min(.033,(t-state.last)/1000||0);state.last=t;update(dt);draw();state.raf=requestAnimationFrame(frame);}
  function mount(canvas){state.canvas=typeof canvas==='string'?document.querySelector(canvas):canvas;if(!state.canvas)throw new Error('UniverseFlight canvas missing');state.ctx=state.canvas.getContext('2d',{alpha:false});resize();makeSector('solana');addEventListener('resize',resize,{passive:true});addEventListener('keydown',e=>{state.keys.add(e.code);if(e.code==='Space'){e.preventDefault();shoot();}});addEventListener('keyup',e=>state.keys.delete(e.code));state.canvas.addEventListener('pointerdown',e=>{const r=state.canvas.getBoundingClientRect();state.pointer={x:e.clientX-r.left,y:e.clientY-r.top,thrust:true};});state.canvas.addEventListener('pointermove',e=>{if(!state.pointer)return;const r=state.canvas.getBoundingClientRect();state.pointer.x=e.clientX-r.left;state.pointer.y=e.clientY-r.top;});addEventListener('pointerup',()=>state.pointer=null);return api;}
  function start(){if(state.running)return;state.running=true;state.last=performance.now();state.raf=requestAnimationFrame(frame);}
  function stop(){state.running=false;cancelAnimationFrame(state.raf);}
  function setSector(data={}){if(data.seed)makeSector(data.seed);if(Array.isArray(data.particles))state.particles=data.particles.slice(0,600);if(Array.isArray(data.obstacles))state.obstacles=data.obstacles.slice(0,120);market(data.market||{});}
  const api={mount,start,stop,shoot,setDestination,setSector,setMarket:market,state};
  window.UniverseFlight=api;
})();
