/* A Bulls App — Universe Flight v0.5: playable market encounters */
(()=>{'use strict';
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),emit=(t,d={})=>dispatchEvent(new CustomEvent('universeflight:'+t,{detail:d}));
const state={running:false,canvas:null,ctx:null,w:0,h:0,last:0,ship:{x:0,y:0,vx:0,vy:0,a:-Math.PI/2,boost:100,shield:100},camera:{mode:'chase',x:0,y:0,zoom:1,shake:0,target:null,angle:0},keys:new Set(),pointer:null,shots:[],particles:[],destination:null,market:{volatility:.35,buyPressure:.5,volume:.4},selected:null,scanned:new Set(),route:[],arrived:false,timeline:[],clock:{enabled:false,playing:false,speed:1,time:0,min:0,max:0,index:0},bursts:[],game:{active:true,score:0,combo:1,kills:0,damage:0,mission:null,hazards:[],enemies:[],pickups:[],lastHit:0},raf:0};
const hash=s=>{let h=2166136261;for(const c of String(s||'')){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0},rng=seed=>()=>((seed=Math.imul(seed^seed>>>15,1|seed)+0x6D2B79F5|0)^seed>>>7)>>>0)/4294967296;
function resize(){const r=state.canvas.getBoundingClientRect();state.w=r.width;state.h=r.height;const d=Math.min(2,devicePixelRatio||1);state.canvas.width=r.width*d;state.canvas.height=r.height*d;state.ctx.setTransform(d,0,0,d,0,0)}
function resetGame(){state.game={...state.game,score:0,combo:1,kills:0,damage:0,mission:null,hazards:[],enemies:[],pickups:[],lastHit:0};state.ship.shield=100;emit('game-state',gameState())}
function makeSector(seed='solana'){const R=rng(hash(seed));state.particles=Array.from({length:180},(_,i)=>({x:(R()-.5)*2600,y:(R()-.5)*2600,r:1+R()*3,k:R(),id:`p-${i}`}));state.scanned.clear();state.timeline=[];resetClock();resetGame()}
function setDestination(v,type='auto'){const id=String(v||'').trim();if(!id)return;const R=rng(hash(id));state.destination={id,type,x:(R()-.5)*1800,y:(R()-.5)*1800,label:id.length>18?`${id.slice(0,8)}…${id.slice(-6)}`:id};state.route=Array.from({length:12},(_,i)=>({x:state.ship.x+(state.destination.x-state.ship.x)*(i+1)/12,y:state.ship.y+(state.destination.y-state.ship.y)*(i+1)/12}));state.arrived=false;startMission({kind:'reach-destination',target:id,label:'REACH DESTINATION'});return state.destination}
function market(m={}){for(const k of['volatility','buyPressure','volume'])state.market[k]=clamp(Number(m[k]??state.market[k]),0,1)}
function shoot(){const s=state.ship,sp=720;state.shots.push({x:s.x+Math.cos(s.a)*24,y:s.y+Math.sin(s.a)*24,vx:Math.cos(s.a)*sp+s.vx,vy:Math.sin(s.a)*sp+s.vy,life:1.1,power:1});emit('shot')}
function scan(p){if(!p)return;state.scanned.add(p.id);state.selected=p;emit('evidence',{...p,position:{x:p.x,y:p.y}});return p}
function nearest(max=170){let b=null,d=max;for(const p of visibleParticles())if(dist(state.ship,p)<d){b=p;d=dist(state.ship,p)}return b}
function visibleParticles(){if(!state.clock.enabled)return state.particles;return state.particles.filter(p=>!p.time||p.time<=state.clock.time)}
function resetClock(){state.clock={enabled:false,playing:false,speed:1,time:0,min:0,max:0,index:0}}
function setTimeline(rows=[]){state.timeline=[...rows].sort((a,b)=>a.time-b.time);if(!state.timeline.length){resetClock();return}const min=state.timeline[0].time,max=state.timeline.at(-1).time;state.clock={enabled:true,playing:false,speed:1,time:min,min,max,index:0};emit('time',{...state.clock})}
function replay(){if(state.clock.enabled){state.clock.playing=true;emit('time',{...state.clock})}}function pause(){state.clock.playing=false;emit('time',{...state.clock})}
function seek(value){if(!state.clock.enabled)return;state.clock.time=clamp(Number(value),state.clock.min,state.clock.max);state.clock.index=state.timeline.findIndex(e=>e.time>state.clock.time);if(state.clock.index<0)state.clock.index=state.timeline.length;state.bursts=[];state.game.hazards=[];state.game.enemies=[];emit('time',{...state.clock})}
function speed(v){state.clock.speed=[.25,.5,1,2,4,8,16].includes(Number(v))?Number(v):1;emit('time',{...state.clock})}
function trigger(e){state.bursts.push({x:e.x,y:e.y,side:e.side||'',life:1,max:1,magnitude:e.magnitude||.2});if(state.bursts.length>80)state.bursts.shift();spawnEncounter(e);emit('market-event',e)}
function tickTime(dt){const c=state.clock;if(!c.enabled||!c.playing)return;c.time=Math.min(c.max,c.time+dt*c.speed*Math.max(1,(c.max-c.min)/45));while(c.index<state.timeline.length&&state.timeline[c.index].time<=c.time)trigger(state.timeline[c.index++]);if(c.time>=c.max)c.playing=false;emit('time',{...c})}
function startMission(m={}){state.game.mission={kind:m.kind||'survive',target:m.target||null,label:m.label||'SURVIVE',progress:0,complete:false};emit('mission',{...state.game.mission})}
function spawnEncounter(e={}){if(!state.game.active)return;const mag=clamp(Number(e.magnitude)||.2,.05,1),R=rng(hash(`${e.id||Date.now()}:${e.time||0}`)),count=1+Math.floor(mag*4),side=e.side||'';for(let i=0;i<count;i++){const a=R()*TAU,d=120+R()*260,x=(e.x??state.ship.x)+Math.cos(a)*d,y=(e.y??state.ship.y)+Math.sin(a)*d;if(mag>.62){state.game.enemies.push({id:`raider:${e.id||Date.now()}:${i}`,x,y,vx:0,vy:0,r:12+mag*7,hp:1+Math.ceil(mag*3),maxHp:1+Math.ceil(mag*3),side,aggression:.35+mag*.65,reward:100+Math.round(mag*400),simulated:!!e.simulated})}else{state.game.hazards.push({id:`hazard:${e.id||Date.now()}:${i}`,x,y,r:16+mag*26,life:8+mag*7,damage:8+mag*22,side,spin:R()*TAU,simulated:!!e.simulated})}}if(mag>.78)state.game.pickups.push({id:`pickup:${e.id||Date.now()}`,x:e.x??state.ship.x,y:e.y??state.ship.y,r:9,kind:'shield',value:18+Math.round(mag*25),life:12});emit('encounter',{side,magnitude:mag,enemies:state.game.enemies.length,hazards:state.game.hazards.length})}
function controls(dt){const s=state.ship,k=state.keys;let turn=(k.has('ArrowRight')||k.has('KeyD')?1:0)-(k.has('ArrowLeft')||k.has('KeyA')?1:0);s.a+=turn*2.8*dt;let thrust=k.has('ArrowUp')||k.has('KeyW')?1:0;if(state.pointer){s.a=Math.atan2(state.pointer.y-state.h/2,state.pointer.x-state.w/2);thrust=state.pointer.thrust?1:thrust}const boost=(k.has('ShiftLeft')||k.has('ShiftRight'))&&s.boost>0;s.boost=clamp(s.boost+(boost?-30:13)*dt,0,100);const a=330*(boost?1.85:1);s.vx+=Math.cos(s.a)*a*thrust*dt;s.vy+=Math.sin(s.a)*a*thrust*dt;const drag=Math.pow(.18,dt);s.vx*=drag;s.vy*=drag;const max=boost?650:390,m=Math.hypot(s.vx,s.vy);if(m>max){s.vx=s.vx/m*max;s.vy=s.vy/m*max}s.x+=s.vx*dt;s.y+=s.vy*dt}
function camera(dt){const c=state.camera,s=state.ship;let tx=s.x,ty=s.y,z=1;if(c.mode==='wide')z=.72;else if(c.mode==='impact-zoom'){z=1.55;if(c.target){const e=state.timeline.find(x=>x.id===c.target);if(e){tx=e.x;ty=e.y}}}else if(c.mode==='orbit-flyby'){c.angle+=dt*.8;tx=s.x+Math.cos(c.angle)*95;ty=s.y+Math.sin(c.angle)*95;z=1.18}else if(c.mode==='pullback')z=.55;c.x+=(tx-c.x)*Math.min(1,dt*4.5);c.y+=(ty-c.y)*Math.min(1,dt*4.5);c.zoom+=(z-c.zoom)*Math.min(1,dt*3.8);c.shake=Math.max(0,c.shake-dt*2.5)}
function damageShip(amount,source){const now=performance.now();if(now-state.game.lastHit<350)return;state.game.lastHit=now;state.ship.shield=clamp(state.ship.shield-amount,0,100);state.game.damage+=amount;state.game.combo=1;state.camera.shake=Math.max(state.camera.shake,.7);emit('ship-hit',{shield:state.ship.shield,amount,source});if(state.ship.shield<=0){emit('ship-disabled',{score:state.game.score});state.ship.shield=100;state.ship.vx=state.ship.vy=0;state.ship.x-=Math.cos(state.ship.a)*120;state.ship.y-=Math.sin(state.ship.a)*120}}
function updateGameplay(dt){const g=state.game,s=state.ship;for(const h of g.hazards){h.life-=dt;h.spin+=dt;if(dist(s,h)<h.r+11)damageShip(h.damage,'market-hazard')}g.hazards=g.hazards.filter(h=>h.life>0);for(const e of g.enemies){const dx=s.x-e.x,dy=s.y-e.y,d=Math.max(1,Math.hypot(dx,dy));e.vx+=dx/d*e.aggression*95*dt;e.vy+=dy/d*e.aggression*95*dt;e.vx*=.985;e.vy*=.985;e.x+=e.vx*dt;e.y+=e.vy*dt;if(d<e.r+13)damageShip(10+e.aggression*12,'market-raider')}for(const p of g.pickups){p.life-=dt;if(dist(s,p)<p.r+14){if(p.kind==='shield')s.shield=clamp(s.shield+p.value,0,100);p.life=0;state.game.score+=50;emit('pickup',{kind:p.kind,value:p.value,shield:s.shield})}}g.pickups=g.pickups.filter(p=>p.life>0);for(const q of state.shots){for(const e of g.enemies){if(q.life<=0||e.hp<=0)continue;if(Math.hypot(q.x-e.x,q.y-e.y)<e.r+5){q.life=0;e.hp-=q.power;if(e.hp<=0){g.kills++;g.combo=Math.min(8,g.combo+.25);g.score+=Math.round(e.reward*g.combo);state.bursts.push({x:e.x,y:e.y,side:e.side,life:1,max:1,magnitude:.8});emit('enemy-destroyed',{id:e.id,score:g.score,combo:g.combo,simulated:e.simulated})}}}g.enemies=g.enemies.filter(e=>e.hp>0);if(g.mission?.kind==='reach-destination'&&state.arrived&&!g.mission.complete){g.mission.complete=true;g.mission.progress=1;g.score+=500;emit('mission-complete',{...g.mission,score:g.score})}emit('game-state',gameState())}
function gameState(){return{score:state.game.score,combo:state.game.combo,kills:state.game.kills,shield:state.ship.shield,boost:state.ship.boost,mission:state.game.mission,enemies:state.game.enemies.length,hazards:state.game.hazards.length}}
function update(dt){controls(dt);tickTime(dt);camera(dt);for(const q of state.shots){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;for(const p of visibleParticles())if(q.life>0&&Math.hypot(q.x-p.x,q.y-p.y)<p.r+8){q.life=0;scan(p)}}updateGameplay(dt);state.shots=state.shots.filter(q=>q.life>0);for(const b of state.bursts)b.life-=dt;state.bursts=state.bursts.filter(b=>b.life>0);if(state.destination&&!state.arrived&&dist(state.ship,state.destination)<85){state.arrived=true;emit('arrival',{destination:state.destination,nearby:nearest(260)})}}
function world(x,y){const c=state.camera,j=c.shake?(Math.random()-.5)*c.shake*16:0,k=c.shake?(Math.random()-.5)*c.shake*16:0;return[(x-c.x)*c.zoom+state.w/2+j,(y-c.y)*c.zoom+state.h/2+k]}
function drawGameplay(c){for(const h of state.game.hazards){const[x,y]=world(h.x,h.y);if(x<-70||y<-70||x>state.w+70||y>state.h+70)continue;c.save();c.translate(x,y);c.rotate(h.spin);c.strokeStyle=h.side==='buy'?'rgba(80,255,185,.75)':h.side==='sell'?'rgba(255,83,111,.78)':'rgba(180,150,255,.75)';c.lineWidth=2;c.beginPath();for(let i=0;i<8;i++){const a=i/8*TAU,r=h.r*(i%2?.55:1),px=Math.cos(a)*r,py=Math.sin(a)*r;i?c.lineTo(px,py):c.moveTo(px,py)}c.closePath();c.stroke();c.restore()}for(const e of state.game.enemies){const[x,y]=world(e.x,e.y);if(x<-50||y<-50||x>state.w+50||y>state.h+50)continue;c.save();c.translate(x,y);const a=Math.atan2(state.ship.y-e.y,state.ship.x-e.x);c.rotate(a+Math.PI/2);c.fillStyle=e.simulated?'#ffd36a':e.side==='sell'?'#ff536f':'#8d79ff';c.beginPath();c.moveTo(0,-14);c.lineTo(11,12);c.lineTo(0,7);c.lineTo(-11,12);c.closePath();c.fill();c.strokeStyle='#fff8';c.strokeRect(-13,18,26,3);c.fillStyle='#63ffc5';c.fillRect(-13,18,26*(e.hp/e.maxHp),3);c.restore()}for(const p of state.game.pickups){const[x,y]=world(p.x,p.y);c.strokeStyle='#63ffc5';c.lineWidth=2;c.beginPath();c.arc(x,y,p.r+Math.sin(performance.now()/180)*3,0,TAU);c.stroke();c.fillStyle='#d8fff1';c.fillRect(x-2,y-7,4,14);c.fillRect(x-7,y-2,14,4)}}
function draw(){const c=state.ctx,w=state.w,h=state.h,m=state.market;c.fillStyle='#020608';c.fillRect(0,0,w,h);if(state.destination&&!state.arrived){c.setLineDash([5,10]);c.strokeStyle='#63ffc530';c.beginPath();for(let j=0;j<state.route.length;j++){const[x,y]=world(state.route[j].x,state.route[j].y);j?c.lineTo(x,y):c.moveTo(...world(state.ship.x,state.ship.y))}c.stroke();c.setLineDash([])}for(const p of visibleParticles()){const[x,y]=world(p.x,p.y);if(x<0||y<0||x>w||y>h)continue;const buy=p.side==='buy'||(!p.side&&p.k<m.buyPressure);c.globalAlpha=state.scanned.has(p.id)?1:.25+p.k*.6;c.fillStyle=buy?'#63ffc5':'#ff536f';c.beginPath();c.arc(x,y,p.r*(1+m.volatility*.7)*state.camera.zoom+(state.selected?.id===p.id?5:0),0,TAU);c.fill()}c.globalAlpha=1;for(const b of state.bursts){const[x,y]=world(b.x,b.y),progress=1-b.life/b.max,r=(10+progress*(35+b.magnitude*80))*state.camera.zoom;c.strokeStyle=b.side==='buy'?`rgba(80,255,185,${b.life})`:b.side==='sell'?`rgba(255,55,90,${b.life})`:`rgba(180,150,255,${b.life})`;c.lineWidth=2+4*b.magnitude;c.beginPath();c.arc(x,y,r,0,TAU);c.stroke()}drawGameplay(c);if(state.destination){const[x,y]=world(state.destination.x,state.destination.y);c.strokeStyle=state.arrived?'#63ffc5':'#fff';c.beginPath();c.arc(x,y,22*state.camera.zoom,0,TAU);c.stroke()}for(const q of state.shots){const[x,y]=world(q.x,q.y);c.fillStyle='#fff';c.beginPath();c.arc(x,y,3,0,TAU);c.fill()}const[sx,sy]=world(state.ship.x,state.ship.y);c.save();c.translate(sx,sy);c.rotate(state.ship.a+Math.PI/2);c.scale(state.camera.zoom,state.camera.zoom);c.fillStyle='#d8fff1';c.beginPath();c.moveTo(0,-22);c.lineTo(14,17);c.lineTo(0,10);c.lineTo(-14,17);c.closePath();c.fill();c.restore()}
function frame(t){if(!state.running)return;const dt=Math.min(.033,(t-state.last)/1000||0);state.last=t;update(dt);draw();state.raf=requestAnimationFrame(frame)}
function mount(canvas){state.canvas=typeof canvas==='string'?document.querySelector(canvas):canvas;state.ctx=state.canvas.getContext('2d',{alpha:false});state.camera.x=state.ship.x;state.camera.y=state.ship.y;resize();makeSector();addEventListener('resize',resize);addEventListener('universeflight:camera',e=>{const d=e.detail||{};state.camera.mode=d.mode||'chase';state.camera.target=d.target||null;state.camera.shake=Math.max(state.camera.shake,Number(d.shake)||0)});addEventListener('universeflight:fx',e=>state.camera.shake=Math.max(state.camera.shake,Number(e.detail?.magnitude)||.2));addEventListener('keydown',e=>{state.keys.add(e.code);if(e.code==='Space'){e.preventDefault();shoot()}if(e.code==='KeyE')scan(nearest());if(e.code==='KeyP')state.clock.playing?pause():replay();if(e.code==='BracketLeft')seek(state.clock.time-(state.clock.max-state.clock.min)*.05);if(e.code==='BracketRight')seek(state.clock.time+(state.clock.max-state.clock.min)*.05)});addEventListener('keyup',e=>state.keys.delete(e.code));let down;state.canvas.addEventListener('pointerdown',e=>{const r=state.canvas.getBoundingClientRect();down={x:e.clientX,y:e.clientY,t:performance.now()};state.pointer={x:e.clientX-r.left,y:e.clientY-r.top,thrust:true}});addEventListener('pointerup',e=>{if(down&&performance.now()-down.t<220){const r=state.canvas.getBoundingClientRect(),sx=e.clientX-r.left,sy=e.clientY-r.top;let b=null,bd=30;for(const p of visibleParticles()){const[x,y]=world(p.x,p.y),d=Math.hypot(x-sx,y-sy);if(d<bd){b=p;bd=d}}scan(b)}down=null;state.pointer=null});return api}
function start(){if(state.running)return;state.running=true;state.last=performance.now();state.raf=requestAnimationFrame(frame)}
function setSector(d={}){if(d.seed)makeSector(d.seed);if(Array.isArray(d.particles))state.particles=d.particles.slice(0,600);market(d.market||{});setTimeline(d.timeline||[]);emit('sector',{particleCount:state.particles.length,coverage:d.coverage||null,timelineCount:state.timeline.length})}
const api={mount,start,shoot,scan,setDestination,setSector,setMarket:market,replay,pause,seek,setSpeed:speed,setTimeline,spawnEncounter,startMission,gameState,resetGame,state};window.UniverseFlight=api})();