import type { FieldParticle, UniverseSnapshot } from "@/lib/field/types";
import type { UniverseDataStatus } from "./contracts";
import { fetchIntelligence } from "../intelligence-origin.ts";
export const PONS_GALAXY_PATH="/api/intelligence/pons/galaxy";
export const PONS_GALAXY_URL=`https://abullsapp.com${PONS_GALAXY_PATH}`;

export type PonsLaunch={rank:number;token:string;factory:string;factoryVersion:"v1"|"v2";curve:string|null;deployer:string;dexFactory:string|null;pairToken:string;pool:string|null;transactionHash:string;blockNumber:number;blockHash:string;blockTime:number|null;finality:string;state:string;market?:Record<string,unknown>};
type PonsGalaxyBody={ok?:boolean;error?:string;data?:{generatedAt?:number;coverage?:{complete?:boolean;statement?:string};launches?:PonsLaunch[]}};
export type PonsGalaxyDelivery={snapshot:UniverseSnapshot|null;status:UniverseDataStatus};
function clamp01(value:number){return Math.min(1,Math.max(0,Number.isFinite(value)?value:0));}
function hashUnit(input:string){let hash=2166136261;for(let index=0;index<input.length;index++){hash^=input.charCodeAt(index);hash=Math.imul(hash,16777619);}return(hash>>>0)/4294967295;}
function marketNumber(market:Record<string,unknown>|undefined,key:string){const value=market?.[key];if(value==null||value==="")return null;const numeric=typeof value==="number"?value:Number(value);return Number.isFinite(numeric)&&numeric>=0?numeric:null;}
export function ponsLaunchToParticle(launch:PonsLaunch):FieldParticle{const angle=hashUnit(launch.token)*Math.PI*2,radius=24+hashUnit(`${launch.token}:radius`)*62,vertical=(hashUnit(`${launch.token}:height`)-.5)*18,marketCapUsd=marketNumber(launch.market,"marketCapUsd"),fdvUsd=marketNumber(launch.market,"fdvUsd"),priceUsd=marketNumber(launch.market,"priceUsd"),volumeH24=marketNumber(launch.market,"volumeH24"),holderCount=marketNumber(launch.market,"holderCount"),marketObservedAt=marketNumber(launch.market,"observedAt"),symbol=typeof launch.market?.symbol==="string"?launch.market.symbol:null,name=typeof launch.market?.name==="string"?launch.market.name:null,volumeBand=volumeH24!==null?Math.log10(1+volumeH24)/12:0,magnitudeBand=clamp01(.42+volumeBand*.42+(marketCapUsd!==null?Math.log10(1+marketCapUsd)/40:0)),observedAt=launch.blockTime??Date.now();return{id:`planet:pons:${launch.token.toLowerCase()}`,eventId:`pons:${launch.transactionHash.toLowerCase()}`,kind:"token",cosmicKind:"planet",originGalaxyId:"pons",verificationState:launch.finality||"observed",observedAt,category:"program",magnitudeBand,position:[Math.cos(angle)*radius,vertical,Math.sin(angle)*radius],source:"verified-pons-factory-event",metadata:{chainId:4663,rank:launch.rank,mint:launch.token,factory:launch.factory,factoryVersion:launch.factoryVersion,curve:launch.curve,deployer:launch.deployer,dexFactory:launch.dexFactory,pairToken:launch.pairToken,pool:launch.pool,transactionHash:launch.transactionHash,blockNumber:launch.blockNumber,blockHash:launch.blockHash,state:launch.state,symbol,name,priceUsd,marketCapUsd,fdvUsd,volumeH24,holderCount,marketObservedAt,originVerified:true,systemRole:"ponsfamily-trending-planet"}};}
export function snapshotFromPonsLaunches(launches:readonly PonsLaunch[],input:{generatedAt?:number;disclosure?:string}={}):UniverseSnapshot{const particles=launches.map(ponsLaunchToParticle),observed=particles.map(p=>p.observedAt).filter(Number.isFinite),now=input.generatedAt??Date.now();return{galaxyId:"pons",windowStart:observed.length?Math.min(...observed):now,windowEnd:observed.length?Math.max(now,...observed):now,observedEventCount:particles.length,samplingPolicy:"PonsFamily trending · verified PONS origin · market cap > $75,000 · holders > 750 · fresh 24h volume descending · maximum 50",coverageStatement:input.disclosure??"PonsFamily membership requires verified PONS origin plus fresh market-cap, holder-count, and 24-hour-volume observations. Missing metrics do not qualify.",sources:["verified PONS V1/V2 factory evidence","PonsFamily Intelligence market cache","PonsFamily Intelligence holder cache"],particles};}
export async function loadPonsGalaxyDelivery():Promise<PonsGalaxyDelivery>{try{const response=await fetchIntelligence(`${PONS_GALAXY_PATH}?limit=50`,{headers:{accept:"application/json"},cache:"no-store"}),contentType=response.headers.get("content-type")??"";if(!contentType.includes("application/json"))return degraded("PonsFamily endpoint returned a non-JSON response. No direct provider fallback was attempted.");const body=await response.json() as PonsGalaxyBody;if(!response.ok||!body.ok||!body.data)return degraded(response.status===404||body.error==="feature_disabled"?"PonsFamily rankings are disabled.":"PonsFamily trending index is unavailable. No unverified token feed was substituted.");const launches=body.data.launches??[];if(!launches.length)return{snapshot:null,status:{store:"d1",coverage:"empty",circuitBreaker:null,disclosure:body.data.coverage?.statement??"No verified PONS-origin tokens currently meet the PonsFamily trending thresholds."}};return{snapshot:snapshotFromPonsLaunches(launches,{generatedAt:body.data.generatedAt,disclosure:body.data.coverage?.statement}),status:{store:"d1",coverage:"fresh",circuitBreaker:null,disclosure:body.data.coverage?.statement??"PonsFamily trending coverage."}};}catch{return degraded("PonsFamily index is unreachable. No browser-side market or RPC fallback was attempted.");}}
function degraded(disclosure:string):PonsGalaxyDelivery{return{snapshot:null,status:{store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure}};}
