import { ParticleFieldRenderer } from "./particle-field";
import { LivingAlienOrganism } from "./query-organism";
import { createGalaxySnapshot } from "./synthetic-universe";
import { deviceBudget } from "./hash";
import type { CameraState, Coverage, FieldMode, FieldParticle, FieldSection, FocusedParticle, GalaxyDefinition, GalaxyId, EvidenceRecord, IntelligenceResult, OrganismState, ReplayState, UniverseSnapshot } from "./types";
import { DEFAULT_GALAXY_ID, GALAXIES, getGalaxy, isPopulatedGalaxy } from "./galaxies";
import { speakText, unlockSpeech, type VoiceHandle } from "./voice";
import { resolvePublicIdentifier } from "@/lib/intelligence";
import { getIndexedGalaxySnapshot } from "@/lib/universe-data/service";
import { getTokenSystem } from "@/lib/universe-data/token-system-client";
import { getFomoGalaxy, getFomoTraderSystem } from "@/lib/universe-data/fomo-client";
import { getAfterbellGalaxy } from "@/lib/universe-data/afterbell-client";
import { getAfterbellTraders } from "@/lib/universe-data/afterbell-traders-client";
import { getWalletResearchSystem } from "@/lib/universe-data/research-index-client";
import { createResearchThreadContext } from "../research-thread";
import { loadResearchThread, saveResearchThread } from "@/lib/research-thread-store";
import { shouldReplacePrototypeField, sparseHydrateDisclosure, visibilityFloor } from "./hydrate-gate";
import type { UniverseDataStatus } from "@/lib/universe-data/contracts";
import { createReplayState, evidenceForParticle, stepReplayCursor, visibleReplayCount } from "./replay";
import { composeVolumeSky, countLivePlanets, countLiveStars, particleMint } from "./volume-sky";
import { isWatched, loadWatchlist, saveWatchlist, toggleWatchItem, tokenWatchMints, type WatchItem, type WatchSubjectKind } from "./watchlist";
import { speakObservedParticle } from "./observed-speech";
import { buildTokenSystemSnapshot } from "./token-system";
import { buildFomoGalaxySnapshot } from "./fomo-galaxy";
import { buildAfterbellGalaxySnapshot } from "./afterbell-galaxy";
import { buildAfterbellTraderSystemSnapshot } from "./afterbell-trader-system";
import { buildFomoTraderSystemSnapshot } from "./fomo-trader-system";
import { buildWalletResearchSystemSnapshot } from "./wallet-research-system";
import { buildWatchlistSnapshot } from "./watchlist-sky";
import { FIELD_RESEARCH_MODE_EVENT, researchModeFromEvent, tradeReplaySelection } from "./trade-research-navigation";
import { roomFor, type FieldRoom } from "./galaxies";
import { ASK_MISS_LINE, resolveLocal, type AskIndex } from "./ask-local";
import { afterbellTraderDetail, fomoTraderDetail } from "./trader-sheet";
import { buildAfterbellPlanetSystemSnapshot } from "./afterbell-trader-system";
import { removeWatchItem } from "./watchlist";
import { XSTOCK_REGISTRY, type AfterbellGalaxyData } from "@/lib/universe-data/afterbell-client";
import type { AfterbellTraderResponse } from "@/lib/universe-data/afterbell-traders-client";
import type { FomoGalaxyResponse } from "@/lib/universe-data/fomo-client";

const metaText=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():null;

export type FieldOSListener=(event:{mode:FieldMode;queryActive:boolean;organismState:OrganismState;result:IntelligenceResult|null;speaking:boolean;muted:boolean;focus:FocusedParticle|null;galaxy:GalaxyDefinition;galaxies:readonly GalaxyDefinition[];replay:ReplayState;evidence:EvidenceRecord|null;dataStatus:UniverseDataStatus;askPrefill:string;askNotice:string;watchlist:readonly WatchItem[];livePlanetCount:number;fieldSection:FieldSection;})=>void;

export class FieldOS {
  host:HTMLElement;field:ParticleFieldRenderer;organism:LivingAlienOrganism|null=null;mode:FieldMode="explore";queryActive=false;organismState:OrganismState="idle";result:IntelligenceResult|null=null;muted=false;volume=.92;focus:FocusedParticle|null=null;galaxy:GalaxyDefinition=getGalaxy(DEFAULT_GALAXY_ID);replay:ReplayState;evidence:EvidenceRecord|null=null;dataStatus:UniverseDataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:"Checking indexed universe coverage."};askPrefill="";askNotice="";watchlist:WatchItem[]=[];livePlanetCount=0;fieldSection:FieldSection={kind:"galaxy",label:"Field",count:0};
  #cameraSnapshot:CameraState|null=null;#voice:VoiceHandle|null=null;#listener:FieldOSListener|null=null;#querySeq=0;#snapshotSeq=0;#prototype=createGalaxySnapshot(getGalaxy(DEFAULT_GALAXY_ID),deviceBudget().field);#live:UniverseSnapshot|null=null;#baseSky:UniverseSnapshot|null=null;#hydrateTimer=0;#lastSpokenId:string|null=null;#focusResolveSeq=0;#pendingFocusMint:string|null=null;#destroyed=false;#hydration:Promise<void>=Promise.resolve();#fomoData:FomoGalaxyResponse|null=null;#afterbellMarkets:AfterbellGalaxyData|null=null;#afterbellTraders:AfterbellTraderResponse|null=null;#researchModeListener=(event:Event)=>{const mode=researchModeFromEvent(event);if(mode)this.setMode(mode);};

  constructor(host:HTMLElement,listener:FieldOSListener){this.host=host;this.#listener=listener;globalThis.addEventListener(FIELD_RESEARCH_MODE_EVENT,this.#researchModeListener);this.watchlist=loadWatchlist();const budget=deviceBudget();this.#prototype=createGalaxySnapshot(this.galaxy,budget.field);const initial=composeVolumeSky({prototype:this.#prototype,live:null,watchlist:this.watchlist,wallpaperLimit:budget.field});this.#baseSky=initial;this.field=new ParticleFieldRenderer(host,initial);this.field.setWatchlistMints(tokenWatchMints(this.watchlist));this.replay=createReplayState(initial);this.livePlanetCount=countLivePlanets(initial);this.fieldSection={kind:"galaxy",label:this.galaxy.name,count:this.livePlanetCount};this.field.onFocus=particle=>this.#onFocus(particle);this.field.onReplayTick=(cursor,playing)=>{this.replay={...this.replay,cursor,status:playing?"playing":cursor>=1?"complete":"paused",visibleEventCount:visibleReplayCount(this.field.snapshot,cursor)};this.#emit();};try{this.muted=globalThis.localStorage?.getItem("abulls-mute")==="1";}catch{this.muted=false;}this.#emit();this.#hydration=this.#hydrateGalaxy(this.galaxy.id);this.#hydrateTimer=globalThis.setInterval(()=>{if(!this.queryActive&&this.fieldSection.kind==="galaxy"&&this.galaxy.id!=="galaxy-zero"&&document.visibilityState!=="hidden")void this.#hydrateGalaxy(this.galaxy.id);},60_000) as unknown as number;}

  #onFocus(particle:FieldParticle|null){
    this.focus=particle?{id:particle.id,kind:particle.kind,cosmicKind:particle.cosmicKind,originGalaxyId:particle.originGalaxyId,category:particle.category,observedAt:particle.observedAt,verificationState:particle.verificationState,magnitudeBand:particle.magnitudeBand,eventId:particle.eventId,source:particle.source,slot:particle.slot,metadata:particle.metadata}:null;
    this.evidence=particle?evidenceForParticle(this.field.snapshot,particle):null;
    if(particle)this.askNotice="";
    const mint=particleMint(particle),wallet=particle?.cosmicKind==="star"&&typeof particle.metadata?.wallet==="string"?particle.metadata.wallet.trim():"";
    if(particle&&(mint||wallet))this.askPrefill=mint||wallet;
    this.#emit();
    if(!particle){this.#focusResolveSeq++;this.#lastSpokenId=null;return;}
    const target=typeof particle.metadata?.targetGalaxyId==="string"?particle.metadata.targetGalaxyId as GalaxyId:null;
    if(target){this.field.clearFocus(true);this.setGalaxy(target);return;}
    if(this.queryActive||particle.id===this.#lastSpokenId)return;
    this.#lastSpokenId=particle.id;unlockSpeech();

    if(this.galaxy.id==="afterbell"&&this.fieldSection.kind==="galaxy"&&particle.cosmicKind==="star"&&particle.metadata?.afterbellTrader===true&&wallet){void this.enterAfterbellTraderSystem(particle);return;}
    if(particle.cosmicKind==="star"&&particle.metadata?.fomoTrader===true&&this.galaxy.id==="fomo"&&this.fieldSection.kind==="galaxy"){void this.enterFomoTraderSystem(particle);return;}

    if(this.fieldSection.kind==="watchlist"){const item=this.#watchItemFor(particle);if(item){void this.openWatchItem(item);return;}}
    if(this.fieldSection.kind==="afterbell-system"&&particle.cosmicKind==="star"&&particle.metadata?.afterbellTrader===true&&wallet){void this.enterAfterbellTraderSystem(particle);return;}
    if(this.fieldSection.kind==="trader-system"&&particle.cosmicKind==="planet"&&mint){this.#selectTraderPlanet(particle,mint);return;}
    if(this.fieldSection.kind==="trader-system"&&particle.cosmicKind==="comet"&&mint){this.#openPrint(particle,"replay");return;}
    if(this.fieldSection.kind==="wallet-system"&&particle.cosmicKind==="planet"&&mint){const chainKey=typeof particle.metadata?.chainKey==="string"?particle.metadata.chainKey:"solana",prior=loadResearchThread();saveResearchThread(createResearchThreadContext({galaxyId:this.galaxy.id,chainKey,wallet:this.fieldSection.wallet,mint,replaySpeed:prior.replaySpeed}));this.askPrefill=mint;void this.enterTokenSystem(particle);return;}
    if(particle.cosmicKind==="planet"&&mint){if(this.fieldSection.kind!=="token-system"||this.fieldSection.mint!==mint){void this.enterTokenSystem(particle);return;}void this.#narrateResolvedMarket(particle.id,mint);return;}
    this.narrateObserved(speakObservedParticle(particle,this.field.snapshot));
  }

  #emit(){if(!this.#destroyed)this.#listener?.({mode:this.mode,queryActive:this.queryActive,organismState:this.organismState,result:this.result,speaking:Boolean(this.#voice?.speaking),muted:this.muted,focus:this.focus,galaxy:this.galaxy,galaxies:GALAXIES,replay:this.replay,evidence:this.evidence,dataStatus:this.dataStatus,askPrefill:this.askPrefill,askNotice:this.askNotice,watchlist:this.watchlist,livePlanetCount:this.livePlanetCount,fieldSection:this.fieldSection});}
  #applySky(){const composed=composeVolumeSky({prototype:this.#prototype,live:this.#live,watchlist:this.watchlist,wallpaperLimit:deviceBudget().field});this.#baseSky=composed;this.livePlanetCount=countLivePlanets(composed);const galaxyObjectCount=(this.galaxy.id==="fomo"||this.galaxy.id==="afterbell")?countLiveStars(composed):this.livePlanetCount;if(this.fieldSection.kind==="galaxy"){this.field.setSnapshot(composed);this.fieldSection={kind:"galaxy",label:this.galaxy.name,count:galaxyObjectCount};this.replay=createReplayState(composed);const want=particleMint(this.focus)??this.#pendingFocusMint;if(want){this.field.focusByMint(want);if(this.field.focused)this.#pendingFocusMint=null;}}this.field.setWatchlistMints(tokenWatchMints(this.watchlist));}
  focusMint(mint:string){const trimmed=mint.trim();if(!trimmed)return;this.#pendingFocusMint=trimmed;this.askPrefill=trimmed;if(this.queryActive){void this.returnToField().then(()=>this.focusMint(trimmed));return;}if(this.fieldSection.kind!=="galaxy")this.exitSpecialSection(false);this.mode="explore";this.field.focusByMint(trimmed);this.#emit();}
  #focusedWatchSubject():{subjectKind:WatchSubjectKind;subjectId:string}|null{if(!this.focus)return null;if(this.focus.cosmicKind==="planet"||this.focus.cosmicKind==="black-hole"||this.focus.cosmicKind==="supernova"){const mint=particleMint(this.focus);return mint?{subjectKind:"token",subjectId:mint}:null;}if(this.focus.cosmicKind==="star"&&typeof this.focus.metadata?.wallet==="string"&&this.focus.metadata.wallet.trim())return{subjectKind:"wallet",subjectId:this.focus.metadata.wallet.trim()};return null;}
  toggleWatch(){const subject=this.#focusedWatchSubject();if(!subject)return false;const metadata=this.focus?.metadata,section=this.fieldSection,traderSection=section.kind==="trader-system"?section:null,symbol=metaText(metadata?.symbol),name=subject.subjectKind==="wallet"?metaText(metadata?.displayName)??metaText(metadata?.name):metaText(metadata?.name),handle=metaText(metadata?.fomoHandle)??(traderSection&&this.galaxy.id==="fomo"?traderSection.handle:null),contextWallet=subject.subjectKind==="token"?metaText(metadata?.traderWallet)??traderSection?.wallet??null:null;this.watchlist=saveWatchlist(toggleWatchItem(this.watchlist,{...subject,galaxyId:this.galaxy.id,symbol,name,handle,wallet:contextWallet,chainKey:metaText(metadata?.chainKey)}));this.field.setWatchlistMints(tokenWatchMints(this.watchlist));if(this.fieldSection.kind==="watchlist")this.enterWatchlist();else this.#applySky();this.#emit();return isWatched(this.watchlist,subject.subjectKind,subject.subjectId);}
  isFocusedWatched(){const subject=this.#focusedWatchSubject();return Boolean(subject&&isWatched(this.watchlist,subject.subjectKind,subject.subjectId));}

  setGalaxy(id:GalaxyId){if(this.queryActive||!isPopulatedGalaxy(id))return false;const next=getGalaxy(id);if(next.id===this.galaxy.id&&this.fieldSection.kind==="galaxy"){this.#emit();return true;}this.galaxy=next;this.#stopVoice();this.#focusResolveSeq++;this.#prototype=createGalaxySnapshot(next,deviceBudget().field);this.#live=null;this.focus=null;this.evidence=null;this.askPrefill=this.#pendingFocusMint??"";this.result=null;this.fieldSection={kind:"galaxy",label:next.name,count:0};this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:`Loading ${next.name} cached coverage.`};this.mode="explore";this.askNotice="";this.#applySky();this.#emit();this.#hydration=this.#hydrateGalaxy(id);return true;}
  async #hydrateGalaxy(id:GalaxyId){const seq=++this.#snapshotSeq;void unregisterStaleServiceWorkers();if(id==="galaxy-zero"){this.#live=null;this.dataStatus={store:"memory-fallback",coverage:"fresh",circuitBreaker:null,disclosure:"The Field. FOMO and Afterbell are equal floors. No provider request is made from the Field."};this.#applySky();this.#emit();return;}if(id==="fomo"){const data=await getFomoGalaxy();if(this.#destroyed||this.queryActive||seq!==this.#snapshotSeq||id!==this.galaxy.id)return;if(data.ok)this.#fomoData=data;const snapshot=data.ok?buildFomoGalaxySnapshot(data):null;this.#live=snapshot&&snapshot.particles.length?snapshot:null;this.dataStatus={store:"d1",coverage:data.coverage==="fresh"?"fresh":data.coverage,circuitBreaker:null,disclosure:data.disclosure};this.#applySky();this.#emit();return;}if(id==="afterbell"){const data=await getAfterbellGalaxy();const traders=data.ok?await getAfterbellTraders({data:{mints:data.planets.map(item=>item.mint),limit:50}}):null;if(this.#destroyed||this.queryActive||seq!==this.#snapshotSeq||id!==this.galaxy.id)return;if(data.ok){this.#afterbellMarkets=data;if(traders?.ok)this.#afterbellTraders=traders;}const snapshot=data.ok&&traders?buildAfterbellGalaxySnapshot(data,traders):null;this.#live=snapshot&&snapshot.particles.length?snapshot:null;this.dataStatus={store:"d1",coverage:traders?.coverage??data.coverage,circuitBreaker:null,disclosure:traders?`${traders.disclosure} ${data.disclosure}`:data.disclosure};this.#applySky();this.#emit();return;}let delivery;try{delivery=await getIndexedGalaxySnapshot({data:{galaxyId:id}});}catch{delivery={snapshot:null,status:{store:"memory-fallback" as const,coverage:"degraded" as const,circuitBreaker:null,disclosure:"Live galaxy data is temporarily unavailable. Public search is still available."}};}if(this.#destroyed||this.queryActive||seq!==this.#snapshotSeq||id!==this.galaxy.id)return;const indexed=delivery.snapshot,count=indexed?.particles.length??0,budget=deviceBudget().field;this.#live=indexed&&count>0?indexed:null;if(shouldReplacePrototypeField(indexed,budget)||this.#live)this.dataStatus={...delivery.status};else{const floor=visibilityFloor(budget),empty="The indexed snapshot contains no qualifying evidence, so decorative dust remains visible without being promoted into market objects.";this.dataStatus={...delivery.status,store:"memory-fallback",coverage:count>0?"stale":delivery.status.coverage,disclosure:count>0?sparseHydrateDisclosure(delivery.status.disclosure,count,floor):`${delivery.status.disclosure} ${empty}`.trim()};}this.#applySky();this.#emit();}

  async enterAfterbellTraderSystem(traderStar:FieldParticle){
    const wallet=typeof traderStar.metadata?.wallet==="string"?traderStar.metadata.wallet.trim():"";if(!wallet)return false;
    this.#stopVoice();this.#focusResolveSeq++;this.mode="explore";
    const rank=typeof traderStar.metadata?.afterbellRank==="number"?traderStar.metadata.afterbellRank:null;
    const label=typeof traderStar.metadata?.displayName==="string"&&traderStar.metadata.displayName.trim()?traderStar.metadata.displayName.trim():typeof traderStar.metadata?.name==="string"&&traderStar.metadata.name.trim()?traderStar.metadata.name.trim():wallet.length>=8?`${wallet.slice(0,4)}…${wallet.slice(-4)}`:wallet;
    const holdings=Array.isArray(traderStar.metadata?.holdings)?traderStar.metadata.holdings:[],mostTraded=Array.isArray(traderStar.metadata?.mostTraded)?traderStar.metadata.mostTraded:[],latestTrades=Array.isArray(traderStar.metadata?.latestTrades)?traderStar.metadata.latestTrades.slice(0,3):[];
    const labels=mostTraded.slice(0,5).map((row:any)=>String(row?.symbol||row?.cashSymbol||row?.mint||"").trim()).filter(Boolean);
    const sourceLabels=[...new Set([...(Array.isArray(traderStar.metadata?.sources)?traderStar.metadata.sources:[]),traderStar.source].map(value=>String(value??"").trim()).filter(Boolean))];
    const afterbell={rank,uniqueAfterCloseTxCount:Number(traderStar.metadata?.uniqueAfterCloseTxCount??traderStar.metadata?.transactionCount??0),displayNameSource:typeof traderStar.metadata?.displayNameSource==="string"?traderStar.metadata.displayNameSource:null,windowLabel:typeof traderStar.metadata?.windowLabel==="string"?traderStar.metadata.windowLabel:null,calendarCoverage:typeof traderStar.metadata?.calendarCoverage==="string"?traderStar.metadata.calendarCoverage:null,holdingsCount:holdings.length,mostTradedLabels:labels,latestTradeCount:latestTrades.length,sourceLabels};
    this.fieldSection={kind:"trader-system",label,handle:`afterbell:${wallet}`,wallet,count:0,afterbell};
    this.dataStatus={store:"d1",coverage:"fresh",circuitBreaker:null,disclosure:"Opening retained Afterbell holdings, most-traded xStocks, and latest retained trade receipts for this ranked public wallet."};
    if(this.galaxy.id!=="afterbell"){this.galaxy=getGalaxy("afterbell");}
    const snapshot=buildAfterbellTraderSystemSnapshot(traderStar);this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.24,pitch:.13,distance:100,target:[0,10,0]};this.field.beginFlight();this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;this.askPrefill=wallet;
    const count=snapshot.particles.filter(item=>item.cosmicKind==="planet").length,comets=snapshot.particles.filter(item=>item.cosmicKind==="comet").length;
    this.fieldSection={kind:"trader-system",label,handle:`afterbell:${wallet}`,wallet,count,afterbell,trader:afterbellTraderDetail(traderStar,count,comets)};
    this.dataStatus={store:"d1",coverage:count?"fresh":"empty",circuitBreaker:null,disclosure:count?"Retained Afterbell holdings, most-traded xStocks, and latest retained prints for this public wallet.":"No retained xStock PLANETS for this public wallet. The system stays empty."};
    const prior=loadResearchThread();saveResearchThread(createResearchThreadContext({galaxyId:"afterbell",chainKey:"solana",wallet,displayName:label,fromTs:snapshot.windowStart,toTs:snapshot.windowEnd,replaySpeed:prior.replaySpeed}));
    this.#emit();return true;
  }

  async enterFomoTraderSystem(traderStar:FieldParticle){const handle=typeof traderStar.metadata?.fomoHandle==="string"?traderStar.metadata.fomoHandle.trim():"";if(!handle)return false;this.#stopVoice();this.#focusResolveSeq++;this.mode="explore";const wallet=typeof traderStar.metadata?.solanaWallet==="string"?traderStar.metadata.solanaWallet:typeof traderStar.metadata?.wallet==="string"?traderStar.metadata.wallet:null,label=typeof traderStar.metadata?.displayName==="string"?traderStar.metadata.displayName:handle;this.fieldSection={kind:"trader-system",label,handle,wallet,count:0};this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:"Reading the cached trader system and retained public-chain evidence."};this.#emit();const data=await getFomoTraderSystem({data:{handle}});if(this.#destroyed||this.fieldSection.kind!=="trader-system"||this.fieldSection.handle!==handle)return false;if(!data.ok){this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:data.disclosure};this.narrateObserved(data.disclosure);this.#emit();return false;}const snapshot=buildFomoTraderSystemSnapshot(data);this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.24,pitch:.13,distance:100,target:[0,10,0]};this.field.beginFlight();this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;const traderWallet=data.trader?.solanaWallet??data.trader?.evmWallet??null,traderLabel=data.trader?.displayName??label;this.askPrefill=traderWallet??"";const trader=fomoTraderDetail({wallet:traderWallet,handle,displayName:data.trader?.displayName??null,rank:data.trader?.rank??null,positions:data.positions.slice(0,10),latestTrades:data.latestTrades.slice(0,3).map(item=>({side:item.side,observedAt:item.observedAt,mint:item.mint,signature:item.signature}))});this.fieldSection={kind:"trader-system",label:traderLabel,handle,wallet:traderWallet,count:Math.min(10,data.positions.length),trader};this.dataStatus={store:"d1",coverage:data.coverage==="partial"?"fresh":data.coverage,circuitBreaker:null,disclosure:data.disclosure};const prior=loadResearchThread();saveResearchThread(createResearchThreadContext({galaxyId:"fomo",chainKey:data.trader?.solanaWallet?"solana":null,wallet:traderWallet,displayName:traderLabel,replaySpeed:prior.replaySpeed}));this.#emit();return true;}
  async enterTokenSystem(tokenPlanet:FieldParticle){const mint=particleMint(tokenPlanet);if(!mint)return false;const parentWallet=this.fieldSection.kind==="wallet-system"?this.fieldSection.wallet:this.fieldSection.kind==="trader-system"?this.fieldSection.wallet:null,chainKey=typeof tokenPlanet.metadata?.chainKey==="string"?tokenPlanet.metadata.chainKey:typeof tokenPlanet.metadata?.chain==="string"?tokenPlanet.metadata.chain:this.galaxy.id==="solana-core"||this.galaxy.id==="afterbell"?"solana":"solana";this.#stopVoice();this.#focusResolveSeq++;this.mode="explore";this.fieldSection={kind:"token-system",label:typeof tokenPlanet.metadata?.symbol==="string"?tokenPlanet.metadata.symbol:mint.slice(0,8),mint,wallet:parentWallet,chainKey,count:0};this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:"Reading retained holder-star evidence for this token planet."};this.#emit();const data=await getTokenSystem({data:{mint,galaxyId:this.galaxy.id,chainKey,limit:50}});if(this.#destroyed||this.fieldSection.kind!=="token-system"||this.fieldSection.mint!==mint)return false;if(!data.ok&&data.coverage==="degraded"){this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:data.disclosure};this.narrateObserved(data.disclosure);this.#emit();return false;}const snapshot=buildTokenSystemSnapshot(tokenPlanet,data);this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.28,pitch:.16,distance:88,target:[0,9,0]};this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;this.fieldSection={kind:"token-system",label:typeof tokenPlanet.metadata?.symbol==="string"?tokenPlanet.metadata.symbol:mint.slice(0,8),mint,wallet:parentWallet,chainKey,count:data.holders.length};this.dataStatus={store:"d1",coverage:data.coverage,circuitBreaker:null,disclosure:data.disclosure};this.#emit();this.narrateObserved(`${speakObservedParticle(snapshot.particles[0]??tokenPlanet,snapshot)} ${data.disclosure}`.trim());return true;}
  async enterWalletResearchSystem(walletInput:string){const wallet=walletInput.trim();if(!wallet)return false;if(this.queryActive)await this.returnToField();this.#stopVoice();this.#focusResolveSeq++;this.mode="explore";this.focus=null;this.evidence=null;this.askPrefill=wallet;this.fieldSection={kind:"wallet-system",label:`Wallet …${wallet.slice(-6)}`,wallet,count:0};this.dataStatus={store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:"Reading retained chain-qualified wallet activity."};this.#emit();const data=await getWalletResearchSystem({data:{wallet,limit:10}});if(this.#destroyed||this.fieldSection.kind!=="wallet-system"||this.fieldSection.wallet!==wallet)return false;const snapshot=buildWalletResearchSystemSnapshot(data);this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.22,pitch:.13,distance:102,target:[0,10,0]};this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;this.fieldSection={kind:"wallet-system",label:`Wallet …${wallet.slice(-6)}`,wallet,count:data.items.length};this.dataStatus={store:"d1",coverage:data.coverage,circuitBreaker:null,disclosure:data.disclosure};this.#emit();this.narrateObserved(data.items.length?`Public wallet ending in ${wallet.slice(-6)}. Around this star are ${data.items.length} chain-qualified token planets from retained evidence. Missing chains and missing valuation stay unavailable.`:`Public wallet ending in ${wallet.slice(-6)}. No retained wallet-token evidence is indexed yet, so this star has an empty sky rather than invented planets.`);return true;}

  #traderSection(){return this.fieldSection.kind==="trader-system"?this.fieldSection:null;}
  #selectTraderPlanet(particle:FieldParticle,mint:string){
    const section=this.#traderSection();if(!section)return;
    const room=roomFor(this.galaxy.id),chainKey=metaText(particle.metadata?.chainKey)??metaText(particle.metadata?.chain)??"solana",wallet=metaText(particle.metadata?.traderWallet)??metaText(particle.metadata?.wallet)??section.wallet,prior=loadResearchThread();
    saveResearchThread(createResearchThreadContext({galaxyId:this.galaxy.id,chainKey,wallet,displayName:section.trader?.identity??section.label,mint,symbol:metaText(particle.metadata?.symbol),fromTs:room==="afterbell"?this.field.snapshot.windowStart:null,toTs:room==="afterbell"?this.field.snapshot.windowEnd:null,replaySpeed:prior.replaySpeed}));
    this.askPrefill=mint;this.#emit();
  }
  #openPrint(particle:FieldParticle,mode:"replay"|"evidence"){
    const section=this.#traderSection();if(!section)return false;
    const selected=tradeReplaySelection(particle,section.wallet);if(!selected)return false;
    const room=roomFor(this.galaxy.id),planet=this.field.snapshot.particles.find(item=>item.cosmicKind==="planet"&&particleMint(item)?.toLowerCase()===selected.mint.toLowerCase()),signature=metaText(particle.metadata?.signature),eventId=particle.verificationState==="observed"?String(particle.eventId??"").trim():"",prior=loadResearchThread();
    saveResearchThread(createResearchThreadContext({...selected,galaxyId:this.galaxy.id,displayName:section.trader?.identity??section.label,symbol:metaText(planet?.metadata?.symbol),fromTs:room==="afterbell"?this.field.snapshot.windowStart:selected.fromTs,toTs:room==="afterbell"?this.field.snapshot.windowEnd:selected.toTs,entrySignature:signature,evidenceIds:eventId?[eventId]:[],replaySpeed:prior.replaySpeed}));
    this.askPrefill=selected.mint;this.#openResearch(mode);return true;
  }
  #openResearch(mode:"replay"|"evidence"){if(mode==="replay"){this.mode="replay";this.replay={...this.replay,active:true,status:"paused",cursor:1,visibleEventCount:visibleReplayCount(this.field.snapshot,1)};this.field.setReplay({active:true,cursor:1,playing:false});this.#emit();return;}this.setMode("evidence");}
  /** STAR action: Replay/Evidence use the selected PLANET, else the latest retained print, else the first mapped PLANET. Nothing is guessed. */
  openTraderResearch(mode:"replay"|"evidence"){
    const section=this.#traderSection();if(!section)return false;
    const focusMint=this.focus?.cosmicKind==="planet"?particleMint(this.focus):null;
    if(focusMint&&this.focus){const planet=this.field.snapshot.particles.find(item=>item.id===this.focus?.id);if(planet){this.#selectTraderPlanet(planet,focusMint);this.#openResearch(mode);return true;}}
    const comets=this.field.snapshot.particles.filter(item=>item.cosmicKind==="comet"&&particleMint(item)).sort((a,b)=>b.observedAt-a.observedAt);
    if(comets[0]&&this.#openPrint(comets[0],mode))return true;
    const planet=this.field.snapshot.particles.find(item=>item.cosmicKind==="planet"&&particleMint(item));
    const mint=planet?particleMint(planet):null;if(planet&&mint){this.#selectTraderPlanet(planet,mint);this.#openResearch(mode);return true;}
    return false;
  }
  toggleWatchTrader(){
    const section=this.#traderSection();if(!section?.wallet)return false;
    const trader=section.trader,room=roomFor(this.galaxy.id);
    this.watchlist=saveWatchlist(toggleWatchItem(this.watchlist,{subjectKind:"wallet",subjectId:section.wallet,galaxyId:this.galaxy.id,name:trader?.identity??section.label,symbol:null,handle:room==="fomo"?section.handle:null,chainKey:null,lastPrint:trader?.latestPrint?{side:trader.latestPrint.side,at:trader.latestPrint.at,symbol:trader.latestPrint.symbol}:null}));
    this.#applyWatchChange();return isWatched(this.watchlist,"wallet",section.wallet);
  }
  toggleWatchSubject(next:Parameters<typeof toggleWatchItem>[1]){this.watchlist=saveWatchlist(toggleWatchItem(this.watchlist,next));this.#applyWatchChange();return isWatched(this.watchlist,next.subjectKind,next.subjectId);}
  setFieldSuspended(on:boolean){this.field.setSuspended(on);}
  isTraderWatched(){const section=this.#traderSection();return Boolean(section?.wallet&&isWatched(this.watchlist,"wallet",section.wallet));}
  removeWatch(item:Pick<WatchItem,"subjectKind"|"subjectId">){this.watchlist=saveWatchlist(removeWatchItem(this.watchlist,item.subjectKind,item.subjectId));this.#applyWatchChange();}
  #applyWatchChange(){this.field.setWatchlistMints(tokenWatchMints(this.watchlist));if(this.fieldSection.kind==="watchlist")this.enterWatchlist();this.#emit();}
  #watchItemFor(particle:FieldParticle){const kind=particle.metadata?.watchSubjectKind,id=particle.metadata?.watchSubjectId;return typeof kind==="string"&&typeof id==="string"?this.watchlist.find(item=>item.subjectKind===kind&&item.subjectId===id)??null:null;}
  async openWatchItem(item:WatchItem){
    const room=roomFor(item.galaxyId)??"fomo";
    if(item.subjectKind==="wallet")return this.openTrader({room,wallet:item.subjectId,handle:item.handle??null});
    if(item.subjectKind==="token")return this.openToken({room,mint:item.subjectId,wallet:item.wallet??null,handle:item.handle??null,symbol:item.symbol,chainKey:item.chainKey??null});
    return false;
  }
  async #enterRoom(room:FieldRoom){if(this.queryActive)await this.returnToField();if(this.galaxy.id!==room||this.fieldSection.kind!=="galaxy")this.setGalaxy(room);await this.#hydration;}
  async openTrader(input:{room:FieldRoom;wallet?:string|null;handle?:string|null}){
    await this.#enterRoom(input.room);if(this.#destroyed)return false;
    const live=this.#live?.particles??[];
    if(input.room==="fomo"){
      const wallet=input.wallet?.trim()||null,handle=input.handle?.trim()||this.#fomoData?.items.find(item=>wallet&&(item.solanaWallet===wallet||item.evmWallet?.toLowerCase()===wallet.toLowerCase()))?.handle||null;
      if(!handle){if(wallet)return this.enterWalletResearchSystem(wallet);return false;}
      const star=live.find(item=>item.metadata?.fomoHandle===handle)??{id:`star:fomo:${handle}`,kind:"wallet",cosmicKind:"star" as const,originGalaxyId:"fomo" as const,verificationState:"provider-reported",observedAt:Date.now(),category:"swap" as const,magnitudeBand:1,position:[0,0,0] as [number,number,number],metadata:{fomoTrader:true,fomoHandle:handle,wallet:wallet??"",displayName:handle}};
      return this.enterFomoTraderSystem(star);
    }
    const wallet=input.wallet?.trim()||"";if(!wallet)return false;
    const star=live.find(item=>item.metadata?.afterbellTrader===true&&item.metadata.wallet===wallet);
    if(star)return this.enterAfterbellTraderSystem(star);
    this.askNotice="This wallet is outside the current Afterbell window.";return this.enterWalletResearchSystem(wallet);
  }
  async openToken(input:{room:FieldRoom;mint:string;wallet?:string|null;handle?:string|null;symbol?:string|null;chainKey?:string|null}){
    const mint=input.mint.trim();if(!mint)return false;
    if(input.wallet||input.handle){const opened=await this.openTrader({room:input.room,wallet:input.wallet,handle:input.handle});if(opened&&this.fieldSection.kind==="trader-system"){this.field.focusByMint(mint);return true;}}
    if(input.room==="afterbell")return this.enterAfterbellPlanet(mint,input.symbol??null);
    await this.#enterRoom(input.room);
    const planet:FieldParticle={id:`planet:${input.room}:${mint}`,kind:"token",cosmicKind:"planet",originGalaxyId:input.room,verificationState:"saved-reference",observedAt:Date.now(),category:"swap",magnitudeBand:.8,position:[0,0,0],metadata:{mint,symbol:input.symbol??null,chainKey:input.chainKey??"solana"}};
    return this.enterTokenSystem(planet);
  }
  /** xStock PLANET sky: only Afterbell traders with retained after-close prints on this mint become STARS. */
  async enterAfterbellPlanet(mint:string,symbol:string|null){
    await this.#enterRoom("afterbell");if(this.#destroyed)return false;
    const market=this.#afterbellMarkets?.planets.find(item=>item.mint===mint),label=symbol??market?.symbol??`${mint.slice(0,4)}…${mint.slice(-4)}`;
    const stars=(this.#live?.particles??[]).filter(item=>item.metadata?.afterbellTrader===true&&Array.isArray(item.metadata.mints)&&(item.metadata.mints as unknown[]).includes(mint));
    const snapshot=buildAfterbellPlanetSystemSnapshot({mint,symbol:label,name:market?.name??null,stars,windowStart:this.field.snapshot.windowStart,windowEnd:this.field.snapshot.windowEnd});
    this.#stopVoice();this.#focusResolveSeq++;this.mode="explore";this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.28,pitch:.16,distance:92,target:[0,6,0]};this.field.beginFlight();this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;this.askPrefill=mint;
    this.fieldSection={kind:"afterbell-system",label,mint,count:stars.length};
    this.dataStatus={store:"d1",coverage:stars.length?"fresh":"empty",circuitBreaker:null,disclosure:stars.length?`${stars.length} Afterbell traders printed ${label} after the close. Rank is unique prints, not performance.`:`No retained after-close prints for ${label} in this window. Missing evidence stays missing.`};
    const prior=loadResearchThread();saveResearchThread(createResearchThreadContext({galaxyId:"afterbell",chainKey:"solana",mint,symbol:label,fromTs:snapshot.windowStart,toTs:snapshot.windowEnd,replaySpeed:prior.replaySpeed}));
    this.#emit();return true;
  }
  async #askIndex():Promise<AskIndex>{
    if(!this.#fomoData){try{const data=await getFomoGalaxy();if(data.ok)this.#fomoData=data;}catch{}}
    if(!this.#afterbellMarkets||!this.#afterbellTraders){try{const markets=this.#afterbellMarkets??await getAfterbellGalaxy();if(markets.ok){this.#afterbellMarkets=markets;const traders=await getAfterbellTraders({data:{mints:markets.planets.map(item=>item.mint),limit:50}});if(traders.ok)this.#afterbellTraders=traders;}}catch{}}
    const traders=[...(this.#fomoData?.items??[]).flatMap(item=>{const wallet=item.solanaWallet??item.evmWallet;return wallet?[{room:"fomo" as const,wallet,handle:item.handle,displayName:item.displayName}]:[];}),...(this.#afterbellTraders?.items??[]).map(item=>({room:"afterbell" as const,wallet:item.wallet,handle:null,displayName:item.displayName}))];
    const room=roomFor(this.galaxy.id)??"fomo",tokens=[...(this.#afterbellMarkets?.planets??[]).map(item=>({room:"afterbell" as const,mint:item.mint,symbol:item.symbol,name:item.name})),...this.field.snapshot.particles.flatMap(item=>{const mint=item.cosmicKind==="planet"?particleMint(item):null;return mint?[{room,mint,symbol:metaText(item.metadata?.symbol),name:metaText(item.metadata?.name)}]:[];})];
    return{traders,tokens};
  }
  clearAskNotice(){if(!this.askNotice)return;this.askNotice="";this.#emit();}

  exitTokenSystem(){if(this.fieldSection.kind==="token-system")this.exitSpecialSection();}
  exitSpecialSection(emit=true){this.fieldSection={kind:"galaxy",label:this.galaxy.name,count:this.livePlanetCount};this.mode="explore";this.focus=null;this.evidence=null;this.result=null;if(this.#baseSky){this.field.setSnapshot(this.#baseSky);this.field.cameraState={yaw:.4,pitch:.18,distance:this.galaxy.id==="galaxy-zero"?205:125,target:[0,0,0]};this.replay=createReplayState(this.#baseSky);}if(emit)this.#emit();}
  async enterObservatory(){this.setGalaxy("fomo");}
  enterWatchlist(){if(this.queryActive)return;this.#stopVoice();this.mode="watchlist";const snapshot=buildWatchlistSnapshot(this.watchlist,this.#baseSky);this.field.setSnapshot(snapshot);this.field.cameraState={yaw:.18,pitch:.12,distance:105,target:[0,7,0]};this.replay=createReplayState(snapshot);this.focus=null;this.evidence=null;this.fieldSection={kind:"watchlist",label:"My Sky",count:this.watchlist.length};this.dataStatus={store:"memory-fallback",coverage:this.watchlist.length?"fresh":"empty",circuitBreaker:null,disclosure:snapshot.coverageStatement};this.#emit();}

  setMode(mode:FieldMode){if(mode==="query"){if(this.queryActive){this.#emit();return;}this.mode="query";this.#emit();return;}if(this.queryActive)void this.returnToField();if(mode==="observatory"){this.setGalaxy("fomo");return;}if(mode==="watchlist"){this.enterWatchlist();return;}if(mode==="explore"&&this.fieldSection.kind!=="galaxy"){this.exitSpecialSection();return;}if(mode==="replay"){this.enterReplay();return;}if(mode==="evidence"){this.field.setReplay({active:true,playing:false,cursor:this.replay.cursor});this.replay={...this.replay,active:true,status:"paused"};this.mode="evidence";this.#emit();return;}if(this.replay.active){this.field.setReplay({active:false,cursor:1,playing:false});this.replay={...this.replay,active:false,status:"paused",cursor:1};}this.mode=mode;this.#emit();}
  closeResearch(){if(this.replay.active){this.field.setReplay({active:false,cursor:1,playing:false});this.replay={...this.replay,active:false,status:"paused",cursor:1};}this.mode="explore";this.#emit();}
  enterReplay(){if(this.queryActive)return;const cursor=this.replay.active?this.replay.cursor:0;this.mode="replay";this.replay={...this.replay,active:true,status:"paused",cursor,visibleEventCount:visibleReplayCount(this.field.snapshot,cursor)};this.field.setReplay({active:true,cursor,playing:false});this.field.clearFocus();this.#emit();}
  toggleReplay(){if(!this.replay.active)this.enterReplay();const restart=this.replay.cursor>=1,cursor=restart?0:this.replay.cursor,playing=this.replay.status!=="playing";this.replay={...this.replay,active:true,cursor,status:playing?"playing":"paused",visibleEventCount:visibleReplayCount(this.field.snapshot,cursor)};this.field.setReplay({active:true,cursor,playing});this.#emit();}
  seekReplay(cursor:number){const safe=Math.min(1,Math.max(0,cursor));this.replay={...this.replay,active:true,status:"paused",cursor:safe,visibleEventCount:visibleReplayCount(this.field.snapshot,safe)};this.field.setReplay({active:true,cursor:safe,playing:false});this.field.clearFocus();this.#emit();}
  stepReplay(direction:-1|1){this.seekReplay(stepReplayCursor(this.field.snapshot,this.replay.cursor,direction));}
  async enterQuery(){if(this.queryActive&&this.organism)return;this.mode="query";this.#focusResolveSeq++;this.queryActive=true;this.organismState="idle";this.focus=null;this.evidence=null;this.field.setReplay({active:false,cursor:1,playing:false});this.#cameraSnapshot=this.field.snapshotCamera();this.field.setQueryActive(true);this.organism?.destroy();this.organism=new LivingAlienOrganism(this.field,this.field.getParentPositions(),this.field.getParentColors(),this.field.getParticleCount());this.organism.setState("idle");this.#emit();}
  async returnToField(){this.#querySeq++;this.#focusResolveSeq++;this.#stopVoice();this.organismState="return";this.#emit();this.organism?.setState("return");await this.organism?.dissolve();if(this.#destroyed)return;this.organism?.destroy();this.organism=null;this.field.setQueryActive(false);this.queryActive=false;this.organismState="idle";this.mode="explore";this.result=null;this.fieldSection={kind:"galaxy",label:this.galaxy.name,count:this.livePlanetCount};if(this.#baseSky){this.field.setSnapshot(this.#baseSky);this.field.cameraState={yaw:.4,pitch:.18,distance:this.galaxy.id==="galaxy-zero"?205:125,target:[0,0,0]};}else if(this.#cameraSnapshot)this.field.restoreCamera(this.#cameraSnapshot);this.#emit();void this.#hydrateGalaxy(this.galaxy.id);}
  setMuted(muted:boolean){this.muted=muted;try{globalThis.localStorage?.setItem("abulls-mute",muted?"1":"0");}catch{}if(muted)this.#stopVoice();this.#emit();}
  narrateObserved(text:string){this.#stopVoice();this.#voice=speakText(text,{muted:this.muted,volume:this.volume,onEnd:()=>{this.#voice=null;this.#emit();}});this.#emit();}
  async #narrateResolvedMarket(particleId:string,mint:string,allowMissingFocus=false){const seq=++this.#focusResolveSeq,result=await resolvePublicIdentifier({data:{query:mint}});if(seq!==this.#focusResolveSeq||this.queryActive)return;if(!allowMissingFocus&&this.focus?.id!==particleId)return;this.result=result;this.#emit();this.narrateObserved(result.spokenText);}
  async submitQuery(value:string){const query=value.trim();if(!query)return;unlockSpeech();this.#stopVoice();this.askNotice="";const local=resolveLocal(query,await this.#askIndex(),XSTOCK_REGISTRY);if(local.kind==="trader"){this.#emit();await this.openTrader({room:local.trader.room,wallet:local.trader.wallet,handle:local.trader.handle});return;}if(local.kind==="token"){this.#emit();await this.openToken({room:local.token.room,mint:local.token.mint,symbol:local.token.symbol});return;}if(local.kind==="miss"){if(this.queryActive)await this.returnToField();this.askNotice=ASK_MISS_LINE;this.#emit();return;}if(!this.queryActive||!this.organism)await this.enterQuery();const seq=++this.#querySeq;this.result=null;this.organismState="listening";this.organism?.setState("listening");this.#emit();await wait(280);if(seq!==this.#querySeq)return;this.organismState="analyzing";this.organism?.setState("analyzing");this.#emit();const result=await resolvePublicIdentifier({data:{query}});if(seq!==this.#querySeq)return;let openWallet=result.ok&&result.kind==="wallet";if(!openWallet&&/^0x[a-fA-F0-9]{40}$/.test(query)){try{const walletData=await getWalletResearchSystem({data:{wallet:query,limit:1}});openWallet=walletData.ok&&walletData.items.length>0;}catch{openWallet=false;}}this.result=result;this.organismState="speaking";this.organism?.setState("speaking");this.#emit();const finish=()=>{this.#pulseSpeech(false);this.organism?.setSpeech(0);if(seq!==this.#querySeq)return;this.organismState="complete";this.organism?.setState("complete");this.#voice=null;this.#emit();if(openWallet)void this.enterWalletResearchSystem(query);};this.#voice=speakText(result.spokenText,{muted:this.muted,volume:this.volume,onStart:()=>this.#pulseSpeech(true),onBoundary:()=>this.organism?.setSpeech(.34),onEnergy:e=>this.organism?.setSpeech(e),onEnd:finish});if(this.muted)finish();}
  #pulseSpeech(on:boolean){this.organism?.setSpeech(on?.52:0);}
  #stopVoice(){this.#voice?.stop();this.#voice=null;this.#pulseSpeech(false);}
  destroy(){this.#destroyed=true;this.#snapshotSeq++;this.#querySeq++;this.#focusResolveSeq++;globalThis.removeEventListener(FIELD_RESEARCH_MODE_EVENT,this.#researchModeListener);if(this.#hydrateTimer)globalThis.clearInterval(this.#hydrateTimer);this.#stopVoice();this.organism?.destroy();this.field.destroy();}
}
async function unregisterStaleServiceWorkers(){if(typeof navigator==="undefined"||!("serviceWorker" in navigator))return;try{const registrations=await navigator.serviceWorker.getRegistrations();await Promise.all(registrations.map(registration=>registration.unregister()));}catch{}}
function wait(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
