import type { FieldParticle, UniverseSnapshot } from "./types";
import type { FomoGalaxyResponse, FomoTrader } from "@/lib/universe-data/fomo-client";
import { canonicalUniverseId } from "./galaxies";

function clamp01(value:number){return Math.max(0,Math.min(1,Number.isFinite(value)?value:0));}
function positionForRank(rank:number):[number,number,number]{if(rank===1)return[0,34,0];const ring=rank<=10?25:rank<=28?44:64,count=rank<=10?9:rank<=28?18:22,start=rank<=10?2:rank<=28?11:29,angle=((rank-start)/count)*Math.PI*2-Math.PI/2,y=10+(rank<=10?18:rank<=28?8:0)+Math.sin(angle*2)*4;return[Math.cos(angle)*ring,y,Math.sin(angle)*ring];}
function compactUsd(value:number|null){if(value==null||!Number.isFinite(value))return"PNL N/A";const sign=value>=0?"+":"-",amount=Math.abs(value);if(amount>=1_000_000_000)return`${sign}$${(amount/1_000_000_000).toFixed(amount>=10_000_000_000?0:1)}B`;if(amount>=1_000_000)return`${sign}$${(amount/1_000_000).toFixed(amount>=10_000_000?0:1)}M`;if(amount>=1_000)return`${sign}$${(amount/1_000).toFixed(amount>=100_000?0:1)}K`;return`${sign}$${amount.toFixed(amount>=100?0:2)}`;}
export function fomoStarLabel(item:Pick<FomoTrader,"rank"|"handle"|"displayName"|"reportedPnlUsd">){const tag=(item.handle||item.displayName).replace(/[^a-z0-9]/gi,"").slice(0,4).toUpperCase();return`#${item.rank} ${compactUsd(item.reportedPnlUsd)}${tag?` ${tag}`:""}`;}
export function buildFomoGalaxySnapshot(data:FomoGalaxyResponse):UniverseSnapshot{
  const now=data.capturedAt??Date.now(),particles:FieldParticle[]=data.items.slice(0,50).flatMap(item=>{const wallet=item.solanaWallet??item.evmWallet;if(!wallet)return[];return[{id:canonicalUniverseId("star",wallet,"fomo"),kind:"wallet",cosmicKind:"star",originGalaxyId:"fomo",verificationState:"provider-reported",observedAt:item.capturedAt||now,category:"swap",magnitudeBand:clamp01(1-(item.rank-1)/58),position:positionForRank(item.rank),source:"fomoapi.io",metadata:{name:fomoStarLabel(item),displayName:item.displayName,traderDisplayName:item.displayName,wallet,solanaWallet:item.solanaWallet,evmWallet:item.evmWallet,fomoTrader:true,fomoHandle:item.handle,fomoRank:item.rank,reportedPnlUsd:item.reportedPnlUsd,reportedVolumeUsd:item.reportedVolumeUsd,reportedTradeCount:item.reportedTradeCount,followerCount:item.followerCount,avatarUrl:item.avatarUrl,fomoCapturedAt:item.capturedAt,rankingWindow:"ALL",skyRole:"live",systemRole:"fomo-trader-star",interactive:true}}]});
  return{galaxyId:"fomo",windowStart:now-1000,windowEnd:now,observedEventCount:particles.length,samplingPolicy:"fomo all-time, as reported · cached D1 · maximum 50 trader stars",coverageStatement:data.disclosure,sources:["fomoapi.io"],particles};
}
