import type { FieldParticle, UniverseSnapshot } from "./types";
import type { FomoTraderSystemResponse } from "@/lib/universe-data/fomo-client";
import { canonicalUniverseId } from "./galaxies";

function planetPos(index:number,count:number):[number,number,number]{const angle=index/Math.max(1,count)*Math.PI*2-Math.PI/2,ring=index<5?28:48;return[Math.cos(angle)*ring,2+Math.sin(angle*2)*5,Math.sin(angle)*ring];}
export function buildFomoTraderSystemSnapshot(data:FomoTraderSystemResponse):UniverseSnapshot{
  const trader=data.trader,now=Math.max(Date.now(),...(data.latestTrades.map(item=>item.observedAt||0)));if(!trader)return{galaxyId:"fomo",windowStart:now-1,windowEnd:now,observedEventCount:0,samplingPolicy:"empty Fomo trader system",coverageStatement:data.disclosure,sources:["fomoapi.io","a-bulls-indexed-public-chain"],particles:[]};
  const wallet=trader.solanaWallet??trader.evmWallet??trader.handle,particles:FieldParticle[]=[{id:canonicalUniverseId("star",wallet,"fomo"),kind:"wallet",cosmicKind:"star",originGalaxyId:"fomo",verificationState:"provider-reported",observedAt:trader.capturedAt,category:"swap",magnitudeBand:1,position:[0,28,0],source:"fomoapi.io",metadata:{name:trader.displayName,displayName:trader.displayName,wallet,solanaWallet:trader.solanaWallet,evmWallet:trader.evmWallet,fomoTrader:true,fomoHandle:trader.handle,fomoRank:trader.rank,reportedPnlUsd:trader.reportedPnlUsd,avatarUrl:trader.avatarUrl,systemRole:"focused-trader-star"}}];
  for(const [index,item] of data.positions.slice(0,10).entries())particles.push({id:`planet:solana-core:${item.mint}`,kind:"token",cosmicKind:"planet",originGalaxyId:"solana-core",verificationState:item.sourceKind.includes("a-bulls-observed")?"observed":"provider-reported",observedAt:item.lastObservedAt??trader.capturedAt,category:"swap",magnitudeBand:.88-index*.045,position:planetPos(index,Math.min(10,data.positions.length)),source:item.sourceKind,metadata:{mint:item.mint,symbol:item.symbol,name:item.name,traderWallet:trader.solanaWallet,traderHandle:trader.handle,wallet:trader.solanaWallet,positionRank:item.rank,positionSource:item.sourceKind,observedNetTokenFlow:item.observedNetTokenFlow,tradeCount:item.tradeCount,eventCount:item.eventCount,lastObservedAt:item.lastObservedAt,systemRole:"trader-position-planet"}});
  for(const [index,trade] of data.latestTrades.slice(0,3).entries()){const target=particles.find(p=>p.cosmicKind==="planet"&&p.metadata?.mint===trade.mint);const end=target?.position??[20-index*20,-10,15+index*12];const start:[number,number,number]=trade.side==="buy"?[-65+index*12,42-index*8,-36+index*18]:end as [number,number,number];const position:[number,number,number]=trade.side==="buy"?[(start[0]+end[0])/2,(start[1]+end[1])/2+8,(start[2]+end[2])/2]:[end[0]*1.55,end[1]+16,end[2]*1.55];particles.push({id:`fomo-comet:${trade.signature??`${trader.handle}:${index}`}`,eventId:trade.signature??`fomo:${trader.handle}:trade:${index}`,kind:"trade",cosmicKind:"comet",originGalaxyId:"solana-core",verificationState:"observed",observedAt:trade.observedAt,category:"swap",magnitudeBand:.92-index*.1,position,source:trade.source,metadata:{signature:trade.signature,wallet:trade.wallet,mint:trade.mint,side:trade.side,solAmount:trade.solAmount,tokenAmount:trade.tokenAmount,priceSol:trade.priceSol,traderHandle:trader.handle,tradeOrder:index+1,systemRole:"latest-trade-comet"}});}
  const times=data.latestTrades.map(item=>item.observedAt).filter(Number.isFinite);return{galaxyId:"fomo",windowStart:times.length?Math.min(...times):trader.capturedAt,windowEnd:Math.max(now,trader.capturedAt),observedEventCount:data.latestTrades.length,samplingPolicy:"Fomo-reported top-token addresses + retained A Bulls App public-chain wallet observations · top 10 planets · latest 3 observed trades",coverageStatement:data.disclosure,sources:["fomoapi.io","a-bulls-indexed-public-chain"],particles};
}
