import type { FieldParticle, JsonValue, UniverseSnapshot } from "./types.ts";
import { fiveMinuteHeat, formatHeat, particleMint, uniqueTraders, liquidityUsd, liquiditySol, tapeM5, type FiveMinuteHeat } from "./volume-sky.ts";
import { cosmicMeaning, renderCosmicKind } from "./cosmic-visuals.ts";

const shortId=(raw:string)=>raw.trim().length<=12?raw.trim():`${raw.trim().slice(0,4)}…${raw.trim().slice(-4)}`;
const usd=(value:number)=>value.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:value<.0001?10:value<1?6:0});
const numeric=(value:JsonValue|undefined):number|null=>typeof value==="number"&&Number.isFinite(value)?value:null;
const strings=(value:JsonValue|undefined):string[]=>Array.isArray(value)?value.filter((item):item is string=>typeof item==="string"&&Boolean(item.trim())):[];
const observedTime=(ms:number)=>Number.isFinite(ms)?new Date(ms).toISOString():"unavailable";
export function containsSafetyBadge(text:string){return /\bSAFE\b/i.test(text)&&!/no safety claim/i.test(text);}
function flagPhrase(flag:string){switch(flag){case"watch-pin":return"device watch pin, not a provider membership";case"teaching-body":return"teaching body, not a live ranked market";case"thin-liquidity":return"liquidity below the observed floor";case"missing-liquidity":return"liquidity not observed";case"missing-5m-heat":return"no five-minute volume was observed";case"thin-traders":return"thin unique-trader set";case"missing-traders":return"unique traders not observed";case"one-sided-tape":return"one-sided tape in the five-minute window";case"wash-like-velocity":return"five-minute volume is high versus observed liquidity";case"young-pair":return"pair younger than three minutes";default:return flag.replaceAll("-"," ");}}
export type ObservedTokenFacts={query?:string;symbol?:string|null;name?:string|null;network?:string|null;mint?:string|null;flags:string[];priceUsd?:number|null;marketCapUsd?:number|null;liquidityUsd?:number|null;heat?:FiveMinuteHeat|null;buysM5?:number|null;sellsM5?:number|null;uniqueTraders?:number|null;disclosure?:string|null;};
export function speakObservedFacts(facts:ObservedTokenFacts){const parts:string[]=[];parts.push(facts.flags.length?`Observed flags first: ${facts.flags.map(flagPhrase).join("; ")}.`:"No wash or authority flag is attached. That is not a safety claim.");const name=facts.symbol||facts.name||(facts.mint?`token ending in ${shortId(facts.mint)}`:"this body");parts.push(`${name}${facts.network?` on ${facts.network}`:""}.`);if(typeof facts.priceUsd==="number")parts.push(`Price ${usd(facts.priceUsd)}.`);if(typeof facts.marketCapUsd==="number")parts.push(`Market cap ${usd(facts.marketCapUsd)}.`);const heat=formatHeat(facts.heat??null);if(heat)parts.push(`${heat} volume.`);if(typeof facts.liquidityUsd==="number")parts.push(`Liquidity ${usd(facts.liquidityUsd)}.`);if(typeof facts.buysM5==="number"&&typeof facts.sellsM5==="number")parts.push(`${facts.buysM5.toLocaleString()} buys versus ${facts.sellsM5.toLocaleString()} sells in five minutes.`);if(typeof facts.uniqueTraders==="number")parts.push(`${facts.uniqueTraders.toLocaleString()} unique traders observed.`);if(facts.disclosure)parts.push(facts.disclosure);parts.push("Observed data only. No safety claim or price prediction.");return parts.join(" ");}
export function flagsFromResolveMarket(input:{mintAuthorityRevoked?:boolean|null;freezeAuthorityRevoked?:boolean|null;riskFlags?:readonly string[]|null;liquidityUsd?:number|null;volumeM5Usd?:number|null;uniqueTraders?:number|null;buysM5?:number|null;sellsM5?:number|null}){const flags:string[]=[];if(input.mintAuthorityRevoked===false)flags.push("mint authority active");if(input.freezeAuthorityRevoked===false)flags.push("freeze authority active");for(const flag of input.riskFlags??[])flags.push(flag);if(typeof input.liquidityUsd==="number"&&input.liquidityUsd<10_000)flags.push("thin-liquidity");if(typeof input.volumeM5Usd==="number"&&typeof input.liquidityUsd==="number"&&input.liquidityUsd>0&&input.volumeM5Usd/input.liquidityUsd>8)flags.push("wash-like-velocity");if(typeof input.uniqueTraders==="number"&&input.uniqueTraders<10)flags.push("thin-traders");if(typeof input.buysM5==="number"&&typeof input.sellsM5==="number"&&(input.buysM5<=0||input.sellsM5<=0))flags.push("one-sided-tape");return flags;}

function speakStar(p:FieldParticle){const wallet=typeof p.metadata?.wallet==="string"?p.metadata.wallet:null,linked=strings(p.metadata?.linkedMints),share=numeric(p.metadata?.observedSharePct),net=numeric(p.metadata?.observedNetToken),tradeCount=numeric(p.metadata?.tradeCount),rank=numeric(p.metadata?.observatoryRank),realized=numeric(p.metadata?.realizedSolMatched),winRate=numeric(p.metadata?.winRate);const parts=[`STAR. ${cosmicMeaning("star")}.`,wallet?`Public wallet ${shortId(wallet)}.`:"Public wallet identity is unavailable in this snapshot."];
  if(rank!=null){parts.push(`Weekly observatory rank ${Math.trunc(rank)}.`);if(realized!=null)parts.push(`Matched in-window realized result ${realized.toLocaleString(undefined,{maximumFractionDigits:4})} SOL.`);if(winRate!=null)parts.push(`Winning matched sells ${(winRate*100).toFixed(1)} percent.`);parts.push("This ranking is descriptive indexed research, not a skill score or copy-trading instruction.");}
  else {if(share!=null)parts.push(`This wallet represents ${share.toFixed(2)} percent of the retained positive-net holder sample for this planet. That is not percent of total token supply.`);if(net!=null)parts.push(`Observed net token amount in retained events ${net.toLocaleString(undefined,{maximumFractionDigits:4})}.`);if(tradeCount!=null)parts.push(`${Math.trunc(tradeCount)} indexed token events contribute to this relationship.`);if(linked.length)parts.push(`${linked.length} indexed token relationship${linked.length===1?"":"s"} attached.`);}
  parts.push(`Observed at ${observedTime(p.observedAt)}. A public wallet is evidence, not proof of a person's identity or ownership.`);return parts.join(" ");}
function speakComet(p:FieldParticle){const side=typeof p.metadata?.side==="string"?p.metadata.side:null,sol=numeric(p.metadata?.solAmount),token=numeric(p.metadata?.tokenAmount),price=numeric(p.metadata?.priceSol),sig=typeof p.metadata?.sig==="string"?p.metadata.sig:p.eventId,mint=particleMint(p),parts=[`COMET. ${cosmicMeaning("comet")}.`];if(side)parts.push(`Indexed side ${side}.`);if(sol!=null)parts.push(`Observed size ${sol.toLocaleString(undefined,{maximumFractionDigits:4})} SOL.`);if(token!=null)parts.push(`Token amount ${token.toLocaleString(undefined,{maximumFractionDigits:4})}.`);if(price!=null)parts.push(`Observed price ${price.toLocaleString(undefined,{maximumFractionDigits:10})} SOL per token.`);if(mint)parts.push(`Token planet ${shortId(mint)}.`);if(sig)parts.push(`Transaction ${shortId(String(sig))}.`);parts.push(`Observed at ${observedTime(p.observedAt)}.`);return parts.join(" ");}
function speakLiquidity(p:FieldParticle){const usdL=liquidityUsd(p),solL=liquiditySol(p),parent=typeof p.metadata?.parentMint==="string"?p.metadata.parentMint:particleMint(p),parts=[`ASTEROID BELT. ${cosmicMeaning("asteroid-belt")}.`];if(usdL!=null)parts.push(`Observed liquidity ${usd(usdL)}.`);else if(solL!=null)parts.push(`Observed liquidity ${solL.toLocaleString(undefined,{maximumFractionDigits:4})} SOL.`);else parts.push("Liquidity is unavailable; this belt is not certified as observed market evidence.");if(parent)parts.push(`It surrounds token planet ${shortId(parent)}.`);return parts.join(" ");}
function speakWormhole(p:FieldParticle){const from=typeof p.metadata?.from==="string"?p.metadata.from:null,to=typeof p.metadata?.to==="string"?p.metadata.to:null,pool=typeof p.metadata?.pool==="string"?p.metadata.pool:null,mint=particleMint(p),parts=[`WORMHOLE. ${cosmicMeaning("wormhole")}.`];if(mint)parts.push(`Token planet ${shortId(mint)} keeps its original launch galaxy.`);if(from&&to)parts.push(`Indexed migration from ${shortId(from)} to ${shortId(to)}.`);if(pool)parts.push(`Pool ${shortId(pool)}.`);parts.push(`Observed at ${observedTime(p.observedAt)}.`);return parts.join(" ");}
function speakCollapse(p:FieldParticle,label:"BLACK HOLE"|"SUPERNOVA"){const reasons=strings(p.metadata?.reason),evidence=strings(p.metadata?.evidence),score=numeric(p.metadata?.score),mint=particleMint(p),parts=[`${label}. ${cosmicMeaning(label==="BLACK HOLE"?"black-hole":"supernova")}.`];if(mint)parts.push(`Token ${shortId(mint)}.`);if(reasons.length)parts.push(`Indexed reasons: ${reasons.join(", ")}.`);if(score!=null)parts.push(`Derived evidence score ${score.toFixed(2)}.`);if(evidence.length)parts.push(`Evidence: ${evidence.slice(0,3).join("; ")}.`);parts.push("This marker describes retained evidence; it is not a safety verdict or prediction.");return parts.join(" ");}
function speakPlanet(p:FieldParticle,snapshot:UniverseSnapshot){const mint=particleMint(p),flags=Array.isArray(p.metadata?.skyFlags)?p.metadata?.skyFlags as string[]:[],heatMeta=p.metadata?.skyHeat,unit=p.metadata?.skyHeatUnit,heat:FiveMinuteHeat|null=typeof heatMeta==="number"&&(unit==="usd"||unit==="sol")?{value:heatMeta,unit}:fiveMinuteHeat(p,snapshot),liqUsd=liquidityUsd(p),liqSol=liquiditySol(p),speech=speakObservedFacts({symbol:typeof p.metadata?.symbol==="string"?p.metadata.symbol:null,name:typeof p.metadata?.name==="string"?p.metadata.name:null,network:p.originGalaxyId==="pons"?"Robinhood Chain":"Solana",mint,flags,liquidityUsd:liqUsd,heat,uniqueTraders:uniqueTraders(p),buysM5:tapeM5(p).buys,sellsM5:tapeM5(p).sells,disclosure:liqSol!=null&&liqUsd==null?`Observed liquidity ${liqSol} SOL.`:null});return `PLANET. ${cosmicMeaning("planet")}. ${speech}${liqUsd!=null||liqSol!=null?" Its asteroid belt represents that observed liquidity.":" No asteroid belt is certified because liquidity is unavailable in this snapshot."} Touching this planet enters its retained wallet-star sky.`;}

export function speakObservedParticle(p:FieldParticle,snapshot:UniverseSnapshot):string{const kind=renderCosmicKind(p);if(kind==="dust")return"DUST. This is decorative field fabric, not a live token or certified market evidence.";if(kind==="galaxy"){const name=typeof p.metadata?.name==="string"?p.metadata.name:"Protocol galaxy";return`GALAXY. ${name}. ${cosmicMeaning("galaxy")}. Enter it to inspect indexed token planets; this directory object is not market evidence.`;}if(kind==="planet")return speakPlanet(p,snapshot);if(kind==="star")return speakStar(p);if(kind==="asteroid-belt")return speakLiquidity(p);if(kind==="comet")return speakComet(p);if(kind==="black-hole")return speakCollapse(p,"BLACK HOLE");if(kind==="supernova")return speakCollapse(p,"SUPERNOVA");if(kind==="wormhole")return speakWormhole(p);if(kind==="ghost"){const mint=particleMint(p),evidence=strings(p.metadata?.evidence);return[`GHOST. ${cosmicMeaning("ghost")}.`,mint?`Token ${shortId(mint)}.`:"No token identity is attached to this trace.",evidence.length?`Retained evidence: ${evidence.slice(0,3).join("; ")}.`:"No additional historical evidence is attached in this snapshot.","No future outcome is estimated."].join(" ");}if(kind==="moon")return`MOON. ${cosmicMeaning("moon")}. Observed at ${observedTime(p.observedAt)}.`;return"Observed object. No additional sourced description is available.";}
