import type { FieldParticle, GalaxyId, UniverseSnapshot } from "./types";
import type { TokenSystemHolder, TokenSystemResponse } from "@/lib/universe-data/contracts";
import { canonicalUniverseId } from "./galaxies";
import { liquidityBeltForPlanet, particleMint } from "./volume-sky";

type ExtendedHolder=TokenSystemHolder&{realizedPnlSol?:number|null;pnlStatus?:string;buyCount?:number;sellCount?:number;firstObservedAt?:number};
type ExtendedTokenSystem=TokenSystemResponse&{rankingMode?:"holders"|"afterbell-traders";window?:{from:number;to:number;timeZone?:string;label?:string;boundary?:string}};
function hashUnit(input:string){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0)/4294967295;}function clamp01(v:number){return Math.max(0,Math.min(1,Number.isFinite(v)?v:0));}
function holderPosition(wallet:string,rank:number):[number,number,number]{const angle=hashUnit(wallet)*Math.PI*2,ring=rank<=8?26:rank<=24?39:52,radius=ring+(hashUnit(`${wallet}:r`)-.5)*8,y=16+hashUnit(`${wallet}:y`)*42+(rank<=8?8:0);return[Math.cos(angle)*radius,y,Math.sin(angle)*radius];}
function tradePosition(seed:string,index:number):[number,number,number]{const angle=hashUnit(seed)*Math.PI*2,radius=18+(index%4)*6;return[Math.cos(angle)*radius,8+(index%7)*5,Math.sin(angle)*radius];}
export function buildTokenSystemSnapshot(tokenPlanet:FieldParticle,data:TokenSystemResponse):UniverseSnapshot{const system=data as ExtendedTokenSystem,mint=particleMint(tokenPlanet)??data.mint,galaxyId=tokenPlanet.originGalaxyId as GalaxyId,isAfterbell=system.rankingMode==="afterbell-traders",core:FieldParticle={...tokenPlanet,id:canonicalUniverseId(tokenPlanet.cosmicKind==="black-hole"?"black-hole":"planet",mint,galaxyId),cosmicKind:tokenPlanet.cosmicKind==="black-hole"?"black-hole":"planet",position:[0,-18,0],magnitudeBand:Math.max(.78,tokenPlanet.magnitudeBand),metadata:{...(tokenPlanet.metadata??{}),mint,skyRole:"live",systemRole:"token-planet-core",holderStarCount:data.holders.length,rankingMode:system.rankingMode??"holders",afterbellWindow:system.window??null}};
const holders:FieldParticle[]=data.holders.map(raw=>{const holder=raw as ExtendedHolder;return{id:canonicalUniverseId("star",holder.wallet,galaxyId),kind:"wallet",cosmicKind:"star",originGalaxyId:galaxyId,verificationState:"observed",observedAt:holder.lastObservedAt,category:isAfterbell?"swap":"transfer",magnitudeBand:isAfterbell?clamp01(Math.log10(1+holder.tradeCount)/2):holder.observedSharePct==null?clamp01(Math.log10(1+Math.abs(holder.netTokenObserved))/10):clamp01(Math.sqrt(Math.max(0,holder.observedSharePct)/100)),position:holderPosition(holder.wallet,holder.rank),source:holder.source,metadata:{name:isAfterbell?`AFTERBELL #${holder.rank}`:`HOLDER #${holder.rank}`,wallet:holder.wallet,parentMint:mint,linkedMints:[mint],holderRank:holder.rank,afterbellRank:isAfterbell?holder.rank:null,observedNetToken:holder.netTokenObserved,observedSharePct:holder.observedSharePct,tradeCount:holder.tradeCount,buyCount:holder.buyCount??null,sellCount:holder.sellCount??null,buySolObserved:holder.buySolObserved,sellSolObserved:holder.sellSolObserved,realizedPnlSol:holder.realizedPnlSol??null,pnlStatus:holder.pnlStatus??null,firstObservedAt:holder.firstObservedAt??null,lastObservedAt:holder.lastObservedAt,holderEvidenceMethod:data.method??"indexed-positive-net-position",rankingMode:system.rankingMode??"holders",afterbellWindow:system.window??null,skyRole:"live",systemRole:isAfterbell?"afterbell-trader-star":"holder-star",interactive:true}}});
const trades:FieldParticle[]=data.trades.slice(0,20).map((trade,index)=>({id:canonicalUniverseId("comet",trade.signature||`${trade.wallet}:${trade.observedAt}:${index}`,galaxyId),eventId:trade.signature??undefined,kind:"transaction",cosmicKind:"comet",originGalaxyId:galaxyId,verificationState:"observed",observedAt:trade.observedAt,category:trade.side==="buy"?"swap":"transfer",magnitudeBand:clamp01(Math.log10(1+Math.max(0,trade.solAmount))/3),position:tradePosition(trade.signature||`${trade.wallet}:${trade.observedAt}`,index),source:trade.source,metadata:{mint,wallet:trade.wallet,side:trade.side,solAmount:trade.solAmount,tokenAmount:trade.tokenAmount,priceSol:trade.priceSol,sig:trade.signature,rankingMode:system.rankingMode??"holders",afterbellWindow:system.window??null,skyRole:"live",systemRole:"token-system-comet"}}));
const belt=liquidityBeltForPlanet(core),particles=[core,...(belt?[belt]:[]),...holders,...trades],times=particles.map(p=>p.observedAt).filter(Number.isFinite),now=Date.now();return{galaxyId,windowStart:system.window?.from?system.window.from*1000:times.length?Math.min(...times):now,windowEnd:system.window?.to?system.window.to*1000:times.length?Math.max(...times):now,observedEventCount:holders.length+trades.length,samplingPolicy:isAfterbell?"afterbell retained swaps; top 50 wallet stars by transaction count then defensible closed-window PnL; recent observed comets":"token-system D1-only; positive-net retained holder stars; recent indexed comets",coverageStatement:data.disclosure,sources:[...new Set(particles.map(p=>p.source).filter((v):v is string=>Boolean(v)))],particles};}
