import type { FieldParticle, GalaxyId, UniverseSnapshot } from "./types";
import type { TokenSystemResponse } from "@/lib/universe-data/contracts";
import { canonicalUniverseId } from "./galaxies";
import { liquidityBeltForPlanet, particleMint } from "./volume-sky";
function hashUnit(input:string){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return(h>>>0)/4294967295;}function clamp01(v:number){return Math.max(0,Math.min(1,Number.isFinite(v)?v:0));}
function holderPosition(wallet:string,rank:number):[number,number,number]{const angle=hashUnit(wallet)*Math.PI*2,ring=rank<=8?26:rank<=24?39:52,radius=ring+(hashUnit(`${wallet}:r`)-.5)*8,y=16+hashUnit(`${wallet}:y`)*42+(rank<=8?8:0);return[Math.cos(angle)*radius,y,Math.sin(angle)*radius];}
function tradePosition(seed:string,index:number):[number,number,number]{const angle=hashUnit(seed)*Math.PI*2,radius=18+(index%4)*6;return[Math.cos(angle)*radius,8+(index%7)*5,Math.sin(angle)*radius];}
export function buildTokenSystemSnapshot(tokenPlanet:FieldParticle,data:TokenSystemResponse):UniverseSnapshot{const mint=particleMint(tokenPlanet)??data.mint,galaxyId=tokenPlanet.originGalaxyId as GalaxyId,chainKey=data.chainKey??(typeof tokenPlanet.metadata?.chainKey==="string"?tokenPlanet.metadata.chainKey:"solana"),core:FieldParticle={...tokenPlanet,id:canonicalUniverseId(tokenPlanet.cosmicKind==="black-hole"?"black-hole":"planet",mint,galaxyId),cosmicKind:tokenPlanet.cosmicKind==="black-hole"?"black-hole":"planet",position:[0,-18,0],magnitudeBand:Math.max(.78,tokenPlanet.magnitudeBand),metadata:{...(tokenPlanet.metadata??{}),mint,chainKey,skyRole:"live",systemRole:"token-planet-core",holderStarCount:data.holders.length}};
const holders:FieldParticle[]=data.holders.map(holder=>({id:canonicalUniverseId("star",holder.wallet,galaxyId),kind:"wallet",cosmicKind:"star",originGalaxyId:galaxyId,verificationState:holder.sourceKind==="observed-fact"?"observed":"provider-reported",observedAt:holder.lastObservedAt,category:"transfer",magnitudeBand:holder.observedSharePct==null?clamp01(Math.log10(1+holder.netTokenObserved)/10):clamp01(Math.sqrt(Math.max(0,holder.observedSharePct)/100)),position:holderPosition(holder.wallet,holder.rank),source:holder.source,metadata:{name:`WALLET #${holder.rank}`,wallet:holder.wallet,parentMint:mint,linkedMints:[mint],chainKey:holder.chainKey||chainKey,holderRank:holder.rank,observedNetToken:holder.netTokenObserved,observedSharePct:holder.observedSharePct,tradeCount:holder.tradeCount,buySolObserved:holder.buySolObserved,sellSolObserved:holder.sellSolObserved,buyValueUsd:holder.buyValueUsd,sellValueUsd:holder.sellValueUsd,lastObservedAt:holder.lastObservedAt,sourceKind:holder.sourceKind,holderEvidenceMethod:data.method??"chain-qualified-indexed-positive-net-position-v2",skyRole:"live",systemRole:"holder-star",interactive:true}}));
const trades:FieldParticle[]=data.trades.slice(0,20).map((trade,index)=>({id:canonicalUniverseId("comet",trade.signature||`${trade.wallet}:${trade.observedAt}:${index}`,galaxyId),eventId:trade.signature??undefined,kind:"transaction",cosmicKind:"comet",originGalaxyId:galaxyId,verificationState:trade.sourceKind==="observed-fact"?"observed":"provider-reported",observedAt:trade.observedAt,category:trade.side==="buy"?"swap":"transfer",magnitudeBand:clamp01(Math.log10(1+Math.max(0,trade.solAmount??trade.valueUsd??0))/3),position:tradePosition(trade.signature||`${trade.wallet}:${trade.observedAt}`,index),source:trade.source,metadata:{mint,wallet:trade.wallet,chainKey:trade.chainKey||chainKey,side:trade.side,solAmount:trade.solAmount,tokenAmount:trade.tokenAmount,priceSol:trade.priceSol,priceUsd:trade.priceUsd,valueUsd:trade.valueUsd,sourceKind:trade.sourceKind,sig:trade.signature,skyRole:"live",systemRole:"token-system-comet"}}));
const belt=liquidityBeltForPlanet(core),particles=[core,...(belt?[belt]:[]),...holders,...trades],times=particles.map(p=>p.observedAt).filter(Number.isFinite),now=Date.now();return{galaxyId,windowStart:times.length?Math.min(...times):now,windowEnd:times.length?Math.max(...times):now,observedEventCount:holders.length+trades.length,samplingPolicy:`token-system D1-only · ${chainKey} · positive-net retained wallet stars · recent chain-qualified comets`,coverageStatement:data.disclosure,sources:[...new Set(particles.map(p=>p.source).filter((v):v is string=>Boolean(v)))],particles};}
