import { synthesizeAlienVoice, type AlienVoiceAlignment } from "@/lib/alien-voice";
export type VoiceHandle={speaking:boolean;stop:()=>void};
type AlienVoiceOptions={muted:boolean;volume:number;language?:string;onBoundary?:(progress:number)=>void;onEnergy?:(energy:number)=>void;onStart?:()=>void;onEnd?:()=>void};
let sharedAudioContext:AudioContext|null=null;
function getAudioContext(){if(sharedAudioContext&&sharedAudioContext.state!=="closed")return sharedAudioContext;const AudioCtx=globalThis.AudioContext??(globalThis as typeof globalThis&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)return null;try{sharedAudioContext=new AudioCtx({latencyHint:"interactive"});return sharedAudioContext;}catch{return null;}}
function pickVoice(language="en-US"){const voices=globalThis.speechSynthesis?.getVoices?.()??[],base=language.toLowerCase().split("-")[0],same=voices.filter(v=>v.lang?.toLowerCase().startsWith(base));const natural=same.find(v=>/natural|enhanced|google us english|samantha|aria|jenny|ava|serena/i.test(v.name));return natural??same.find(v=>v.default)??same[0]??voices.find(v=>v.default)??voices[0]??null;}
function base64Bytes(value:string){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer;}
function scheduleAlignment(alignment:AlienVoiceAlignment|null,options:AlienVoiceOptions,timers:ReturnType<typeof setTimeout>[]){if(!alignment)return;for(let i=0;i<alignment.characters.length;i+=2){if(!alignment.characters[i]?.trim())continue;timers.push(globalThis.setTimeout(()=>options.onBoundary?.(i/alignment.characters.length),Math.max(0,alignment.starts[i]*1000)));}}
function playBrowserVoice(text:string,options:AlienVoiceOptions,isStopped:()=>boolean,finish:()=>void,setStop:(stop:()=>void)=>void){const synth=globalThis.speechSynthesis;if(!synth||isStopped())return false;synth.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=options.language??"en-US";utterance.rate=1;utterance.pitch=1;utterance.volume=options.volume;const voice=pickVoice(utterance.lang);if(voice)utterance.voice=voice;utterance.onstart=()=>{if(!isStopped())options.onStart?.();};utterance.onboundary=event=>{options.onBoundary?.(text.length?(event.charIndex??0)/text.length:0);options.onEnergy?.(.38);globalThis.setTimeout(()=>!isStopped()&&options.onEnergy?.(.08),70);};utterance.onend=finish;utterance.onerror=finish;setStop(()=>synth.cancel());synth.speak(utterance);return true;}
export function unlockSpeech(){const ctx=getAudioContext();if(ctx?.state==="suspended")void ctx.resume();if(!globalThis.speechSynthesis)return;globalThis.speechSynthesis.cancel();const warm=new SpeechSynthesisUtterance(" ");warm.volume=0;globalThis.speechSynthesis.speak(warm);globalThis.speechSynthesis.cancel();}
export function speakText(text:string,options:AlienVoiceOptions):VoiceHandle{let stopped=false,ended=false,activeStop=()=>{},animationFrame=0;const timers:ReturnType<typeof setTimeout>[]=[];const handle:VoiceHandle={speaking:!options.muted&&Boolean(text.trim()),stop(){if(stopped)return;stopped=true;handle.speaking=false;activeStop();cancelAnimationFrame(animationFrame);for(const timer of timers)clearTimeout(timer);options.onEnergy?.(0);}};const finish=()=>{if(ended||stopped)return;ended=true;handle.speaking=false;cancelAnimationFrame(animationFrame);for(const timer of timers)clearTimeout(timer);options.onEnergy?.(0);options.onEnd?.();};if(!handle.speaking){options.onEnd?.();return handle;}
  void(async()=>{const delivery=await synthesizeAlienVoice({data:{text}});if(stopped)return;const ctx=getAudioContext();if(!delivery.ok||!delivery.audioBase64||!ctx){playBrowserVoice(text,options,()=>stopped,finish,stop=>{activeStop=stop;});return;}try{await ctx.resume();const audio=await ctx.decodeAudioData(base64Bytes(delivery.audioBase64));if(stopped)return;const source=ctx.createBufferSource();source.buffer=audio;source.playbackRate.value=1;const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=8;compressor.ratio.value=1.5;compressor.attack.value=.008;compressor.release.value=.18;const master=ctx.createGain();master.gain.value=options.volume;const analyser=ctx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.68;source.connect(compressor).connect(master).connect(analyser).connect(ctx.destination);const samples=new Uint8Array(analyser.fftSize),energyTick=()=>{if(stopped||ended)return;analyser.getByteTimeDomainData(samples);let sum=0;for(const value of samples){const centered=(value-128)/128;sum+=centered*centered;}const rms=Math.sqrt(sum/samples.length);options.onEnergy?.(Math.max(0,Math.min(1,(rms-.008)*5.5)));animationFrame=requestAnimationFrame(energyTick);};source.onended=finish;activeStop=()=>{try{source.stop();}catch{}source.disconnect();};scheduleAlignment(delivery.alignment,options,timers);options.onStart?.();source.start();energyTick();}catch{if(!stopped)playBrowserVoice(text,options,()=>stopped,finish,stop=>{activeStop=stop;});}})();return handle;}
