import { synthesizeAlienVoice, type AlienVoiceAlignment } from "@/lib/alien-voice";
export type VoiceHandle={speaking:boolean;stop:()=>void};
type AlienVoiceOptions={muted:boolean;volume:number;language?:string;onBoundary?:(progress:number)=>void;onEnergy?:(energy:number)=>void;onStart?:()=>void;onEnd?:()=>void};
let sharedAudioContext:AudioContext|null=null;
function getAudioContext(){if(sharedAudioContext&&sharedAudioContext.state!=="closed")return sharedAudioContext;const AudioCtx=globalThis.AudioContext??(globalThis as typeof globalThis&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!AudioCtx)return null;try{sharedAudioContext=new AudioCtx({latencyHint:"interactive"});return sharedAudioContext;}catch{return null;}}
function pickVoice(language="en"){const voices=globalThis.speechSynthesis?.getVoices?.()??[],lang=language.toLowerCase(),same=voices.filter(v=>v.lang?.toLowerCase().startsWith(lang.split("-")[0])),preferred=same.find(v=>/male|daniel|george|arthur|guy|david|mark|alex|thomas|google uk english male/i.test(v.name));return preferred??same[0]??voices[0]??null;}
function base64Bytes(value:string){const binary=atob(value),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes.buffer;}
function makeRoomImpulse(ctx:AudioContext){const length=Math.floor(ctx.sampleRate*.34),impulse=ctx.createBuffer(2,length,ctx.sampleRate);for(let channel=0;channel<2;channel++){const data=impulse.getChannelData(channel);for(let i=0;i<length;i++){const decay=Math.pow(1-i/length,4.6);data[i]=(Math.random()*2-1)*decay*(channel?.72:.82);}}return impulse;}
function scheduleAlignment(alignment:AlienVoiceAlignment|null,options:AlienVoiceOptions,timers:ReturnType<typeof setTimeout>[]){if(!alignment)return;for(let i=0;i<alignment.characters.length;i+=2){if(!alignment.characters[i]?.trim())continue;timers.push(globalThis.setTimeout(()=>options.onBoundary?.(i/alignment.characters.length),Math.max(0,alignment.starts[i]*1000)));}}
function playBrowserVoice(text:string,options:AlienVoiceOptions,isStopped:()=>boolean,finish:()=>void,setStop:(stop:()=>void)=>void){const synth=globalThis.speechSynthesis;if(!synth||isStopped())return false;synth.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang=options.language??"en-US";utterance.rate=.92;utterance.pitch=.78;utterance.volume=options.volume;const voice=pickVoice(utterance.lang);if(voice)utterance.voice=voice;utterance.onstart=()=>{if(!isStopped())options.onStart?.();};utterance.onboundary=event=>{options.onBoundary?.(text.length?(event.charIndex??0)/text.length:0);options.onEnergy?.(.42);globalThis.setTimeout(()=>!isStopped()&&options.onEnergy?.(.1),80);};utterance.onend=finish;utterance.onerror=finish;setStop(()=>synth.cancel());synth.speak(utterance);return true;}
export function unlockSpeech(){const ctx=getAudioContext();if(ctx?.state==="suspended")void ctx.resume();if(!globalThis.speechSynthesis)return;globalThis.speechSynthesis.cancel();const warm=new SpeechSynthesisUtterance(" ");warm.volume=0;globalThis.speechSynthesis.speak(warm);globalThis.speechSynthesis.cancel();}
export function speakText(text:string,options:AlienVoiceOptions):VoiceHandle{let stopped=false,ended=false,activeStop=()=>{},animationFrame=0;const timers:ReturnType<typeof setTimeout>[]=[];const handle:VoiceHandle={speaking:!options.muted&&Boolean(text.trim()),stop(){if(stopped)return;stopped=true;handle.speaking=false;activeStop();cancelAnimationFrame(animationFrame);for(const timer of timers)clearTimeout(timer);options.onEnergy?.(0);}};const finish=()=>{if(ended||stopped)return;ended=true;handle.speaking=false;cancelAnimationFrame(animationFrame);for(const timer of timers)clearTimeout(timer);options.onEnergy?.(0);options.onEnd?.();};if(!handle.speaking){options.onEnd?.();return handle;}
  void(async()=>{const delivery=await synthesizeAlienVoice({data:{text}});if(stopped)return;const ctx=getAudioContext();if(!delivery.ok||!delivery.audioBase64||!ctx){playBrowserVoice(text,options,()=>stopped,finish,stop=>{activeStop=stop;});return;}try{await ctx.resume();const audio=await ctx.decodeAudioData(base64Bytes(delivery.audioBase64));if(stopped)return;const source=ctx.createBufferSource();source.buffer=audio;source.playbackRate.value=.99;const dry=ctx.createGain();dry.gain.value=.96;const warmth=ctx.createBiquadFilter();warmth.type="peaking";warmth.frequency.value=180;warmth.Q.value=.72;warmth.gain.value=1.6;const presence=ctx.createBiquadFilter();presence.type="peaking";presence.frequency.value=2600;presence.Q.value=.8;presence.gain.value=-.8;const convolver=ctx.createConvolver();convolver.buffer=makeRoomImpulse(ctx);const reverb=ctx.createGain();reverb.gain.value=.035;const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-16;compressor.knee.value=10;compressor.ratio.value=2.2;const master=ctx.createGain();master.gain.value=options.volume;const analyser=ctx.createAnalyser();analyser.fftSize=256;analyser.smoothingTimeConstant=.72;source.connect(dry).connect(warmth).connect(presence).connect(compressor);source.connect(convolver).connect(reverb).connect(compressor);compressor.connect(master).connect(analyser).connect(ctx.destination);const samples=new Uint8Array(analyser.fftSize),energyTick=()=>{if(stopped||ended)return;analyser.getByteTimeDomainData(samples);let sum=0;for(const value of samples){const centered=(value-128)/128;sum+=centered*centered;}const rms=Math.sqrt(sum/samples.length);options.onEnergy?.(Math.max(0,Math.min(1,(rms-.01)*6)));animationFrame=requestAnimationFrame(energyTick);};source.onended=finish;activeStop=()=>{try{source.stop();}catch{}source.disconnect();};scheduleAlignment(delivery.alignment,options,timers);options.onStart?.();source.start();energyTick();}catch{if(!stopped)playBrowserVoice(text,options,()=>stopped,finish,stop=>{activeStop=stop;});}})();return handle;}
