import { useEffect, useRef, useState } from "react";
import { Menu, Volume2, VolumeX } from "lucide-react";
import type { FieldOS } from "@/lib/field/field-os";
import type { UniverseDataStatus } from "@/lib/universe-data/contracts";
import { UniverseWorkspace } from "@/components/universe-workspace";
import { TraderHoldingsCutPanel } from "@/components/trader-holdings-cut";
import { createResearchThreadContext } from "@/lib/research-thread";
import { FomoClosedTradesPanel } from "@/components/fomo-closed-trades";
import { statusBadge } from "@/components/colosseum-metrics";
import { SocialFiWorkspace } from "@/components/socialfi-workspace";
import { ResearchIndexWorkspace } from "@/components/research-index-workspace";
import { FIELD_SHEET_CSS, MySkyShelves, TraderSheet } from "@/components/field-sheets";
import { ReplayStudio } from "@/components/replay-studio";
import { GALAXIES, GALAXY_CHAIN_LABEL, GALAXY_ORIGIN_CHIPS, ROOM_LABEL, getGalaxy, roomFor } from "@/lib/field/galaxies";
import { ADVANCED_MODES, ANALYSIS_MODES, MODE_HINT, TOOL_TITLE, type FieldMode, type FieldSection, type FocusedParticle, type GalaxyDefinition, type IntelligenceResult, type OrganismState, type EvidenceRecord } from "@/lib/field/types";
import { shareIdFromSearch } from "../../js/trickster-story-manifest.mjs";
import { inboundGalaxyFromSearch, inboundWorkspaceMode, subjectPrefillFromSearch } from "@/lib/field/ux-simplify";
import { holdingsHighlightMint, holdingsWalletFromContext, type CutSubject } from "@/lib/field/trader-holdings";
import { formatHeat, particleMint } from "@/lib/field/volume-sky";
import { isWatched, type WatchItem, type WatchSubjectKind } from "@/lib/field/watchlist";
import { resolvePublicIdentifier } from "@/lib/intelligence";
import { saveResearchThread } from "@/lib/research-thread-store";

const SOCIALFI_UI_ENABLED=import.meta.env.VITE_SOCIALFI_UI_ENABLED==="true";
const MENU_PRIMARY=ANALYSIS_MODES;
const MENU_ADVANCED:{id:FieldMode;label:string}[]=[...ADVANCED_MODES,{id:"intelligence",label:"Intelligence"},{id:"index",label:"Index"},{id:"watchlist",label:"My Sky"},...(SOCIALFI_UI_ENABLED?[{id:"social" as const,label:"SOCIAL"}]:[]),{id:"query",label:"Query"}];
const MENU_ITEMS:{id:FieldMode;label:string}[]=[...MENU_PRIMARY,...MENU_ADVANCED];
const STATE_LABEL:Record<OrganismState,string>={idle:"THE FIELD IS CONSCIOUS",listening:"LISTENING",analyzing:"ANALYZING PUBLIC MEMORY",speaking:"SPEAKING OBSERVED FACTS",complete:"COMPLETE",return:"RETURNING TO FIELD"};
function watchSubject(focus:FocusedParticle|null):{subjectKind:WatchSubjectKind;subjectId:string}|null{if(!focus)return null;if(focus.cosmicKind==="planet"||focus.cosmicKind==="black-hole"||focus.cosmicKind==="supernova"){const mint=particleMint(focus);return mint?{subjectKind:"token",subjectId:mint}:null;}if(focus.cosmicKind==="star"&&typeof focus.metadata?.wallet==="string"&&focus.metadata.wallet.trim())return{subjectKind:"wallet",subjectId:focus.metadata.wallet.trim()};return null;}
function inboundShareId(){return shareIdFromSearch(globalThis.location?.search??"");}
function inboundPrefill(){return subjectPrefillFromSearch(globalThis.location?.search??"");}
function inboundMode(){return inboundWorkspaceMode(globalThis.location?.search??"",inboundShareId());}
function inboundGalaxy(){return inboundGalaxyFromSearch(globalThis.location?.search??"");}

export function AppShell(){
  const hostRef=useRef<HTMLDivElement>(null),osRef=useRef<FieldOS|null>(null),inputRef=useRef<HTMLInputElement>(null),queryInputRef=useRef<HTMLInputElement>(null),querySequence=useRef(0);
  const[mode,setMode]=useState<FieldMode>("explore"),[menuOpen,setMenuOpen]=useState(false),[queryActive,setQueryActive]=useState(false),[organismState,setOrganismState]=useState<OrganismState>("idle"),[result,setResult]=useState<IntelligenceResult|null>(null),[muted,setMuted]=useState(false),[focus,setFocus]=useState<FocusedParticle|null>(null),[galaxy,setGalaxy]=useState<GalaxyDefinition>(()=>getGalaxy("galaxy-zero")),[,setGalaxies]=useState<readonly GalaxyDefinition[]>(GALAXIES),[evidence,setEvidence]=useState<EvidenceRecord|null>(null),[askPrefill,setAskPrefill]=useState(""),[askNotice,setAskNotice]=useState(""),[watchlist,setWatchlist]=useState<readonly WatchItem[]>([]),[livePlanetCount,setLivePlanetCount]=useState(0),[fieldSection,setFieldSection]=useState<FieldSection>({kind:"galaxy",label:"Field",count:0}),[fieldUnavailable,setFieldUnavailable]=useState(false),[dataStatus,setDataStatus]=useState<UniverseDataStatus>({store:"memory-fallback",coverage:"degraded",circuitBreaker:null,disclosure:"Checking indexed universe coverage."}),[cutSubject,setCutSubject]=useState<CutSubject|null>(null),[hydrated,setHydrated]=useState(false);
  useEffect(()=>setHydrated(true),[]);
  useEffect(()=>{if(inboundShareId())setMode("trickster");else if(inboundMode()==="replay")setMode("replay");const host=hostRef.current;if(!host)return;let cancelled=false,os:FieldOS|null=null;void import("@/lib/field/field-os").then(({FieldOS})=>{if(cancelled||!hostRef.current)return;try{os=new FieldOS(hostRef.current,event=>{setMode(inboundShareId()?"trickster":event.mode);setQueryActive(event.queryActive);setOrganismState(event.organismState);setResult(event.result);setMuted(event.muted);setFocus(event.focus);setGalaxy(event.galaxy);setGalaxies(event.galaxies);setEvidence(event.evidence);setDataStatus(event.dataStatus);setAskPrefill(event.askPrefill);setAskNotice(event.askNotice);setWatchlist(event.watchlist);setLivePlanetCount(event.livePlanetCount);setFieldSection(event.fieldSection);});osRef.current=os;if(inboundShareId())os.setMode("trickster");else if(inboundPrefill()?.mode==="replay")os.setMode("replay");else{const requestedGalaxy=inboundGalaxy();if(requestedGalaxy)os.setGalaxy(requestedGalaxy);}os.setFieldSuspended(studioOpenRef.current);}catch(error){console.error("[field-shell] graphics unavailable; live intelligence fallback active",{error:String(error)});setFieldUnavailable(true);if(inboundShareId())setMode("trickster");else if(inboundMode()==="replay")setMode("replay");}}).catch(error=>{console.error("[field-shell] field module unavailable; live intelligence fallback active",{error:String(error)});setFieldUnavailable(true);if(inboundShareId())setMode("trickster");else if(inboundMode()==="replay")setMode("replay");});return()=>{cancelled=true;querySequence.current++;os?.destroy();osRef.current=null;};},[]);
  useEffect(()=>{if(!menuOpen)return;const close=(event:KeyboardEvent)=>event.key==="Escape"&&setMenuOpen(false);globalThis.addEventListener("keydown",close);return()=>globalThis.removeEventListener("keydown",close);},[menuOpen]);
  useEffect(()=>{if(askPrefill&&inputRef.current)inputRef.current.value=askPrefill;},[askPrefill]);
  const askRoomRef=useRef(galaxy.id),studioOpenRef=useRef(false);
  useEffect(()=>{if(askRoomRef.current===galaxy.id)return;askRoomRef.current=galaxy.id;setAskPrefill("");setAskNotice("");if(inputRef.current)inputRef.current.value="";if(queryInputRef.current)queryInputRef.current.value="";},[galaxy.id]);
  async function onAsk(value:string){const query=value.trim();if(!query)return;if(osRef.current){void osRef.current.submitQuery(query);return;}const sequence=++querySequence.current;setQueryActive(true);setResult(null);setMode("query");setOrganismState("analyzing");try{const resolved=await resolvePublicIdentifier({data:{query}});if(sequence!==querySequence.current)return;setResult(resolved);setOrganismState("complete");}catch(error){if(sequence!==querySequence.current)return;console.error("[field-shell] live intelligence fallback failed",{query,error:String(error)});setResult({ok:false,kind:"unknown",query,shortId:query.slice(-6),coverage:"degraded",observedAt:new Date().toISOString(),label:"resolver unavailable",source:null,disclosure:"No market claim was produced.",facts:["The live resolver could not be reached."],spokenText:"The live resolver could not be reached. Please try again."});setOrganismState("complete");}}
  function onQueryMode(){setMenuOpen(false);if(osRef.current)osRef.current.setMode("query");else{setMode("query");setQueryActive(true);}requestAnimationFrame(()=>inputRef.current?.focus());}
  function selectMode(id:FieldMode){setMenuOpen(false);if(id==="query")onQueryMode();else if(osRef.current)osRef.current.setMode(id);else setMode(id);}
  function openGalaxy(id:GalaxyDefinition["id"]){if(osRef.current)osRef.current.setGalaxy(id);else setGalaxy(getGalaxy(id));}
  const studioOpen=mode==="replay"&&!queryActive,workspaceOpen=!(["explore","query","watchlist","replay"] as FieldMode[]).includes(mode)&&!queryActive,closeStudio=()=>{try{const url=new URL(globalThis.location.href);if(url.searchParams.get("mode")==="replay"){for(const key of ["mode","wallet","mint","chain","from","to","room","symbol","name","t","thread"])url.searchParams.delete(key);globalThis.history.replaceState(null,"",url.pathname+(url.search||""));}}catch{}if(osRef.current)osRef.current.closeResearch();else setMode("explore");},timelineOpen=mode==="replay"||mode==="evidence"||mode==="trickster",returnToField=()=>{querySequence.current++;if(osRef.current)void osRef.current.returnToField();else{setQueryActive(false);setMode("explore");setResult(null);setOrganismState("idle");}};
  const focusedMint=particleMint(focus),subject=watchSubject(focus),watched=Boolean(subject&&isWatched(watchlist,subject.subjectKind,subject.subjectId)),heat=formatHeat(typeof focus?.metadata?.skyHeat==="number"&&(focus.metadata.skyHeatUnit==="usd"||focus.metadata.skyHeatUnit==="sol")?{value:focus.metadata.skyHeat,unit:focus.metadata.skyHeatUnit}:null),symbol=typeof focus?.metadata?.symbol==="string"?focus.metadata.symbol:null,focusedGalaxyId=typeof focus?.metadata?.targetGalaxyId==="string"&&GALAXIES.some(item=>item.id===focus.metadata?.targetGalaxyId)?focus.metadata.targetGalaxyId as GalaxyDefinition["id"]:null,focusedGalaxy=focusedGalaxyId?getGalaxy(focusedGalaxyId):null;
  const fomoName=typeof focus?.metadata?.displayName==="string"?focus.metadata.displayName:null,fomoPnl=typeof focus?.metadata?.reportedPnlUsd==="number"?focus.metadata.reportedPnlUsd:null;
  const afterbellRank=typeof focus?.metadata?.afterbellRank==="number"?focus.metadata.afterbellRank:null,afterbellTx=typeof focus?.metadata?.uniqueAfterCloseTxCount==="number"?focus.metadata.uniqueAfterCloseTxCount:typeof focus?.metadata?.transactionCount==="number"?focus.metadata.transactionCount:null,afterbellName=typeof focus?.metadata?.displayName==="string"?focus.metadata.displayName:typeof focus?.metadata?.name==="string"?focus.metadata.name:null;
  const room=roomFor(galaxy.id),focusedRoom=focusedGalaxyId?roomFor(focusedGalaxyId):null,focusTitle=typeof focus?.metadata?.displayName==="string"&&focus.metadata.displayName.trim()?focus.metadata.displayName.trim():typeof focus?.metadata?.name==="string"?focus.metadata.name:null,focusFact=typeof focus?.metadata?.factLine==="string"?focus.metadata.factLine:null,roomTag=room?ROOM_LABEL[room]:"FIELD";
  const slotValue=focusedGalaxy?`${focusedRoom?ROOM_LABEL[focusedRoom]:"FIELD"} · ENTERING`:focus?.cosmicKind==="star"&&(focus.metadata?.fomoTrader===true||focus.metadata?.afterbellTrader===true)?`${focusTitle??"Trader"}${focusFact?` · ${focusFact}`:""}`:fieldSection.kind==="trader-system"?`${roomTag} · ${fieldSection.trader?.identity??fieldSection.label} · ${fieldSection.count} ${room==="afterbell"?"XSTOCK":"TOKEN"}${fieldSection.count===1?"":"S"}`:fieldSection.kind==="afterbell-system"?`AFTERBELL · ${fieldSection.label} · ${fieldSection.count} TRADERS`:fieldSection.kind==="token-system"?`${roomTag} · ${fieldSection.label} · ${fieldSection.count} HOLDERS`:fieldSection.kind==="wallet-system"?`FIELD · ${fieldSection.label} · ${fieldSection.count} TOKENS`:fieldSection.kind==="watchlist"?`MY SKY · ${fieldSection.count} WATCHED`:focus?`${symbol||focus.cosmicKind.replace("-"," ")}${heat?` · ${heat}`:""}`:room?`${roomTag} · ${GALAXY_CHAIN_LABEL[galaxy.id]}${fieldSection.count?` · ${fieldSection.count} TRADERS`:""}`:`FIELD · ${GALAXY_CHAIN_LABEL[galaxy.id]}`;
  const selectedPlanet=fieldSection.kind==="trader-system"&&focus?.cosmicKind==="planet"&&focusedMint?{mint:focusedMint,symbol}:null;
  const searchPrefill=hydrated?inboundPrefill():null,traderWallet=holdingsWalletFromContext({focus,fieldSection,inboundWallet:searchPrefill?.wallet,verifyingCut:hydrated&&Boolean(inboundShareId())}),highlightMint=holdingsHighlightMint({focus,fieldSection,inboundMint:hydrated&&inboundShareId()?"":searchPrefill?.mint}),showHoldings=Boolean(traderWallet)&&fieldSection.kind!=="trader-system"&&fieldSection.kind!=="watchlist"&&!workspaceOpen&&!queryActive&&mode==="explore",contextWallet=cutSubject?.wallet||evidence?.wallet||traderWallet||(fieldSection.kind==="trader-system"?fieldSection.wallet:fieldSection.kind==="wallet-system"?fieldSection.wallet:fieldSection.kind==="token-system"?fieldSection.wallet??null:null)||"",indexMint=cutSubject?.mint||focusedMint||evidence?.mint||((fieldSection.kind==="token-system"||fieldSection.kind==="afterbell-system")?fieldSection.mint:""),workspaceMint=cutSubject?.mint||searchPrefill?.mint||focusedMint||((fieldSection.kind==="token-system"||fieldSection.kind==="afterbell-system")?fieldSection.mint:""),tokenSymbol=cutSubject?.symbol||symbol||((fieldSection.kind==="token-system"||fieldSection.kind==="afterbell-system")?fieldSection.label:null),tokenName=cutSubject?.name||(typeof focus?.metadata?.name==="string"?focus.metadata.name:fomoName||(fieldSection.kind==="trader-system"?fieldSection.label:null)),advancedOpen=MENU_ADVANCED.some(item=>item.id===mode);
  studioOpenRef.current=studioOpen;
  useEffect(()=>{osRef.current?.setFieldSuspended(studioOpen);},[studioOpen]);
  return <main className={`field-shell${queryActive?" field-shell--query":""}`} data-mode={queryActive?"query":mode} data-galaxy={galaxy.id} data-field-section={fieldSection.kind} data-field-count={fieldSection.count} data-coverage={dataStatus.coverage} data-field-fallback={fieldUnavailable||undefined}>
    <style>{FIELD_SHEET_CSS}</style>
    
    <div ref={hostRef} className="field-shell__field" />
    <div className="field-shell__chrome" hidden={queryActive} aria-hidden={queryActive}><header className="gz-top"><div className="gz-menu-wrap"><button type="button" className="gz-menu-button" aria-label="Open menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(open=>!open)}><Menu size={19}/></button>{menuOpen?<nav className="gz-menu" aria-label="Field modes">{MENU_PRIMARY.map(item=><button key={item.id} type="button" className={item.id==="trickster"?"gz-menu-hero":undefined} aria-pressed={mode===item.id} aria-label={MODE_HINT[item.id]} title={MODE_HINT[item.id]} onClick={()=>selectMode(item.id)}>{item.label}</button>)}<details className="gz-menu-more" open={advancedOpen||undefined}><summary>Advanced</summary>{MENU_ADVANCED.map(item=><button key={item.id} type="button" aria-pressed={mode===item.id} aria-label={MODE_HINT[item.id]} title={MODE_HINT[item.id]} onClick={()=>selectMode(item.id)}>{item.label}</button>)}</details><p className="gz-menu-status" title={dataStatus.disclosure}>{statusBadge(dataStatus.store)} · {dataStatus.coverage.toUpperCase()}</p></nav>:null}</div><form className="gz-search" role="search" onSubmit={event=>{event.preventDefault();onAsk(inputRef.current?.value??"");}}><input ref={inputRef} type="search" autoComplete="off" spellCheck={false} placeholder="Wallet, mint, ticker, handle" aria-label="Ask the Field: wallet, mint, ticker, or handle" onInput={()=>{if(askNotice)osRef.current?.clearAskNotice();}}/><button type="submit">ASK</button>{askNotice?<p className="gz-ask-notice" role="status">{askNotice}</p>:null}</form></header>
      <div className="gz-bottom" aria-label="Field dock"><span className="gz-caption">{slotValue}</span>{GALAXY_ORIGIN_CHIPS.map(item=><button key={item.id} type="button" className="gz-origin" data-room={item.id} aria-pressed={galaxy.id===item.id&&fieldSection.kind!=="watchlist"} aria-label={item.id==="galaxy-zero"?"Open the Field":`Open ${item.label}`} onClick={()=>openGalaxy(item.id)}>{item.label}</button>)}<button type="button" className="gz-origin" data-room="my-sky" aria-pressed={fieldSection.kind==="watchlist"} aria-label="Open My Sky" onClick={()=>osRef.current?.setMode("watchlist")}>MY SKY</button></div>
      {galaxy.id==="fomo"&&fieldSection.kind==="galaxy"&&!workspaceOpen&&!queryActive&&mode==="explore"?<FomoClosedTradesPanel onReplay={trade=>{saveResearchThread(createResearchThreadContext({galaxyId:"fomo",chainKey:trade.chain,wallet:trade.wallet,mint:trade.mint,symbol:trade.symbol??null,fromTs:trade.fromTs,toTs:trade.toTs,replayCursor:0}));setCutSubject({wallet:trade.wallet,mint:trade.mint,name:null,symbol:trade.symbol});selectMode("replay");}}/>:null}
      {fieldSection.kind==="trader-system"&&!workspaceOpen&&!queryActive&&mode==="explore"?<TraderSheet section={fieldSection} selected={selectedPlanet} traderWatched={Boolean(fieldSection.wallet&&isWatched(watchlist,"wallet",fieldSection.wallet))} tokenWatched={Boolean(selectedPlanet&&isWatched(watchlist,"token",selectedPlanet.mint))} onResearch={next=>{if(!osRef.current?.openTraderResearch(next))selectMode(next);}} onWatchTrader={()=>osRef.current?.toggleWatchTrader()} onWatchToken={()=>osRef.current?.toggleWatch()}/>:null}
      {fieldSection.kind==="watchlist"&&!workspaceOpen&&!queryActive?<MySkyShelves items={watchlist} onOpen={item=>void osRef.current?.openWatchItem(item)} onRemove={item=>osRef.current?.removeWatch(item)} onField={()=>openGalaxy("galaxy-zero")}/>:null}
      {showHoldings?<TraderHoldingsCutPanel wallet={traderWallet} highlightMint={highlightMint} onMakeCut={subject=>{saveResearchThread({wallet:subject.wallet,mint:subject.mint});setCutSubject(subject);selectMode("trickster");}}/>:null}
    </div>
    {studioOpen?<ReplayStudio muted={muted} onToggleMute={()=>osRef.current?.setMuted(!muted)} watchlist={watchlist} onToggleWatch={request=>{const galaxyId=request.room??(request.chainKey==="solana"?"solana-core":"fomo");osRef.current?.toggleWatchSubject(request.kind==="wallet"?{subjectKind:"wallet",subjectId:request.wallet,galaxyId,name:request.name,symbol:null,handle:request.handle,chainKey:request.chainKey,wallet:request.wallet,lastPrint:request.lastPrint}:{subjectKind:"token",subjectId:request.mint,galaxyId,name:request.symbol,symbol:request.symbol,mint:request.mint,chainKey:request.chainKey,lastPrint:request.lastPrint});}} onBack={closeStudio} onOpenRoom={id=>{closeStudio();openGalaxy(id);}}/>:null}
    {queryActive?<div className="query-experience"><button type="button" className="query-mute" aria-label={muted?"Unmute":"Mute"} onClick={()=>osRef.current?.setMuted(!muted)}>{muted?<VolumeX size={18}/>:<Volume2 size={18}/>}</button><div className="query-chin"><form className="query-experience__form" onSubmit={event=>{event.preventDefault();onAsk(queryInputRef.current?.value??"");}}><input ref={queryInputRef} type="search" autoComplete="off" spellCheck={false} placeholder="Ask again · wallet, tx, mint, NFT, program" aria-label="Ask the living field"/><button className="query-experience__submit" type="submit">ASK</button></form><div className="query-status"><b>{STATE_LABEL[organismState]}</b>{result?.spokenText?<p>{result.spokenText}</p>:null}</div><button type="button" className="query-experience__back" onClick={returnToField}>RETURN TO FIELD</button></div></div>:null}
    <section className={`field-shell__workspace${timelineOpen?" field-shell__workspace--timeline":""}`} hidden={!workspaceOpen}><div className="field-shell__workspace-head"><strong>{TOOL_TITLE[mode]??mode.replace("what-if","What-If")}</strong><button type="button" className="field-shell__close" onClick={returnToField}>Back</button></div><div className="field-shell__workspace-body">{mode==="intelligence"?<IntelligencePanel result={result} watchlist={watchlist} focus={focus} onAsk={()=>onQueryMode()} onAskSubject={id=>onAsk(id)} onOpenWatchlist={()=>osRef.current?.setMode("watchlist")}/>:null}{mode==="index"?<ResearchIndexWorkspace currentMint={indexMint||""} currentWallet={contextWallet} onOpenField={({mint,wallet})=>{if(mint&&osRef.current){osRef.current.focusMint(mint);return;}if(wallet){void onAsk(wallet);return;}returnToField();}}/>:null}{mode==="social"?<SocialFiWorkspace/>:null}{mode!=="intelligence"&&mode!=="index"&&mode!=="social"&&mode!=="replay"?<UniverseWorkspace mode={mode} galaxy={galaxy} evidence={evidence} askMint={workspaceMint} askWallet={cutSubject?.wallet||searchPrefill?.wallet||contextWallet} tokenName={tokenName||undefined} tokenSymbol={tokenSymbol||undefined} dataStatus={dataStatus} onBack={returnToField} onNarrate={text=>osRef.current?.narrateObserved(text)}/>:null}</div></section>
  </main>;
}
function IntelligencePanel({result,watchlist,focus,onAsk,onAskSubject,onOpenWatchlist}:{result:IntelligenceResult|null;watchlist:readonly WatchItem[];focus:FocusedParticle|null;onAsk:()=>void;onAskSubject:(id:string)=>void;onOpenWatchlist:()=>void}){const subject=watchSubject(focus);return <article className="workspace-copy"><h2>{result?`${result.label} · ${result.shortId}`:"Public memory, observed facts"}</h2>{result?<><p>{result.spokenText}</p><p>Coverage {result.coverage}{result.source?` · ${result.source}`:""}{result.disclosure?` · ${result.disclosure}`:""}</p><ul className="workspace-facts">{result.facts.map(fact=><li key={fact}>{fact}</li>)}</ul></>:<p>Tap a token PLANET to enter its wallet-STAR sky. Enter Fomo to study provider-reported trader context against retained public-chain evidence, or enter Afterbell to study retained tokenized-stock traders and after-close trades. Nothing here executes a trade.</p>}{subject?<button type="button" className="query-experience__submit" onClick={()=>onAskSubject(subject.subjectId)}>ASK THIS BODY</button>:<button type="button" className="query-experience__submit" onClick={onAsk}>ASK THE FIELD</button>}<section className="workspace-copy"><h2>My Sky</h2>{watchlist.length?<><ul className="workspace-facts">{watchlist.slice(0,20).map(item=><li key={`${item.subjectKind}:${item.subjectId}`}><button type="button" onClick={()=>onAskSubject(item.subjectId)}>{item.subjectKind.toUpperCase()} · {(item.symbol||item.name||item.subjectId.slice(0,10)).toString()}</button></li>)}</ul><button type="button" className="query-experience__submit" onClick={onOpenWatchlist}>OPEN MY SKY</button></>:<p>No saved objects yet. Focus a token planet or wallet star and add it to My Sky.</p>}</section></article>;}
