import { useEffect, useState } from "react";
import { LoaderCircle, Play, TrendingDown, TrendingUp } from "lucide-react";
import { getFomoClosedTradeResults, getFomoTraderSystem, type FomoClosedTrade, type FomoClosedTradeResultsResponse } from "@/lib/universe-data/fomo-client";

const short=(value:string)=>value.length>14?`${value.slice(0,6)}…${value.slice(-4)}`:value;
const money=(value:number)=>{const absolute=Math.abs(value),digits=absolute<1?4:absolute<1000?2:0;return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",minimumFractionDigits:0,maximumFractionDigits:digits}).format(value);};

export function FomoClosedTradesPanel({onReplay}:{onReplay:(trade:FomoClosedTrade)=>void}){
  const[data,setData]=useState<FomoClosedTradeResultsResponse|null>(null),[tab,setTab]=useState<"winners"|"losers">("winners"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[preparing,setPreparing]=useState("");
  useEffect(()=>{let active=true;setLoading(true);void getFomoClosedTradeResults({data:{limit:8}}).then(result=>{if(active){setData(result);setError(result.ok?"":result.error||"Closed-trade results are unavailable.");}}).catch(()=>{if(active)setError("Closed-trade results are unavailable.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  const rows=tab==="winners"?data?.winners??[]:data?.losers??[];
  async function openTrade(trade:FomoClosedTrade){if(preparing)return;setPreparing(trade.id);try{await getFomoTraderSystem({data:{handle:trade.handle}});}catch{}finally{setPreparing("");onReplay(trade);}}
  return <aside className="fomo-closed-trades" aria-label="Closed Fomo trader outcomes">
    <style>{`.fomo-closed-trades{position:absolute;z-index:23;left:12px;bottom:calc(max(10px, env(safe-area-inset-bottom)) + 60px);width:min(430px,calc(100vw - 24px));max-height:min(40vh,350px,calc(100dvh - 132px));overflow-x:hidden;overflow-y:auto;display:grid;gap:8px;padding:10px;border:1px solid rgba(226,236,255,.14);border-radius:15px;background:linear-gradient(155deg,rgba(11,13,21,.96),rgba(5,6,11,.94));backdrop-filter:blur(20px) saturate(135%);box-shadow:0 22px 70px rgba(0,0,0,.4);pointer-events:auto}.fomo-results__head{display:flex;align-items:flex-start;justify-content:space-between;flex-wrap:wrap;gap:10px}.fomo-results__head b{display:block;color:#f6f8ff;font:700 11px/1.2 var(--font-display);letter-spacing:.08em}.fomo-results__head span{display:block;margin-top:3px;color:var(--color-muted);font:500 11px/1.3 var(--font-mono)}.fomo-results__tabs{display:flex;gap:5px}.fomo-results__tabs button{min-height:44px;padding:0 9px;border:1px solid rgba(226,236,255,.13);border-radius:999px;background:rgba(255,255,255,.03);color:var(--color-muted);font:700 11px/1 var(--font-display);letter-spacing:.08em}.fomo-results__tabs button[aria-pressed=true]{color:#f7fbff;border-color:rgba(142,233,255,.3);background:linear-gradient(110deg,rgba(142,233,255,.1),rgba(169,156,255,.07))}.fomo-results__list{display:grid;gap:5px;overflow:auto;max-height:min(160px,28vh);scrollbar-width:thin}.fomo-result{width:100%;min-height:44px;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px;align-items:center;padding:8px 9px;border:1px solid rgba(226,236,255,.1);border-radius:10px;background:rgba(255,255,255,.025);color:inherit;text-align:left}.fomo-result:hover,.fomo-result:focus-visible{border-color:rgba(142,233,255,.25);background:rgba(142,233,255,.045);outline:none}.fomo-result__who{min-width:0;display:grid;gap:2px}.fomo-result__who b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#f3f6ff;font:650 11px/1.25 var(--font-sans)}.fomo-result__who span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--color-muted);font:500 11px/1.25 var(--font-mono)}.fomo-result__outcome{display:grid;justify-items:end;gap:3px}.fomo-result__outcome strong{font:750 11px/1 var(--font-mono)}.fomo-result__outcome strong[data-sign=win]{color:#68e39a}.fomo-result__outcome strong[data-sign=loss]{color:#ff8585}.fomo-result__outcome span{display:flex;align-items:center;gap:4px;color:var(--color-muted);font:650 11px/1 var(--font-mono);letter-spacing:.04em}.fomo-results__empty,.fomo-results__disclosure{margin:0;color:var(--color-muted);font:500 11px/1.4 var(--font-mono)}.fomo-results__disclosure{padding-top:2px;border-top:1px solid rgba(226,236,255,.08)}@media(max-width:560px){.fomo-closed-trades{left:8px;bottom:calc(max(10px, env(safe-area-inset-bottom)) + 60px);width:calc(100vw - 16px);max-height:min(420px,calc(100dvh - 132px));padding:8px}.fomo-results__list{max-height:min(120px,22vh)}.fomo-results__head span{max-width:none}}`}</style>
    <div className="fomo-results__head"><div><b>CLOSED TRADE OUTCOMES</b><span>Provider-reported past results for the current cohort. Not a ranking to copy. Not financial advice, not a recommendation, and not a promise of future results.</span></div><div className="fomo-results__tabs"><button type="button" aria-pressed={tab==="winners"} onClick={()=>setTab("winners")}><TrendingUp size={10}/> HIGHER REPORTED</button><button type="button" aria-pressed={tab==="losers"} onClick={()=>setTab("losers")}><TrendingDown size={10}/> LOWER REPORTED</button></div></div>
    {loading?<p className="fomo-results__empty"><LoaderCircle size={11}/> Reading cached closed trades…</p>:error?<p className="fomo-results__empty">DEGRADED · {error}</p>:rows.length?<div className="fomo-results__list">{rows.map(trade=><button key={trade.id} type="button" className="fomo-result" onClick={()=>void openTrade(trade)} disabled={Boolean(preparing)&&preparing!==trade.id}><span className="fomo-result__who"><b>{trade.displayName} · {trade.symbol||short(trade.mint)}</b><span>{trade.chain.toUpperCase()} · Fomo #{trade.rank??"?"} · {new Date(trade.closedAt).toLocaleDateString()} · {trade.observedIndexed&&trade.chartIndexed?"REPLAY READY":trade.observedIndexed?"RECEIPTS READY · MARKET LOADING":trade.chartIndexed?"MARKET READY · RECEIPTS MISSING":"INDEX ON OPEN"}</span></span><span className="fomo-result__outcome"><strong data-sign={trade.pnlUsd>=0?"win":"loss"}>{trade.pnlUsd>=0?"+":""}{money(trade.pnlUsd)}</strong><span>{preparing===trade.id?<><LoaderCircle size={9}/> INDEXING</>:<><Play size={9}/> REPLAY MOVIE</>}</span></span></button>)}</div>:<p className="fomo-results__empty">No qualifying cached {tab==="winners"?"higher reported":"lower reported"} closed trades are available yet. Missing coverage is not zero activity.</p>}
    {data?.disclosure?<p className="fomo-results__disclosure">{data.disclosure}</p>:null}
  </aside>;
}
