import { useEffect, useState } from "react";
import { LoaderCircle } from "lucide-react";
import { getTraderHoldings, type TraderHolding } from "@/lib/universe-data/research-index-client";
import { cutSubjectFromHolding, formatIndexedPnl, holdingTokenLabel, type CutSubject } from "@/lib/field/trader-holdings";

export function TraderHoldingsCutPanel({wallet, highlightMint, onMakeCut}:{wallet:string;highlightMint?:string|null;onMakeCut:(subject:CutSubject)=>void}){
  const[items,setItems]=useState<readonly TraderHolding[]>([]),[busy,setBusy]=useState(false),[disclosure,setDisclosure]=useState(""),[error,setError]=useState("");
  useEffect(()=>{let cancelled=false;setBusy(true);setError("");setItems([]);void getTraderHoldings({data:{wallet,limit:10}}).then(response=>{if(cancelled)return;setItems(response.items??[]);setDisclosure(response.disclosure||"");if(!response.ok&&response.error)setError(response.error);}).catch(()=>{if(cancelled)return;setItems([]);setError("holdings_unavailable");setDisclosure("Indexed holdings are unavailable. No PnL was invented.");}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;};},[wallet]);
  return <aside className="trader-holdings" aria-label="Indexed trader holdings">
    <style>{`.trader-holdings{position:absolute;z-index:23;left:50%;bottom:calc(max(10px,env(safe-area-inset-bottom)) + 46px);transform:translateX(-50%);width:min(420px,calc(100vw - 24px));display:grid;gap:8px;padding:10px 11px 11px;border:1px solid rgba(226,236,255,.16);border-radius:16px;background:linear-gradient(160deg,rgba(12,14,22,.92),rgba(5,6,11,.88));backdrop-filter:blur(18px) saturate(140%);box-shadow:0 18px 48px rgba(0,0,0,.38),inset 0 1px rgba(255,255,255,.04);pointer-events:auto}.trader-holdings__head{display:grid;gap:3px}.trader-holdings__head b{font:700 11px/1.2 var(--font-display);letter-spacing:.04em}.trader-holdings__head span{color:var(--color-muted);font:600 8px/1.35 var(--font-mono);letter-spacing:.06em}.trader-holdings__list{display:grid;gap:5px;max-height:min(36vh,280px);overflow-y:auto}.trader-holdings__row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;width:100%;min-height:42px;padding:8px 10px;border:1px solid rgba(226,236,255,.12);border-radius:12px;background:rgba(255,255,255,.03);color:var(--color-fg);text-align:left}.trader-holdings__row:hover,.trader-holdings__row:focus-visible,.trader-holdings__row[aria-current=true]{border-color:rgba(142,233,255,.34);background:linear-gradient(110deg,rgba(142,233,255,.08),rgba(169,156,255,.05));outline:none}.trader-holdings__row b{display:block;font:650 11px/1.25 var(--font-sans)}.trader-holdings__row small{display:block;margin-top:2px;color:var(--color-muted);font:600 8px/1.3 var(--font-mono)}.trader-holdings__pnl{font:700 10px/1 var(--font-mono);letter-spacing:.04em}.trader-holdings__pnl[data-known="false"]{color:var(--color-muted);font-weight:600}.trader-holdings__empty{margin:0;color:var(--color-muted);font:500 10px/1.45 var(--font-sans)}.trader-holdings__disclosure{margin:0;color:var(--color-muted);font:500 8px/1.4 var(--font-mono)}@media(max-width:560px){.trader-holdings{left:8px;right:8px;transform:none;width:auto}}`}</style>
    <div className="trader-holdings__head"><b>Make a Cut?</b><span>Choose a held token · indexed matched PnL only</span></div>
    {busy?<p className="trader-holdings__empty"><LoaderCircle size={13}/> Reading indexed holdings…</p>:error&&!items.length?<p className="trader-holdings__empty">DEGRADED · Indexed holdings unavailable. No PnL was invented.</p>:items.length? <div className="trader-holdings__list">{items.map(item=>{const pnl=formatIndexedPnl(item.matchedRealizedSol),subject=cutSubjectFromHolding(wallet,item);return <button type="button" className="trader-holdings__row" key={item.mint} aria-current={highlightMint===item.mint||undefined} disabled={!subject} onClick={()=>{if(subject)onMakeCut(subject);}}><span><b>{holdingTokenLabel(item)}</b><small>{item.openCount?"OPEN INVENTORY":"MATCHED ROUNDS"} · INDEXED</small></span><span className="trader-holdings__pnl" data-known={pnl.known}>{pnl.text}</span></button>})}</div>:<p className="trader-holdings__empty">No indexed holdings for this public wallet. Empty coverage stays empty.</p>}
    {disclosure?<p className="trader-holdings__disclosure">{disclosure}</p>:null}
  </aside>;
}
