import { useEffect, useMemo, useRef, useState } from "react";
import { BookOpen, CheckCircle2, LoaderCircle, Play } from "lucide-react";
import { callUniverseTool, type UniverseTool } from "@/lib/universe-intelligence";
import { MODE_HINT, TOOL_TITLE, type EvidenceRecord, type FieldMode, type GalaxyDefinition } from "@/lib/field/types";
import type { UniverseDataStatus } from "@/lib/universe-data/contracts";
import { ThesisCreatePanel, ThesisEvidencePanel } from "@/components/thesis-layer";
import { ReplayWorkspace } from "@/components/replay-workspace";
import { FrozenCutViewer, TricksterDirector } from "@/components/trickster-director";
import { loadResearchThread, saveResearchThread } from "@/lib/research-thread-store";
import {
  CompareDuel,
  DivergeChart,
  LuxuryMetric,
  extractSparklineValues,
  prefersReducedMotion,
  statusBadge,
  type Data,
} from "@/components/colosseum-metrics";
import { heroSubjectLabel, looksLikeMint, needsSelectedTrade, selectedTradeReady, subjectPrefillFromSearch } from "@/lib/field/ux-simplify";
import { cutShareHref, shareIdFromSearch } from "../../js/trickster-story-manifest.mjs";

const WSOL="So11111111111111111111111111111111111111112";
const obj=(value:unknown):Data=>value&&typeof value==="object"&&!Array.isArray(value)?value as Data:{};const arr=(value:unknown):unknown[]=>Array.isArray(value)?value:[];const text=(value:unknown)=>value==null?"":String(value);const num=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0;const finiteMs=(value:unknown)=>{const n=Number(value);return Number.isInteger(n)&&n>=1_000_000_000_000?n:null;};const short=(value:unknown)=>{const valueText=text(value);return valueText.length>18?`${valueText.slice(0,8)}…${valueText.slice(-6)}`:valueText;};const uniq=(values:string[])=>[...new Set(values.map(value=>value.trim()).filter(Boolean))].slice(0,100);
function replayRequest(wallet:string,mint:string,quoteMint:string){const thread=loadResearchThread(),sameSubject=Boolean(wallet&&mint&&thread.wallet===wallet&&thread.mint===mint),selectedWindow=sameSubject&&thread.fromTs&&thread.toTs&&!thread.replayRef?{from:Math.floor(thread.fromTs/1000),to:Math.ceil(thread.toTs/1000)}:{};return{wallets:[wallet].filter(Boolean),mint,quoteMint,bucketSeconds:60,...selectedWindow};}

function searchPrefill(){return subjectPrefillFromSearch(globalThis.location?.search??"");}
export function UniverseWorkspace({mode,galaxy,evidence,askMint,askWallet,tokenName,tokenSymbol,onNarrate,dataStatus,onBack}:{mode:FieldMode;galaxy:GalaxyDefinition;evidence:EvidenceRecord|null;askMint?:string;askWallet?:string;tokenName?:string;tokenSymbol?:string;onNarrate:(text:string)=>void;dataStatus?:UniverseDataStatus|null;onBack?:()=>void}){
  const inboundPrefill=searchPrefill();
  const[wallet,setWallet]=useState(evidence?.wallet??askWallet??inboundPrefill?.wallet??""),[walletB,setWalletB]=useState(""),[mint,setMint]=useState(evidence?.mint??askMint??inboundPrefill?.mint??""),[quoteMint,setQuoteMint]=useState(WSOL),[sequenceScope,setSequenceScope]=useState<"mint"|"wallet">("mint"),[holdDays,setHoldDays]=useState(7),[result,setResult]=useState<Data|null>(null),[replay,setReplay]=useState<Data|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const launchOrigin=evidence?.originGalaxyId&&evidence.originGalaxyId!=="galaxy-zero"&&evidence.originGalaxyId!=="fomo"?evidence.originGalaxyId:galaxy.id==="pump-fun"||galaxy.id==="pons"?galaxy.id:null;
  const badge=statusBadge(dataStatus?.store);
  const reduceMotion=prefersReducedMotion();
  const hero=heroSubjectLabel({name:tokenName,symbol:tokenSymbol});
  const inboundShareId=shareIdFromSearch(globalThis.location?.search??"");
  const verifyingCut=mode==="trickster"&&Boolean(inboundShareId);
  const tradeReady=selectedTradeReady(mode,{wallet,mint,walletB,hasEvidence:Boolean(evidence)});
  const autoKey=useRef("");
  useEffect(()=>{const thread=loadResearchThread(),prefill=searchPrefill();if(!evidence?.wallet&&!askWallet&&!prefill?.wallet&&thread.wallet)setWallet(thread.wallet);if(!evidence?.mint&&!askMint&&!prefill?.mint&&thread.mint)setMint(thread.mint);},[]);
  useEffect(()=>{if(evidence?.mint)setMint(evidence.mint);else if(askMint)setMint(askMint);else{const prefill=searchPrefill();if(prefill?.mint)setMint(prefill.mint);}},[evidence?.mint,askMint]);
  useEffect(()=>{if(evidence?.wallet)setWallet(evidence.wallet);else if(askWallet)setWallet(askWallet);else{const prefill=searchPrefill();if(prefill?.wallet)setWallet(prefill.wallet);}},[evidence?.wallet,askWallet]);
  useEffect(()=>{if(!evidence)return;const prior=loadResearchThread();saveResearchThread({galaxyId:galaxy.id,launchOrigin:launchOrigin??prior.launchOrigin,mint:evidence.mint??prior.mint,wallet:evidence.wallet??prior.wallet,evidenceIds:uniq([...prior.evidenceIds,evidence.eventId]),coverage:evidence.coverageStatement||prior.coverage});},[evidence?.eventId,galaxy.id,launchOrigin]);
  useEffect(()=>{if(!verifyingCut)return;void execute("trickster-read",{shareId:inboundShareId});},[mode,inboundShareId,verifyingCut]);
  async function execute(tool:UniverseTool,input:Data){const prior=loadResearchThread(),inputWallets=arr(input.wallets).map(text).filter(Boolean),heldMint=text(input.mint??input.token)||mint||prior.mint,heldWallet=text(input.wallet??input.subjectWallet??input.walletA)||inputWallets[0]||wallet||prior.wallet;saveResearchThread({galaxyId:galaxy.id,launchOrigin:launchOrigin??prior.launchOrigin,mint:heldMint||null,wallet:heldWallet||null});setBusy(true);setError("");try{const response=obj(await callUniverseTool({data:{tool,input}}));if(response.ok===false)throw new Error(text(response.error)||"The indexed record is unavailable.");setResult(response);if(tool==="replay"){const bundle=obj(response.bundle),subject=obj(bundle.subject),window=obj(bundle.window),coverage=obj(bundle.coverage),events=arr(bundle.events).map(obj),wallets=arr(subject.wallets).map(text).filter(Boolean),resolvedWallet=wallets[0]||heldWallet||"",resolvedMint=text(subject.mint)||heldMint||"",fromTs=finiteMs(window.startTime),toTs=finiteMs(window.endTime),eventIds=uniq(events.map(event=>text(event.signature??event.id))),first=events[0],last=events.at(-1),sameSubject=Boolean(resolvedWallet&&resolvedMint&&prior.wallet===resolvedWallet&&prior.mint===resolvedMint),entrySignature=sameSubject&&prior.entrySignature?prior.entrySignature:text(first?.signature)||null,exitSignature=sameSubject&&prior.exitSignature?prior.exitSignature:events.length>1&&text(last?.signature)!==text(first?.signature)?text(last?.signature)||null:null,replayRef=fromTs&&toTs?`replay:${resolvedWallet}:${resolvedMint}:${fromTs}:${toTs}`:prior.replayRef,sameReplay=Boolean(replayRef&&replayRef===prior.replayRef);setReplay(bundle);saveResearchThread({galaxyId:galaxy.id,launchOrigin:launchOrigin??prior.launchOrigin,mint:resolvedMint||null,wallet:resolvedWallet||null,fromTs,toTs,entrySignature,exitSignature,replayRef,replayCursor:sameReplay?prior.replayCursor:0,replaySpeed:sameReplay?prior.replaySpeed:1,evidenceIds:eventIds.length?uniq([...prior.evidenceIds,...eventIds]):prior.evidenceIds,coverage:text(coverage.statement)||prior.coverage});}return response;}catch(cause){setError(cause instanceof Error?cause.message:"The indexed record is unavailable.");return null;}finally{setBusy(false);}}
  useEffect(()=>{const key=`${mode}|${wallet}|${mint}|${walletB}|${holdDays}|${quoteMint}|${evidence?.eventId??""}|${inboundShareId}`;if(autoKey.current===key)return;if(mode==="replay"&&looksLikeMint(wallet)&&looksLikeMint(mint)){autoKey.current=key;void execute("replay",replayRequest(wallet,mint,quoteMint));return;}if(mode==="trickster"&&verifyingCut){autoKey.current=key;return;}if(mode==="trickster"&&looksLikeMint(wallet)&&looksLikeMint(mint)){autoKey.current=key;void execute("replay",replayRequest(wallet,mint,quoteMint));return;}if(mode==="what-if"&&looksLikeMint(wallet)&&looksLikeMint(mint)){autoKey.current=key;void execute("what-if",{wallet,mint,quoteMint,holdDays});return;}if(mode==="evidence"&&(evidence||mint)){autoKey.current=key;void execute("evidence",{mint:evidence?.mint??mint,subjectWallet:evidence?.wallet??wallet,signature:evidence?.signature,timestamp:evidence?evidence.observedAt*(evidence.observedAt<10_000_000_000?1000:1):Date.now()});return;}if(mode==="compare"&&wallet&&walletB){autoKey.current=key;void execute("compare",{walletA:wallet,walletB});}},[mode,wallet,mint,walletB,holdDays,quoteMint,evidence,inboundShareId,verifyingCut]);
  const replayBundle=replay??obj(result?.bundle),frozenManifest=obj(result?.manifest),frozenShareId=text(result?.shareId??result?.id);
  const statusChip=dataStatus?<p className="colosseum-status-chip" data-store={dataStatus.store} data-badge={badge} title={dataStatus.disclosure}><span>{badge}</span> · {dataStatus.coverage.toUpperCase()}</p>:null;
  const foldProps={wallet,setWallet,mint,setMint,quoteMint,setQuoteMint,holdDays:mode==="what-if"?holdDays:undefined,setHoldDays:mode==="what-if"?setHoldDays:undefined,hideMint:mode==="ghost"||mode==="compare",open:Boolean(inboundPrefill)};
  const details=<DetailsFold {...foldProps}/>;

  if(!tradeReady&&!verifyingCut&&needsSelectedTrade(mode)){
    return <WorkspaceFrame eyebrow={MODE_HINT[mode]} title={TOOL_TITLE[mode]??MODE_HINT[mode]} hero="" busy={false} error="" statusChip={statusChip}><div className="universe-pick"><p className="universe-empty">Pick a trade first, or enter a public wallet and token mint.</p><DetailsFold {...foldProps} open/>{mode==="compare"?<label>Second trader<input value={walletB} onChange={event=>setWalletB(event.target.value.trim())} placeholder="Public wallet"/></label>:null}<Action onClick={()=>onBack?.()}>Back</Action></div></WorkspaceFrame>;
  }

  if(mode==="replay")return <WorkspaceFrame eyebrow={galaxy.name} title="Watch this trade on the chart" hero={hero} busy={busy} error={error} statusChip={statusChip}>{details}<ReplayWorkspace bundle={replayBundle} waitingMint={mint}/></WorkspaceFrame>;
  if(mode==="evidence"){const context=obj(result?.context),eventMint=evidence?.mint??mint;return <WorkspaceFrame eyebrow="VERIFY" title="Receipts for this trade" hero={hero} busy={busy} error={error} statusChip={statusChip}>{evidence?<Receipt evidence={evidence}/>:null}{details}<EvidenceContext context={context} reduceMotion={reduceMotion}/><ThesisEvidencePanel mint={eventMint}/></WorkspaceFrame>}
  if(mode==="compare"){const comparison=obj(result?.comparison),summaryA=obj(result?.a),summaryB=obj(result?.b);return <WorkspaceFrame eyebrow={MODE_HINT.compare} title="Compare two traders side by side" hero={hero} busy={busy} error={error} statusChip={statusChip}><label>Second trader<input value={walletB} onChange={event=>setWalletB(event.target.value.trim())} placeholder="Public wallet"/></label><Action onClick={()=>void execute("compare",{walletA:wallet,walletB})} disabled={!wallet||!walletB}>Compare two traders side by side</Action>{result?<CompareDuel walletA={text(result.walletA)||wallet} walletB={text(result.walletB)||walletB} summaryA={summaryA} summaryB={summaryB} comparison={comparison} disclaimer={text(comparison.disclaimer||result.disclaimer)||"Observed public activity only. No skill, ownership, or identity ranking."}/>:null}{details}</WorkspaceFrame>;}
  if(mode==="what-if")return <WorkspaceFrame eyebrow={MODE_HINT["what-if"]} title="What if you held instead?" hero={hero} busy={busy} error={error} statusChip={statusChip}>{details}<SimulationView simulation={obj(result?.simulation)} reduceMotion={reduceMotion} showDiverge/></WorkspaceFrame>;
  if(mode==="ghost")return <WorkspaceFrame eyebrow="COUNTERFACTUAL HOLDING" title="Ghost portfolio" hero={hero} busy={busy} error={error} statusChip={statusChip}>{details}<Action onClick={()=>void execute("ghost",{wallet,quoteMint})} disabled={!wallet||!quoteMint}>REVEAL GHOST POSITIONS</Action><SimulationView simulation={obj(result?.simulation)} reduceMotion={reduceMotion}/></WorkspaceFrame>;
  if(mode==="sequences")return <WorkspaceFrame eyebrow="BOUNDED CHRONOLOGY" title="Market sequences" hero={hero} busy={busy} error={error} statusChip={statusChip}><label>SCOPE<select value={sequenceScope} onChange={event=>setSequenceScope(event.target.value as"mint"|"wallet")} id="sequence-scope"><option value="mint">TOKEN</option><option value="wallet">WALLET</option></select></label><label>PUBLIC TOKEN OR WALLET<input value={mint} onChange={event=>setMint(event.target.value.trim())}/></label><Action onClick={()=>void execute("sequences",{scopeType:sequenceScope,scopeValue:mint,limit:80})} disabled={!mint}>LOAD SEQUENCE</Action><EventList events={arr(result?.events)}/><Disclosure>{text(result?.disclaimer)||"Chronology does not prove economic causation."}</Disclosure></WorkspaceFrame>;
  if(mode==="trickster"&&verifyingCut){const verifyUrl=frozenShareId?cutShareHref(globalThis.location?.origin??"https://abullsapp.com",frozenShareId):cutShareHref(globalThis.location?.origin??"https://abullsapp.com",inboundShareId);return <WorkspaceFrame eyebrow="VERIFY" title="Frozen Cut" hero="" busy={busy} error={error} statusChip={statusChip}>{Object.keys(frozenManifest).length?<FrozenCutViewer record={result??{}} verifyUrl={verifyUrl||undefined}/>:null}</WorkspaceFrame>;}
  if(mode==="trickster")return <WorkspaceFrame eyebrow="Share the story with receipts" title="Make a Cut" hero={hero} busy={busy} error={error} statusChip={statusChip}>{Object.keys(frozenManifest).length?<FrozenCutViewer record={result??{}} verifyUrl={frozenShareId?cutShareHref(globalThis.location?.origin??"https://abullsapp.com",frozenShareId):undefined}/>:null}{details}{Object.keys(replayBundle).length?null:<div className="universe-actions"><Action onClick={()=>void execute("replay",replayRequest(wallet,mint,quoteMint))} disabled={!wallet||!mint}><Play size={14}/> Make a Cut from Replay</Action></div>}{Object.keys(replayBundle).length?<ReplayWorkspace bundle={replayBundle} waitingMint={mint} autoPlay/>:null}<TricksterDirector bundle={replayBundle} mint={mint} wallet={wallet} tokenLabel={hero}/><ThesisCreatePanel mint={mint} galaxyId={galaxy.id} replayBundle={replayBundle}/></WorkspaceFrame>;
  if(mode==="games"){const anomalies=arr(result?.anomalies);return <WorkspaceFrame eyebrow="NARRATED EDUCATION · NO SCORE" title="Learn from observed history" hero="" busy={busy} error={error} statusChip={statusChip}><p className="universe-lede">The Grey explains descriptive chain patterns. There are no missions, rankings, prizes, or progression loops.</p><Action onClick={async()=>{const response=await execute("education",{}),first=obj(arr(response?.anomalies)[0]),narration=first.headline?`Observed pattern: ${text(first.headline)}. This is descriptive evidence, not a prediction.`:"No indexed anomaly is available to narrate. I will not invent one.";onNarrate(narration);}}><BookOpen size={14}/> ASK THE GREY TO TEACH</Action><EventList events={anomalies}/><Disclosure>{text(result?.disclaimer)||"Observed anomalies are descriptive, not predictions or recommendations."}</Disclosure></WorkspaceFrame>}
  return null;
}
function WorkspaceFrame({eyebrow,title,hero,busy,error,children,statusChip}:{eyebrow:string;title:string;hero:string;busy:boolean;error:string;children:React.ReactNode;statusChip?:React.ReactNode}){return <article className="universe-workspace"><header><span>{eyebrow}</span><h2>{title}</h2>{hero?<p className="universe-hero">{hero}</p>:null}{statusChip}</header>{busy?<p className="universe-busy"><LoaderCircle size={15}/> Reading the indexed universe…</p>:null}{error?<p className="universe-error">{error}</p>:null}<div className="universe-workspace__body">{children}</div></article>}
function DetailsFold({wallet,setWallet,mint,setMint,quoteMint,setQuoteMint,holdDays,setHoldDays,hideMint=false,open=false}:{wallet:string;setWallet:(v:string)=>void;mint:string;setMint:(v:string)=>void;quoteMint:string;setQuoteMint:(v:string)=>void;holdDays?:number;setHoldDays?:(v:number)=>void;hideMint?:boolean;open?:boolean}){const fields=<div className="universe-inputs universe-inputs--details"><label>Public wallet<input value={wallet} onChange={event=>setWallet(event.target.value.trim())} placeholder="Wallet address"/></label>{!hideMint?<label>Token mint<input value={mint} onChange={event=>setMint(event.target.value.trim())} placeholder="Token mint"/></label>:null}<label>Quote mint<input value={quoteMint} onChange={event=>setQuoteMint(event.target.value.trim())} placeholder="WSOL"/></label>{setHoldDays!=null&&holdDays!=null?<label>Hold days<input type="number" min="1" max="365" value={holdDays} onChange={event=>setHoldDays(Number(event.target.value))}/></label>:null}</div>;return open?<div className="universe-details">{fields}</div>:<details className="universe-details"><summary>Details</summary>{fields}</details>}
function Action({onClick,disabled,children}:{onClick:()=>void;disabled?:boolean;children:React.ReactNode}){return <button className="universe-action" type="button" onClick={onClick} disabled={disabled}>{children}</button>}
function EvidenceContext({context,reduceMotion}:{context:Data;reduceMotion:boolean}){if(!Object.keys(context).length)return null;const pairs=arr(context.pricePairs),pair=obj(pairs[0]),candles=arr(pair.candles),spark=extractSparklineValues(candles);return <section className="universe-result"><div className="universe-metrics"><LuxuryMetric label="EVENTS" value={num(obj(context.activity).eventCount)} reducedMotion={reduceMotion} sparkValues={spark}/><LuxuryMetric label="WALLETS" value={num(obj(context.activity).walletCount)} reducedMotion={reduceMotion}/><LuxuryMetric label="ROUTES" value={num(obj(context.routes).routeRows)} reducedMotion={reduceMotion}/></div>{candles.length?<CandleChart candles={candles}/>:<p className="universe-empty">No indexed price series exists around this event. No price series was invented.</p>}<EventList events={arr(obj(context.activity).events)}/><Disclosure>{text(context.disclosure)}</Disclosure></section>}
function Receipt({evidence}:{evidence:EvidenceRecord}){return <div className="evidence-receipt"><CheckCircle2 size={18}/><div><b>{short(evidence.eventId)}</b><span>{evidence.verificationState} · slot {evidence.slot??"not indexed"}</span><span>{evidence.source??evidence.sources.join(" · ")}</span></div></div>}
function CandleChart({candles}:{candles:unknown[]}){const rows=candles.map(obj).filter(row=>num(row.high)||num(row.low));const range=useMemo(()=>{const highs=rows.map(row=>num(row.high)),lows=rows.map(row=>num(row.low));return{high:Math.max(...highs,1),low:Math.min(...lows,0)}},[rows]);if(!rows.length)return null;const y=(value:number)=>12+(1-(value-range.low)/Math.max(.0000001,range.high-range.low))*136;return <div className="candle-chart"><span>INDEXED OHLC · OBSERVED SWAPS</span><svg viewBox="0 0 640 160" role="img" aria-label="Indexed candlestick chart">{rows.slice(-90).map((row,index,shown)=>{const x=8+index*(624/Math.max(1,shown.length)),up=num(row.close)>=num(row.open);return <g key={`${text(row.timestamp)}-${index}`} className={up?"candle-up":"candle-down"}><line x1={x} x2={x} y1={y(num(row.high))} y2={y(num(row.low))}/><rect x={x-2} y={Math.min(y(num(row.open)),y(num(row.close)))} width="4" height={Math.max(1,Math.abs(y(num(row.open))-y(num(row.close))))}/></g>})}</svg></div>}
function EventList({events}:{events:unknown[]}){if(!events.length)return null;return <div className="universe-events">{events.slice(0,40).map((item,index)=>{const row=obj(item);return <div key={text(row.id??row.signature??index)}><time>{row.timestamp?new Date(num(row.timestamp)).toLocaleString():text(row.observed_at??row.observedAt)}</time><b>{text(row.side??row.kind??row.sequence_type??row.headline??"observed event")}</b><span>{short(row.signature??row.scope_value??row.source)}</span></div>})}</div>}
function MetricObject({value,reduceMotion,sparkValues}:{value:Data;reduceMotion?:boolean;sparkValues?:number[]}){const skip=new Set(["wallet","mint","quoteMint","quote_mint"]);const entries=Object.entries(value).filter(([key,entry])=>["string","number","boolean"].includes(typeof entry)&&!skip.has(key)&&!(typeof entry==="string"&&/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(entry)));if(!entries.length)return null;return <div className="universe-metrics universe-metrics--wrap">{entries.map(([key,entry],index)=><LuxuryMetric key={key} label={key.replaceAll(/([A-Z])/g," $1").toUpperCase()} value={typeof entry==="boolean"?String(entry):entry as string|number} reducedMotion={reduceMotion} sparkValues={index===0?sparkValues:undefined}/>)}</div>}
function SimulationView({simulation,reduceMotion,showDiverge=false}:{simulation:Data;reduceMotion?:boolean;showDiverge?:boolean}){if(!Object.keys(simulation).length)return null;const outcomes=arr(simulation.outcomes??simulation.positions);const seriesBag=obj(simulation.series);const spark=extractSparklineValues(seriesBag.closes??seriesBag.values??simulation.closes??[]);return <section className="universe-result">{showDiverge?<DivergeChart simulation={simulation}/>:null}<MetricObject value={simulation} reduceMotion={reduceMotion} sparkValues={spark.length>=2?spark:undefined}/><EventList events={outcomes}/><Disclosure>{text(simulation.disclaimer)}</Disclosure></section>}
function Disclosure({children}:{children:React.ReactNode}){return children?<p className="universe-disclosure">{children}</p>:null}
