/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiIntelligenceSplatRouteImport } from './routes/api.intelligence.$'
import { Route as ApiSocialAuthVerifyRouteImport } from './routes/api.social-auth.verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntelligenceSplatRoute = ApiIntelligenceSplatRouteImport.update({
  id: '/api/intelligence/$',
  path: '/api/intelligence/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSocialAuthVerifyRoute = ApiSocialAuthVerifyRouteImport.update({
  id: '/api/social-auth/verify',
  path: '/api/social-auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intelligence/$': typeof ApiIntelligenceSplatRoute
  '/api/social-auth/verify': typeof ApiSocialAuthVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intelligence/$': typeof ApiIntelligenceSplatRoute
  '/api/social-auth/verify': typeof ApiSocialAuthVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/intelligence/$': typeof ApiIntelligenceSplatRoute
  '/api/social-auth/verify': typeof ApiSocialAuthVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health' | '/api/intelligence/$' | '/api/social-auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/intelligence/$' | '/api/social-auth/verify'
  id: '__root__' | '/' | '/api/health' | '/api/intelligence/$' | '/api/social-auth/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiIntelligenceSplatRoute: typeof ApiIntelligenceSplatRoute
  ApiSocialAuthVerifyRoute: typeof ApiSocialAuthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/intelligence/$': {
      id: '/api/intelligence/$'
      path: '/api/intelligence/$'
      fullPath: '/api/intelligence/$'
      preLoaderRoute: typeof ApiIntelligenceSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/social-auth/verify': {
      id: '/api/social-auth/verify'
      path: '/api/social-auth/verify'
      fullPath: '/api/social-auth/verify'
      preLoaderRoute: typeof ApiSocialAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiIntelligenceSplatRoute: ApiIntelligenceSplatRoute,
  ApiSocialAuthVerifyRoute: ApiSocialAuthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
