import test from 'node:test';
import assert from 'node:assert/strict';
import { decodePonsSeedLaunch,nextBlockscoutCursor,parseBlockscoutHolderCount,normalizePonsFamilyLiveMarket,selectPonsEnrichmentQueue,__ponsFamilyLiveContract } from './intelligence-ponsfamily-live.mjs';
const TOKEN='0x0000000000000000000000000000000000000007';
const address=index=>`0x${Number(index).toString(16).padStart(40,'0')}`;
const topicAddress=value=>`0x${'0'.repeat(24)}${value.slice(2)}`;
const wordAddress=value=>`${'0'.repeat(24)}${value.slice(2)}`;
const wordUint=value=>BigInt(value).toString(16).padStart(64,'0');
const hash=character=>`0x${character.repeat(64)}`;

test('PonsFamily no longer needs a private holder provider to qualify tokens',()=>{assert.equal(__ponsFamilyLiveContract.selfPopulating,true);assert.equal(__ponsFamilyLiveContract.holderSource,'robinhood-blockscout');assert.equal(__ponsFamilyLiveContract.marketCapFloorUsd,75000);assert.equal(__ponsFamilyLiveContract.minimumHolders,750);assert.equal(__ponsFamilyLiveContract.entryCycles,1);assert.equal(__ponsFamilyLiveContract.maximumMembers,50);assert.equal(__ponsFamilyLiveContract.progressiveDiscovery,true);assert.equal(__ponsFamilyLiveContract.progressiveEnrichment,true);assert.equal(__ponsFamilyLiveContract.discoveryFactories,3);});
test('Blockscout token counters parse holder count',()=>{assert.equal(parseBlockscoutHolderCount({token_holders_count:'801'}),801);assert.equal(parseBlockscoutHolderCount({tokenHoldersCount:999}),999);assert.equal(parseBlockscoutHolderCount({}),null);});
test('Blockscout discovery cursor is preserved without inventing pagination',()=>{assert.deepEqual(nextBlockscoutCursor({next_page_params:{block_number:123,index:7}}),{block_number:123,index:7});assert.equal(nextBlockscoutCursor({next_page_params:null}),null);assert.equal(nextBlockscoutCursor({}),null);});
test('documented legacy V1 PONS origin decodes with the same verified launch event shape',()=>{const factory={version:'v1-legacy',address:'0x0c37a24f5d23a486fa692d1500881d698b1f77a4',topic:'0xdb51ea9ad51ab453a65a4cb7e60c3cb378c9501bb002609f8f97778fb6c4235a'},token=address(7),deployer=address(8),dexFactory=address(9),pairToken=address(10),pool=address(11);const launch=decodePonsSeedLaunch(factory,{topics:[factory.topic,topicAddress(token),topicAddress(deployer),topicAddress(dexFactory)],data:`0x${wordAddress(pairToken)}${wordAddress(pool)}${wordUint(0)}${wordUint(2)}${wordUint(3)}${wordUint(4)}${wordUint(5)}`,transaction_hash:hash('a'),block_hash:hash('b'),block_number:8963150,index:0});assert.equal(launch?.factory,factory.address);assert.equal(launch?.factoryVersion,'v1');assert.equal(launch?.token,token);assert.equal(launch?.pool,pool);assert.equal(launch?.initialBuyAmount,'5');});
test('DexScreener market and Blockscout holders normalize together',()=>{const pairs=[{chainId:'robinhood',baseToken:{address:TOKEN,symbol:'P7',name:'Pons Seven'},marketCap:90000,fdv:100000,priceUsd:'0.01',volume:{h24:5500},liquidity:{usd:21000},pairAddress:'0x0000000000000000000000000000000000000008',dexId:'test'}];const value=normalizePonsFamilyLiveMarket(TOKEN,pairs,801,2_000_000_000);assert.equal(value?.marketCapUsd,90000);assert.equal(value?.volumeH24Usd,5500);assert.equal(value?.holderCount,801);assert.match(value?.source??'',/blockscout/);});
test('missing holder evidence never gets invented',()=>{const pairs=[{chainId:'robinhood',baseToken:{address:TOKEN},marketCap:90000,volume:{h24:5500},liquidity:{usd:1}}];assert.equal(normalizePonsFamilyLiveMarket(TOKEN,pairs,null,2_000_000_000),null);});
test('enrichment queue cannot be monopolized by the newest unseen launches',()=>{const launches=Array.from({length:100},(_,i)=>({token:address(i+1),block_time:i+1}));const prior=[{token:address(100),active:1,updated_at:1000},{token:address(99),active:0,updated_at:10},{token:address(98),active:0,updated_at:20}];const queue=selectPonsEnrichmentQueue(launches,prior,10);assert.equal(queue.length,10);assert.equal(queue[0],address(100));assert.ok(queue.includes(address(99)));assert.ok(queue.includes(address(1)));assert.ok(queue.includes(address(2)));});
