import test from 'node:test';
import assert from 'node:assert/strict';
import { nextBlockscoutCursor,parseBlockscoutHolderCount,normalizePonsFamilyLiveMarket,selectPonsEnrichmentQueue,__ponsFamilyLiveContract } from './intelligence-ponsfamily-live.mjs';
const TOKEN='0x0000000000000000000000000000000000000007';
const address=index=>`0x${Number(index).toString(16).padStart(40,'0')}`;

test('PonsFamily no longer needs a private holder provider to qualify tokens',()=>{assert.equal(__ponsFamilyLiveContract.selfPopulating,true);assert.equal(__ponsFamilyLiveContract.holderSource,'robinhood-blockscout');assert.equal(__ponsFamilyLiveContract.marketCapFloorUsd,75000);assert.equal(__ponsFamilyLiveContract.minimumHolders,750);assert.equal(__ponsFamilyLiveContract.entryCycles,1);assert.equal(__ponsFamilyLiveContract.maximumMembers,50);assert.equal(__ponsFamilyLiveContract.progressiveDiscovery,true);assert.equal(__ponsFamilyLiveContract.progressiveEnrichment,true);});
test('Blockscout token counters parse holder count',()=>{assert.equal(parseBlockscoutHolderCount({token_holders_count:'801'}),801);assert.equal(parseBlockscoutHolderCount({tokenHoldersCount:999}),999);assert.equal(parseBlockscoutHolderCount({}),null);});
test('Blockscout discovery cursor is preserved without inventing pagination',()=>{assert.deepEqual(nextBlockscoutCursor({next_page_params:{block_number:123,index:7}}),{block_number:123,index:7});assert.equal(nextBlockscoutCursor({next_page_params:null}),null);assert.equal(nextBlockscoutCursor({}),null);});
test('DexScreener market and Blockscout holders normalize together',()=>{const pairs=[{chainId:'robinhood',baseToken:{address:TOKEN,symbol:'P7',name:'Pons Seven'},marketCap:90000,fdv:100000,priceUsd:'0.01',volume:{h24:5500},liquidity:{usd:21000},pairAddress:'0x0000000000000000000000000000000000000008',dexId:'test'}];const value=normalizePonsFamilyLiveMarket(TOKEN,pairs,801,2_000_000_000);assert.equal(value?.marketCapUsd,90000);assert.equal(value?.volumeH24Usd,5500);assert.equal(value?.holderCount,801);assert.match(value?.source??'',/blockscout/);});
test('missing holder evidence never gets invented',()=>{const pairs=[{chainId:'robinhood',baseToken:{address:TOKEN},marketCap:90000,volume:{h24:5500},liquidity:{usd:1}}];assert.equal(normalizePonsFamilyLiveMarket(TOKEN,pairs,null,2_000_000_000),null);});
test('enrichment queue cannot be monopolized by the newest unseen launches',()=>{const launches=Array.from({length:100},(_,i)=>({token:address(i+1),block_time:i+1}));const prior=[{token:address(100),active:1,updated_at:1000},{token:address(99),active:0,updated_at:10},{token:address(98),active:0,updated_at:20}];const queue=selectPonsEnrichmentQueue(launches,prior,10);assert.equal(queue.length,10);assert.equal(queue[0],address(100));assert.ok(queue.includes(address(99)));assert.ok(queue.includes(address(1)));assert.ok(queue.includes(address(2)));});
